//! Generated from TLA+ module: Raft
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Raft module
pub struct LRecord {
    pub candidate: int,
    pub follower: int,
    pub granted: int,
    pub has_entry: int,
    pub last_log_index: int,
    pub last_log_term: int,
    pub leader: int,
    pub leader_commit: int,
    pub match_index: int,
    pub prev_index: int,
    pub prev_term: int,
    pub success: int,
    pub term: int,
    pub value: int,
    pub voter: int,
}

/// State for Raft module
pub struct LState {
}

/// Constants for the module
pub struct LConstants {
    pub Constants: int,
    pub u64: Set<int>,
    pub State: int,
    pub RaftMessage: int,
}


/// u64_inc operator
pub open spec fn Lu64_inc(s: LState, c: LConstants, x: int) -> int {
    (x + 1)
}

/// u64_dec operator
pub open spec fn Lu64_dec(s: LState, c: LConstants, x: int) -> int {
    (x - 1)
}

/// Init operator
pub open spec fn LInit(s: LState, c: LConstants) -> bool {
    (((((((((arbitrary::<int>() == 0) && (arbitrary::<int>() == 8761388551int)) && (arbitrary::<bool>() == false)) && (arbitrary::<int>() == 0)) && (arbitrary::<Seq<int>>() == Seq::<int>::empty())) && (arbitrary::<int>() == 0)) && (Set::<int>::empty() == Set::<int>::empty())) && (arbitrary::<Seq<int>>() == Seq::<int>::empty())) && (arbitrary::<Seq<int>>() == Seq::<int>::empty()))
}

/// Timeout operator
pub open spec fn LTimeout(s: LState, s_: LState, c: LConstants, sent_packets: (LRecord)) -> bool {
    ((arbitrary::<int>() == 8761388551int) || (((((((((((arbitrary::<int>() == 2420160122int) && (arbitrary::<int>() == (arbitrary::<int>() + 1))) && (arbitrary::<int>() == 2420160122int)) && (arbitrary::<bool>() == true)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary() == Set::<int>::empty().union(set![arbitrary()]))) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == arbitrary())))
}

/// GrantVote operator
pub open spec fn LGrantVote(s: LState, s_: LState, c: LConstants, candidate_term: int, candidate_last_log_term: int, candidate_last_log_index: int, candidate_id: int, sent_packets: (LRecord)) -> bool {
    (((candidate_term >= arbitrary::<int>()) && !(arbitrary())) || (((((((((((arbitrary() == candidate_id) && (arbitrary() == candidate_term)) && (arbitrary::<int>() == 8761388551int)) && (arbitrary::<bool>() == true)) && (arbitrary() == candidate_id)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == arbitrary())))
}

/// ReceiveVoteGranted operator
pub open spec fn LReceiveVoteGranted(s: LState, s_: LState, c: LConstants, vote_term: int, vote_granted: bool, voter: int, sent_packets: ()) -> bool {
    (((((((((((((arbitrary::<int>() == 2420160122int) && (vote_granted == true)) && Set::<int>::empty().contains(voter)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary() == Set::<int>::empty().union(set![voter]))) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == Seq::<int>::empty()))
}

/// BecomeLeader operator
pub open spec fn LBecomeLeader(s: LState, s_: LState, c: LConstants, sent_packets: ()) -> bool {
    ((((((((((((arbitrary::<int>() == 2420160122int) && (arbitrary::<Seq<int>>().len() >= arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 4100380100int)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<Seq<int>>() == Seq::<int>::empty())) && (arbitrary::<Seq<int>>() == Seq::<int>::empty())) && (sent_packets == Seq::<int>::empty()))
}

/// ClientRequest operator
pub open spec fn LClientRequest(s: LState, s_: LState, c: LConstants, value: int, sent_packets: ()) -> bool {
    (((((((((((arbitrary::<int>() == 4100380100int) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary() == arbitrary::<Seq<int>>().push(LRecord { candidate: 0int, follower: 0int, granted: 0int, has_entry: 0int, last_log_index: 0int, last_log_term: 0int, leader: 0int, leader_commit: 0int, match_index: 0int, prev_index: 0int, prev_term: 0int, success: 0int, term: arbitrary(), value: value, voter: 0int }))) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == Seq::<int>::empty()))
}

/// SendAppendEntries operator
pub open spec fn LSendAppendEntries(s: LState, s_: LState, c: LConstants, follower: int, entry_value: int, prev_log_index: int, prev_log_term: int, has_entry: int, sent_packets: (LRecord)) -> bool {
    ((((((((((((arbitrary::<int>() == 4100380100int) && Set::<int>::empty().contains(follower)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == arbitrary()))
}

/// FollowerAppendEntries operator
pub open spec fn LFollowerAppendEntries(s: LState, s_: LState, c: LConstants, ae_term: int, ae_leader: int, ae_prev_index: int, ae_prev_term: int, ae_value: int, ae_has_entry: bool, ae_leader_commit: bool, sent_packets: (LRecord)) -> bool {
    ((((ae_term >= arbitrary::<int>()) && (arbitrary() == ae_term)) && (arbitrary::<int>() == 8761388551int)) && (arbitrary::<bool>() == if (ae_term > arbitrary::<int>()) { false } else { (arbitrary() && (arbitrary::<int>() == arbitrary::<int>())) }))
}

/// HandleAppendResponse operator
pub open spec fn LHandleAppendResponse(s: LState, s_: LState, c: LConstants, resp_term: int, resp_success: bool, resp_match_index: int, resp_follower: int, follower: int, new_match_index: int, sent_packets: ()) -> bool {
    (((((((((((((((arbitrary::<int>() == 4100380100int) && (resp_success == true)) && Set::<int>::empty().contains(follower)) && (new_match_index >= 0)) && (new_match_index <= arbitrary::<Seq<int>>().len())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary() == arbitrary().insert(follower, new_match_index))) && (arbitrary() == arbitrary().insert(follower, Lu64_inc(s, c, new_match_index)))) && (sent_packets == Seq::<int>::empty()))
}

/// HandleAppendReject operator
pub open spec fn LHandleAppendReject(s: LState, s_: LState, c: LConstants, resp_term: int, resp_success: bool, resp_match_index: int, resp_follower: int, follower: int, sent_packets: ()) -> bool {
    ((((arbitrary::<int>() == 4100380100int) && (resp_success == false)) && Set::<int>::empty().contains(follower)) && (arbitrary() == if (arbitrary().dom().contains(follower) && (arbitrary::<Seq<int>>()[follower] > 0)) { arbitrary().insert(follower, Lu64_dec(s, c, arbitrary::<Seq<int>>()[follower])) } else { (((((((((arbitrary() && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == Seq::<int>::empty())) }))
}

/// AdvanceCommitIndex operator
pub open spec fn LAdvanceCommitIndex(s: LState, s_: LState, c: LConstants, new_commit_index: int, sent_packets: ()) -> bool {
    ((((((((((((((arbitrary::<int>() == 4100380100int) && (new_commit_index > arbitrary::<int>())) && (new_commit_index <= arbitrary::<Seq<int>>().len())) && (arbitrary::<Seq<int>>()[(new_commit_index - 1)].term == arbitrary())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary() == new_commit_index)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == Seq::<int>::empty()))
}

/// StepDown operator
pub open spec fn LStepDown(s: LState, s_: LState, c: LConstants, new_term: int, sent_packets: ()) -> bool {
    (((((((((((new_term > arbitrary::<int>()) && (arbitrary() == new_term)) && (arbitrary::<int>() == 8761388551int)) && (arbitrary::<bool>() == false)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (Set::<int>::empty() == Set::<int>::empty())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == Seq::<int>::empty()))
}

/// Next operator
pub open spec fn LNext(s: LState, s_: LState, c: LConstants) -> bool {
    exists |sent_packets| (LTimeout(s, s_, c, sent_packets) || exists |candidate_term, candidate_last_log_term, candidate_last_log_index, candidate_id, sent_packets| (LGrantVote(s, s_, c, candidate_term, candidate_last_log_term, candidate_last_log_index, candidate_id, sent_packets) || exists |vote_term, vote_granted, voter, sent_packets| (LReceiveVoteGranted(s, s_, c, vote_term, vote_granted, voter, sent_packets) || exists |sent_packets| (LBecomeLeader(s, s_, c, sent_packets) || exists |value, sent_packets| (LClientRequest(s, s_, c, value, sent_packets) || exists |follower, entry_value, prev_log_index, prev_log_term, sent_packets| (LSendAppendEntries(s, s_, c, follower, entry_value, prev_log_index, prev_log_term, true, sent_packets) || exists |ae_term, ae_leader, ae_prev_index, ae_prev_term, ae_value, ae_has_entry, ae_leader_commit, sent_packets| (LFollowerAppendEntries(s, s_, c, ae_term, ae_leader, ae_prev_index, ae_prev_term, ae_value, ae_has_entry, ae_leader_commit, sent_packets) || exists |resp_term, resp_success, resp_match_index, resp_follower, follower, new_match_index, sent_packets| (c.u64.contains(follower) && c.u64.contains(new_match_index)) && (LHandleAppendResponse(s, s_, c, resp_term, resp_success, resp_match_index, resp_follower, follower, new_match_index, sent_packets) || exists |resp_term, resp_success, resp_match_index, resp_follower, follower, sent_packets| (c.u64.contains(follower)) && (LHandleAppendReject(s, s_, c, resp_term, resp_success, resp_match_index, resp_follower, follower, sent_packets) || exists |new_commit_index, sent_packets| (LAdvanceCommitIndex(s, s_, c, new_commit_index, sent_packets) || exists |new_term, sent_packets| LStepDown(s, s_, c, new_term, sent_packets)))))))))))
}

} // verus!
