//! Verus Spec-to-Implementation Transpiler
//!
//! This crate provides tools to transform Verus `spec fn` predicates (TLA-style
//! Init/Next specifications) into verified `exec fn` implementations.
//!
//! # Overview
//!
//! The transpiler pipeline consists of:
//! 1. **Parser** - Parse Verus spec functions from Rust source files
//! 2. **Annotation** - Process mode annotations from `.automan` files
//! 3. **Mode Analysis** - Analyze input/output modes and track assignments
//! 4. **Validation** - Check saturation, harmony, and obligation constraints
//! 5. **Translation** - Generate exec functions with proof linkage
//! 6. **Printing** - Format output as valid Rust/Verus code
//!
//! # Example
//!
//! ```ignore
//! use verus_transpiler::{Transpiler, TranspilerConfig};
//!
//! let config = TranspilerConfig::default();
//! let transpiler = Transpiler::new(config);
//!
//! let result = transpiler.transpile_file(
//!     "src/protocol/RSL/acceptor.rs",
//!     "src/protocol/RSL/acceptor.automan",
//! )?;
//!
//! std::fs::write("src/implementation/RSL/acceptor_gen.rs", result)?;
//! ```

pub mod annotation;
pub mod ast;
pub mod build_integration;
pub mod checker;
pub mod codegen;
pub mod config;
pub mod error;
pub mod moder;
pub mod parser;
pub mod printer;
pub mod runtime;
pub mod templates;
pub mod translator;
pub mod types;

// Re-export commonly used types
pub use annotation::{AnnotationParser, FunctionAnnotation, ModuleAnnotations};
pub use ast::{Expr, Parameter, ParameterMode, SpecFunction, Type};
pub use checker::{validate_function, HarmonyChecker, ObligationChecker, SaturationChecker};
pub use codegen::{generate_all_types, GeneratedCode, TemplateCodeGenerator, TypeGenerator};
pub use config::{ModuleConfig, NamingConfig, OutputConfig, TranspilerConfig as FileConfig};
pub use error::{DiagnosticAccumulator, TranspileError, TranspileResult, TranspileWarning};
pub use moder::{AnnotatedFunction, AssignmentTracker, ModeAnalyzer, PredicateKind};
pub use parser::{parse_file, VerusParser};
pub use printer::{print_function, Printer, PrinterConfig};
pub use runtime::{DeepClone, ExecType, SpecType, Validated, ValidatedResult, View};
pub use templates::{match_expression, QuantifierTemplate, TemplateMatcher};
pub use translator::{ExecFunction, Translator, TranslatorConfig};
pub use types::{EnumDef, FieldDef, FunctionSig, StructDef, TypeParser, TypeRegistry};

use std::path::Path;

/// Main transpiler configuration
#[derive(Debug, Clone, Default)]
pub struct TranspilerConfig {
    /// Configuration for the translator
    pub translator: TranslatorConfig,
    /// Configuration for the printer
    pub printer: PrinterConfig,
    /// Custom imports to include in generated code (before verus! block)
    pub custom_imports: Vec<String>,
    /// Whether to generate type definitions inline from the spec file.
    /// When true, parses struct/enum definitions from the spec file and generates
    /// corresponding exec types with View trait implementations.
    /// This makes the output self-contained without depending on manual implementation code.
    pub generate_inline_types: bool,
    /// Type remapping table for custom type name mappings
    pub type_remapping: std::collections::HashMap<String, String>,
}

/// Main transpiler orchestrating the pipeline
pub struct Transpiler {
    config: TranspilerConfig,
}

impl Transpiler {
    /// Create a new transpiler with the given configuration
    pub fn new(config: TranspilerConfig) -> Self {
        Self { config }
    }

    /// Transpile a single spec file with its annotation file
    pub fn transpile_file(
        &self,
        spec_path: &Path,
        annotation_path: &Path,
    ) -> TranspileResult<String> {
        // Parse spec file
        let spec_fns = parse_file(spec_path)?;

        // Parse annotations
        let annotations = annotation::parse_annotation_file(annotation_path)?;

        // Process each function
        let mut mode_analyzer = ModeAnalyzer::new();
        let translator = Translator::new(self.config.translator.clone());
        let mut printer = Printer::new(self.config.printer.clone());

        let mut output = String::new();
        output.push_str("// Auto-generated by verus-transpiler\n");
        output.push_str("// DO NOT EDIT MANUALLY\n\n");

        // Add custom imports before verus! block
        for import in &self.config.custom_imports {
            output.push_str(import);
            output.push('\n');
        }
        if !self.config.custom_imports.is_empty() {
            output.push('\n');
        }

        output.push_str("verus! {\n\n");

        // Generate inline types if configured
        if self.config.generate_inline_types {
            let type_defs = types::parse_types_from_file(spec_path)?;
            let registry = types::build_registry(type_defs);
            let naming_config = crate::config::NamingConfig {
                spec_prefix: self.config.translator.spec_prefix.clone(),
                exec_prefix: self.config.translator.exec_prefix.clone(),
                ..Default::default()
            };
            let type_gen = TypeGenerator::with_options(
                naming_config.clone(),
                self.config.type_remapping.clone(),
                self.config.translator.validity_predicate_name.clone(),
            );

            // Generate structs
            for struct_def in registry.structs.values() {
                if struct_def.is_spec {
                    let generated = type_gen.generate_struct(struct_def);
                    output.push_str(&generated.code);
                    output.push('\n');
                }
            }

            // Generate enums
            for enum_def in registry.enums.values() {
                if enum_def.is_spec {
                    let generated = type_gen.generate_enum(enum_def);
                    output.push_str(&generated.code);
                    output.push('\n');
                }
            }
        }

        for spec_fn in spec_fns {
            // Find matching annotation
            let annotation = annotations
                .iter()
                .flat_map(|m| m.functions.values())
                .find(|a| a.name == spec_fn.name);

            if let Some(annotation) = annotation {
                // Annotate and validate
                let annotated = mode_analyzer.annotate(spec_fn, annotation)?;

                // Check if functionalizable
                if annotated.is_functionalizable {
                    // Translate
                    let exec_fn = translator.translate(&annotated)?;

                    // Print
                    let fn_output = printer.print_function(&exec_fn);
                    output.push_str(&fn_output);
                    output.push('\n');
                }
            }
        }

        output.push_str("} // verus!\n");

        Ok(output)
    }

    /// Transpile a spec function from source strings
    pub fn transpile_source(
        &self,
        spec_source: &str,
        annotation_source: &str,
    ) -> TranspileResult<String> {
        let parser = VerusParser::new(spec_source.to_string());
        let spec_fns = parser.parse_spec_functions()?;

        let ann_parser = AnnotationParser::new(annotation_source.to_string());
        let annotations = ann_parser.parse()?;

        let mut mode_analyzer = ModeAnalyzer::new();
        let translator = Translator::new(self.config.translator.clone());
        let mut printer = Printer::new(self.config.printer.clone());

        let mut output = String::new();

        // Add custom imports before verus! block
        for import in &self.config.custom_imports {
            output.push_str(import);
            output.push('\n');
        }
        if !self.config.custom_imports.is_empty() {
            output.push('\n');
        }

        output.push_str("verus! {\n\n");

        // Generate inline types if configured
        if self.config.generate_inline_types {
            let mut type_parser = types::TypeParser::new(spec_source);
            let type_defs = type_parser.parse_types()?;
            let registry = types::build_registry(type_defs);
            let naming_config = crate::config::NamingConfig {
                spec_prefix: self.config.translator.spec_prefix.clone(),
                exec_prefix: self.config.translator.exec_prefix.clone(),
                ..Default::default()
            };
            let type_gen = TypeGenerator::with_options(
                naming_config.clone(),
                self.config.type_remapping.clone(),
                self.config.translator.validity_predicate_name.clone(),
            );

            // Generate structs
            for struct_def in registry.structs.values() {
                if struct_def.is_spec {
                    let generated = type_gen.generate_struct(struct_def);
                    output.push_str(&generated.code);
                    output.push('\n');
                }
            }

            // Generate enums
            for enum_def in registry.enums.values() {
                if enum_def.is_spec {
                    let generated = type_gen.generate_enum(enum_def);
                    output.push_str(&generated.code);
                    output.push('\n');
                }
            }
        }

        for spec_fn in spec_fns {
            let annotation = annotations
                .iter()
                .flat_map(|m| m.functions.values())
                .find(|a| a.name == spec_fn.name);

            if let Some(annotation) = annotation {
                let annotated = mode_analyzer.annotate(spec_fn, annotation)?;
                if annotated.is_functionalizable {
                    let exec_fn = translator.translate(&annotated)?;
                    output.push_str(&printer.print_function(&exec_fn));
                    output.push('\n');
                }
            }
        }

        output.push_str("} // verus!\n");

        Ok(output)
    }
}

impl Default for Transpiler {
    fn default() -> Self {
        Self::new(TranspilerConfig::default())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_transpiler_creation() {
        let config = TranspilerConfig::default();
        let transpiler = Transpiler::new(config);
        assert!(transpiler.config.translator.spec_prefix == "L");
    }

    #[test]
    fn test_custom_imports_in_output() {
        let config = TranspilerConfig {
            custom_imports: vec![
                "use vstd::prelude::*;".to_string(),
                "use std::collections::HashMap;".to_string(),
            ],
            ..Default::default()
        };

        let transpiler = Transpiler::new(config);

        // Create minimal input to test output format
        let spec_source = r#"
            verus! {
                pub open spec fn TestPred(x: int, y: int) -> bool {
                    y == x + 1
                }
            }
        "#;
        let annotation_source = r#"
            module test {
                TestPred(+, -);
            }
        "#;

        let result = transpiler
            .transpile_source(spec_source, annotation_source)
            .unwrap();

        // Check that imports appear before verus! block
        assert!(result.contains("use vstd::prelude::*;"));
        assert!(result.contains("use std::collections::HashMap;"));

        // Verify order: imports should come before verus!
        let import_pos = result.find("use vstd::prelude::*;").unwrap();
        let verus_pos = result.find("verus!").unwrap();
        assert!(
            import_pos < verus_pos,
            "Custom imports should appear before verus! block"
        );
    }

    #[test]
    fn test_inline_type_generation() {
        let config = TranspilerConfig {
            generate_inline_types: true,
            ..Default::default()
        };

        let transpiler = Transpiler::new(config);

        // Spec source with struct and function
        let spec_source = r#"
            verus! {
                pub struct LState {
                    pub value: int,
                    pub active: bool,
                }

                pub open spec fn StateInit(s: LState) -> bool {
                    s.value == 0 && s.active
                }
            }
        "#;
        let annotation_source = r#"
            module test {
                StateInit(-);
            }
        "#;

        let result = transpiler
            .transpile_source(spec_source, annotation_source)
            .unwrap();

        // Check that generated types appear in output
        assert!(
            result.contains("pub struct CState"),
            "Should generate CState struct: {}",
            result
        );
        assert!(
            result.contains("impl CState"),
            "Should generate impl block for CState: {}",
            result
        );
        assert!(
            result.contains("fn well_formed"),
            "Should generate well_formed predicate: {}",
            result
        );
        assert!(
            result.contains("impl View for CState"),
            "Should generate View impl for CState: {}",
            result
        );

        // Check that functions are also generated
        assert!(
            result.contains("pub exec fn CStateInit"),
            "Should generate CStateInit function: {}",
            result
        );
    }

    #[test]
    fn test_inline_type_generation_disabled_by_default() {
        let config = TranspilerConfig::default();
        assert!(
            !config.generate_inline_types,
            "generate_inline_types should be false by default"
        );

        let transpiler = Transpiler::new(config);

        let spec_source = r#"
            verus! {
                pub struct LState {
                    pub value: int,
                }

                pub open spec fn StateInit(s: LState) -> bool {
                    s.value == 0
                }
            }
        "#;
        let annotation_source = r#"
            module test {
                StateInit(-);
            }
        "#;

        let result = transpiler
            .transpile_source(spec_source, annotation_source)
            .unwrap();

        // Should NOT generate types when disabled
        assert!(
            !result.contains("pub struct CState"),
            "Should NOT generate CState struct when inline types disabled: {}",
            result
        );
    }
}
