//! Verus Spec-to-Implementation Transpiler
//!
//! This crate provides tools to transform Verus `spec fn` predicates (TLA-style
//! Init/Next specifications) into verified `exec fn` implementations.
//!
//! # Overview
//!
//! The transpiler pipeline consists of:
//! 1. **Parser** - Parse Verus spec functions from Rust source files
//! 2. **Annotation** - Process mode annotations from `.automan` files
//! 3. **Mode Analysis** - Analyze input/output modes and track assignments
//! 4. **Validation** - Check saturation, harmony, and obligation constraints
//! 5. **Translation** - Generate exec functions with proof linkage
//! 6. **Printing** - Format output as valid Rust/Verus code
//!
//! # Example
//!
//! ```ignore
//! use verus_transpiler::{Transpiler, TranspilerConfig};
//!
//! let config = TranspilerConfig::default();
//! let transpiler = Transpiler::new(config);
//!
//! let result = transpiler.transpile_file(
//!     "src/protocol/RSL/acceptor.rs",
//!     "src/protocol/RSL/acceptor.automan",
//! )?;
//!
//! std::fs::write("src/implementation/RSL/acceptor_gen.rs", result)?;
//! ```

pub mod annotation;
pub mod ast;
pub mod build_integration;
pub mod checker;
pub mod codegen;
pub mod config;
pub mod error;
pub mod moder;
pub mod parser;
pub mod printer;
pub mod runtime;
pub mod templates;
pub mod tla;
pub mod translator;
pub mod types;

// Re-export commonly used types
pub use annotation::{AnnotationParser, FunctionAnnotation, ModuleAnnotations};
pub use ast::{Expr, Parameter, ParameterMode, SpecFunction, Type};
pub use checker::{validate_function, HarmonyChecker, ObligationChecker, SaturationChecker};
pub use codegen::{generate_all_types, GeneratedCode, TemplateCodeGenerator, TypeGenerator};
pub use config::{ModuleConfig, NamingConfig, OutputConfig, TranspilerConfig as FileConfig};
pub use error::{DiagnosticAccumulator, TranspileError, TranspileResult, TranspileWarning};
pub use moder::{AnnotatedFunction, AssignmentTracker, ModeAnalyzer, PredicateKind};
pub use parser::{parse_file, VerusParser};
pub use printer::{print_function, Printer, PrinterConfig};
pub use runtime::{DeepClone, ExecType, SpecType, Validated, ValidatedResult, View};
pub use templates::{match_expression, QuantifierTemplate, TemplateMatcher};
pub use translator::{ExecFunction, Translator, TranslatorConfig};
pub use types::{EnumDef, FieldDef, FunctionSig, StructDef, TypeParser, TypeRegistry};

use std::path::Path;

/// Main transpiler configuration
#[derive(Debug, Clone, Default)]
pub struct TranspilerConfig {
    /// Configuration for the translator
    pub translator: TranslatorConfig,
    /// Configuration for the printer
    pub printer: PrinterConfig,
    /// Custom imports to include in generated code (before verus! block)
    pub custom_imports: Vec<String>,
    /// Whether to generate type definitions inline from the spec file.
    /// When true, parses struct/enum definitions from the spec file and generates
    /// corresponding exec types with View trait implementations.
    /// This makes the output self-contained without depending on manual implementation code.
    pub generate_inline_types: bool,
    /// Type remapping table for custom type name mappings
    pub type_remapping: std::collections::HashMap<String, String>,
    /// Whether to generate wrapper methods in an impl block for &mut self pattern.
    pub generate_wrapper_methods: bool,
    /// Functions to skip during transpilation (require manual implementation).
    /// These are functions with patterns too complex for automatic transpilation.
    pub skip_functions: Vec<String>,
    /// The type name for the impl block when generating wrapper methods.
    pub wrapper_impl_type: Option<String>,
}

/// Main transpiler orchestrating the pipeline
pub struct Transpiler {
    config: TranspilerConfig,
}

impl Transpiler {
    /// Create a new transpiler with the given configuration
    pub fn new(config: TranspilerConfig) -> Self {
        Self { config }
    }

    /// Transpile a single spec file with its annotation file
    pub fn transpile_file(
        &self,
        spec_path: &Path,
        annotation_path: &Path,
    ) -> TranspileResult<String> {
        // Parse spec file
        let spec_fns = parse_file(spec_path)?;

        // Parse annotations
        let annotations = annotation::parse_annotation_file(annotation_path)?;

        // Process each function
        let mut mode_analyzer = ModeAnalyzer::new();
        let translator = Translator::new(self.config.translator.clone());
        let mut printer = Printer::new(self.config.printer.clone());

        let mut output = String::new();
        output.push_str("// Auto-generated by verus-transpiler\n");
        output.push_str("// DO NOT EDIT MANUALLY\n\n");

        // Add custom imports before verus! block
        for import in &self.config.custom_imports {
            output.push_str(import);
            output.push('\n');
        }
        if !self.config.custom_imports.is_empty() {
            output.push('\n');
        }

        output.push_str("verus! {\n\n");

        // Generate inline types if configured
        if self.config.generate_inline_types {
            let type_defs = types::parse_types_from_file(spec_path)?;
            let registry = types::build_registry(type_defs);
            let naming_config = crate::config::NamingConfig {
                spec_prefix: self.config.translator.spec_prefix.clone(),
                exec_prefix: self.config.translator.exec_prefix.clone(),
                ..Default::default()
            };
            let type_gen = TypeGenerator::with_options(
                naming_config.clone(),
                self.config.type_remapping.clone(),
                self.config.translator.validity_predicate_name.clone(),
            );

            // Generate structs
            for struct_def in registry.structs.values() {
                if struct_def.is_spec {
                    let generated = type_gen.generate_struct(struct_def);
                    output.push_str(&generated.code);
                    output.push('\n');
                }
            }

            // Generate enums
            for enum_def in registry.enums.values() {
                if enum_def.is_spec {
                    let generated = type_gen.generate_enum(enum_def);
                    output.push_str(&generated.code);
                    output.push('\n');
                }
            }
        }

        // Collect all translated functions
        let mut exec_functions = Vec::new();

        for spec_fn in spec_fns {
            // Check if this function should be skipped
            if self.config.skip_functions.contains(&spec_fn.name) {
                continue;
            }

            // Find matching annotation
            let annotation = annotations
                .iter()
                .flat_map(|m| m.functions.values())
                .find(|a| a.name == spec_fn.name);

            if let Some(annotation) = annotation {
                // Annotate and validate
                let annotated = mode_analyzer.annotate(spec_fn, annotation)?;

                // Check if functionalizable
                if annotated.is_functionalizable {
                    // Translate
                    let exec_fn = translator.translate(&annotated)?;

                    // Print
                    let fn_output = printer.print_function(&exec_fn);
                    output.push_str(&fn_output);
                    output.push('\n');

                    // Collect for wrapper generation
                    if self.config.generate_wrapper_methods {
                        exec_functions.push(exec_fn);
                    }
                }
            }
        }

        // Generate wrapper methods if configured
        if self.config.generate_wrapper_methods {
            if let Some(ref impl_type) = self.config.wrapper_impl_type {
                let wrappers = self.generate_wrappers(&exec_functions, impl_type);
                if !wrappers.is_empty() {
                    output.push_str(&wrappers);
                    output.push('\n');
                }
            }
        }

        output.push_str("} // verus!\n");

        Ok(output)
    }

    /// Transpile a spec function from source strings
    pub fn transpile_source(
        &self,
        spec_source: &str,
        annotation_source: &str,
    ) -> TranspileResult<String> {
        let parser = VerusParser::new(spec_source.to_string());
        let spec_fns = parser.parse_spec_functions()?;

        let ann_parser = AnnotationParser::new(annotation_source.to_string());
        let annotations = ann_parser.parse()?;

        let mut mode_analyzer = ModeAnalyzer::new();
        let translator = Translator::new(self.config.translator.clone());
        let mut printer = Printer::new(self.config.printer.clone());

        let mut output = String::new();

        // Add custom imports before verus! block
        for import in &self.config.custom_imports {
            output.push_str(import);
            output.push('\n');
        }
        if !self.config.custom_imports.is_empty() {
            output.push('\n');
        }

        output.push_str("verus! {\n\n");

        // Generate inline types if configured
        if self.config.generate_inline_types {
            let mut type_parser = types::TypeParser::new(spec_source);
            let type_defs = type_parser.parse_types()?;
            let registry = types::build_registry(type_defs);
            let naming_config = crate::config::NamingConfig {
                spec_prefix: self.config.translator.spec_prefix.clone(),
                exec_prefix: self.config.translator.exec_prefix.clone(),
                ..Default::default()
            };
            let type_gen = TypeGenerator::with_options(
                naming_config.clone(),
                self.config.type_remapping.clone(),
                self.config.translator.validity_predicate_name.clone(),
            );

            // Generate structs
            for struct_def in registry.structs.values() {
                if struct_def.is_spec {
                    let generated = type_gen.generate_struct(struct_def);
                    output.push_str(&generated.code);
                    output.push('\n');
                }
            }

            // Generate enums
            for enum_def in registry.enums.values() {
                if enum_def.is_spec {
                    let generated = type_gen.generate_enum(enum_def);
                    output.push_str(&generated.code);
                    output.push('\n');
                }
            }
        }

        // Collect all translated functions
        let mut exec_functions = Vec::new();

        for spec_fn in spec_fns {
            // Check if this function should be skipped
            if self.config.skip_functions.contains(&spec_fn.name) {
                continue;
            }

            let annotation = annotations
                .iter()
                .flat_map(|m| m.functions.values())
                .find(|a| a.name == spec_fn.name);

            if let Some(annotation) = annotation {
                let annotated = mode_analyzer.annotate(spec_fn, annotation)?;
                if annotated.is_functionalizable {
                    let exec_fn = translator.translate(&annotated)?;
                    output.push_str(&printer.print_function(&exec_fn));
                    output.push('\n');

                    // Collect for wrapper generation
                    if self.config.generate_wrapper_methods {
                        exec_functions.push(exec_fn);
                    }
                }
            }
        }

        // Generate wrapper methods if configured
        if self.config.generate_wrapper_methods {
            if let Some(ref impl_type) = self.config.wrapper_impl_type {
                let wrappers = self.generate_wrappers(&exec_functions, impl_type);
                if !wrappers.is_empty() {
                    output.push_str(&wrappers);
                    output.push('\n');
                }
            }
        }

        output.push_str("} // verus!\n");

        Ok(output)
    }

    /// Generate wrapper methods for functions that take the impl type as first parameter.
    /// The wrappers convert functional-style `fn foo(&Type, ...) -> Type`
    /// to `impl Type { fn foo(&mut self, ...) }` pattern.
    fn generate_wrappers(&self, exec_functions: &[ExecFunction], impl_type: &str) -> String {
        let mut wrappers = Vec::new();
        let validity_pred = &self.config.translator.validity_predicate_name;

        for func in exec_functions {
            // Check if this function is a wrapper candidate:
            // - First param is a reference to impl_type
            // - Return type contains impl_type
            if !self.is_wrapper_candidate(func, impl_type) {
                continue;
            }

            // Generate wrapper method
            if let Some(wrapper) = self.generate_single_wrapper(func, impl_type, validity_pred) {
                wrappers.push(wrapper);
            }
        }

        if wrappers.is_empty() {
            return String::new();
        }

        // Wrap in impl block
        let mut output = format!("impl {} {{\n", impl_type);
        for wrapper in wrappers {
            output.push_str(&wrapper);
            output.push('\n');
        }
        output.push_str("}\n");
        output
    }

    /// Check if a function is a candidate for wrapper generation.
    fn is_wrapper_candidate(&self, func: &ExecFunction, impl_type: &str) -> bool {
        // Must have at least one parameter
        if func.params.is_empty() {
            return false;
        }

        // First param must be a reference to impl_type
        let first_param = &func.params[0];
        if !first_param.is_reference {
            return false;
        }

        // Check if the type matches impl_type
        let type_str = first_param.ty.to_rust_string();
        if !type_str.contains(impl_type) {
            return false;
        }

        // Return type must contain impl_type
        let return_str = func.return_type.to_rust_string();
        return_str.contains(impl_type)
    }

    /// Generate a single wrapper method for a function.
    fn generate_single_wrapper(
        &self,
        func: &ExecFunction,
        impl_type: &str,
        validity_pred: &str,
    ) -> Option<String> {
        let mut output = String::new();
        let indent = "    ";

        // Generate method signature
        // Convert function name to method name (remove type prefix if present)
        let method_name = func.name.strip_prefix(impl_type).unwrap_or(&func.name);
        let method_name = method_name.strip_prefix('_').unwrap_or(method_name);

        // Generate parameter list (skip first param, which becomes &mut self)
        let other_params: Vec<String> = func
            .params
            .iter()
            .skip(1)
            .map(|p| {
                if p.is_reference {
                    format!("{}: &{}", p.name, p.ty.to_rust_string())
                } else {
                    format!("{}: {}", p.name, p.ty.to_rust_string())
                }
            })
            .collect();

        // Determine return type
        // If return is just impl_type, return nothing (mutates self)
        // If return is tuple (impl_type, Other), return Other
        let return_type = self.extract_non_self_return_type(&func.return_type, impl_type);

        // Generate signature
        output.push_str(&format!("{}pub fn {}(&mut self", indent, method_name));
        if !other_params.is_empty() {
            output.push_str(", ");
            output.push_str(&other_params.join(", "));
        }
        output.push(')');
        if let Some(ref ret) = return_type {
            output.push_str(&format!(" -> {}", ret));
        }
        output.push('\n');

        // Generate requires clause
        output.push_str(&format!("{}requires\n", indent));
        output.push_str(&format!(
            "{}{}old(self).{}(),\n",
            indent, indent, validity_pred
        ));

        // Generate ensures clause
        output.push_str(&format!("{}ensures\n", indent));
        output.push_str(&format!("{}{}self.{}(),\n", indent, indent, validity_pred));

        // Generate body
        output.push_str(&format!("{}{{\n", indent));

        // Generate call to original function
        let _self_param = &func.params[0].name;
        let other_args: Vec<&str> = func
            .params
            .iter()
            .skip(1)
            .map(|p| p.name.as_str())
            .collect();

        if return_type.is_some() {
            // Return is tuple, extract and update self
            output.push_str(&format!(
                "{}{}let (new_self, result) = {}(self",
                indent, indent, func.name
            ));
            for arg in &other_args {
                output.push_str(&format!(", {}", arg));
            }
            output.push_str(");\n");
            output.push_str(&format!("{}{}*self = new_self;\n", indent, indent));
            output.push_str(&format!("{}{}result\n", indent, indent));
        } else {
            // Return is just state, update self
            output.push_str(&format!("{}{}*self = {}(self", indent, indent, func.name));
            for arg in &other_args {
                output.push_str(&format!(", {}", arg));
            }
            output.push_str(");\n");
        }

        output.push_str(&format!("{}}}\n", indent));

        Some(output)
    }

    /// Extract the non-self part of the return type.
    /// If return is `TypeName`, returns None (just updating self).
    /// If return is `(TypeName, Other)`, returns Some("Other").
    fn extract_non_self_return_type(
        &self,
        return_type: &translator::ExecType,
        impl_type: &str,
    ) -> Option<String> {
        let type_str = return_type.to_rust_string();

        // If it's just the impl_type, no separate return
        if type_str == impl_type {
            return None;
        }

        // If it's a tuple containing impl_type
        if type_str.starts_with('(') && type_str.contains(impl_type) {
            // Parse tuple and extract non-impl_type components
            // For now, assume simple (ImplType, Other) pattern
            let inner = type_str.trim_start_matches('(').trim_end_matches(')');
            let parts: Vec<&str> = inner.split(',').map(|s: &str| s.trim()).collect();
            let other_parts: Vec<&str> = parts
                .into_iter()
                .filter(|p: &&str| !p.contains(impl_type))
                .collect();
            if !other_parts.is_empty() {
                if other_parts.len() == 1 {
                    return Some(other_parts[0].to_string());
                } else {
                    return Some(format!("({})", other_parts.join(", ")));
                }
            }
        }

        None
    }
}

impl Default for Transpiler {
    fn default() -> Self {
        Self::new(TranspilerConfig::default())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_transpiler_creation() {
        let config = TranspilerConfig::default();
        let transpiler = Transpiler::new(config);
        assert!(transpiler.config.translator.spec_prefix == "L");
    }

    #[test]
    fn test_custom_imports_in_output() {
        let config = TranspilerConfig {
            custom_imports: vec![
                "use vstd::prelude::*;".to_string(),
                "use std::collections::HashMap;".to_string(),
            ],
            ..Default::default()
        };

        let transpiler = Transpiler::new(config);

        // Create minimal input to test output format
        let spec_source = r#"
            verus! {
                pub open spec fn TestPred(x: int, y: int) -> bool {
                    y == x + 1
                }
            }
        "#;
        let annotation_source = r#"
            module test {
                TestPred(+, -);
            }
        "#;

        let result = transpiler
            .transpile_source(spec_source, annotation_source)
            .unwrap();

        // Check that imports appear before verus! block
        assert!(result.contains("use vstd::prelude::*;"));
        assert!(result.contains("use std::collections::HashMap;"));

        // Verify order: imports should come before verus!
        let import_pos = result.find("use vstd::prelude::*;").unwrap();
        let verus_pos = result.find("verus!").unwrap();
        assert!(
            import_pos < verus_pos,
            "Custom imports should appear before verus! block"
        );
    }

    #[test]
    fn test_inline_type_generation() {
        let config = TranspilerConfig {
            generate_inline_types: true,
            ..Default::default()
        };

        let transpiler = Transpiler::new(config);

        // Spec source with struct and function
        let spec_source = r#"
            verus! {
                pub struct LState {
                    pub value: int,
                    pub active: bool,
                }

                pub open spec fn StateInit(s: LState) -> bool {
                    s.value == 0 && s.active
                }
            }
        "#;
        let annotation_source = r#"
            module test {
                StateInit(-);
            }
        "#;

        let result = transpiler
            .transpile_source(spec_source, annotation_source)
            .unwrap();

        // Check that generated types appear in output
        assert!(
            result.contains("pub struct CState"),
            "Should generate CState struct: {}",
            result
        );
        assert!(
            result.contains("impl CState"),
            "Should generate impl block for CState: {}",
            result
        );
        assert!(
            result.contains("fn well_formed"),
            "Should generate well_formed predicate: {}",
            result
        );
        assert!(
            result.contains("impl View for CState"),
            "Should generate View impl for CState: {}",
            result
        );

        // Check that functions are also generated
        assert!(
            result.contains("pub exec fn CStateInit"),
            "Should generate CStateInit function: {}",
            result
        );
    }

    #[test]
    fn test_inline_type_generation_disabled_by_default() {
        let config = TranspilerConfig::default();
        assert!(
            !config.generate_inline_types,
            "generate_inline_types should be false by default"
        );

        let transpiler = Transpiler::new(config);

        let spec_source = r#"
            verus! {
                pub struct LState {
                    pub value: int,
                }

                pub open spec fn StateInit(s: LState) -> bool {
                    s.value == 0
                }
            }
        "#;
        let annotation_source = r#"
            module test {
                StateInit(-);
            }
        "#;

        let result = transpiler
            .transpile_source(spec_source, annotation_source)
            .unwrap();

        // Should NOT generate types when disabled
        assert!(
            !result.contains("pub struct CState"),
            "Should NOT generate CState struct when inline types disabled: {}",
            result
        );
    }

    #[test]
    fn test_wrapper_generation_config_defaults() {
        let config = TranspilerConfig::default();
        assert!(
            !config.generate_wrapper_methods,
            "generate_wrapper_methods should be false by default"
        );
        assert!(
            config.wrapper_impl_type.is_none(),
            "wrapper_impl_type should be None by default"
        );
    }

    #[test]
    fn test_wrapper_generation_simple() {
        let config = TranspilerConfig {
            generate_wrapper_methods: true,
            wrapper_impl_type: Some("CState".to_string()),
            ..Default::default()
        };

        let transpiler = Transpiler::new(config);

        // Create spec with function that takes state and returns new state
        let spec_source = r#"
            verus! {
                pub struct LState {
                    pub value: int,
                }

                pub open spec fn StateUpdate(s: LState, s_: LState, delta: int) -> bool {
                    s_.value == s.value + delta
                }
            }
        "#;
        let annotation_source = r#"
            module test {
                StateUpdate(+, -, +);
            }
        "#;

        let result = transpiler
            .transpile_source(spec_source, annotation_source)
            .unwrap();

        // Check that wrapper impl block is generated
        assert!(
            result.contains("impl CState {"),
            "Should generate impl CState block: {}",
            result
        );

        // Check that wrapper method is generated
        assert!(
            result.contains("pub fn Update(&mut self"),
            "Should generate Update wrapper method: {}",
            result
        );

        // Check that wrapper has requires/ensures
        assert!(
            result.contains("old(self).well_formed()"),
            "Should have old(self) in requires: {}",
            result
        );
        assert!(
            result.contains("self.well_formed()"),
            "Should have self.well_formed() in ensures: {}",
            result
        );

        // Check that wrapper calls original function
        assert!(
            result.contains("*self = CStateUpdate(self"),
            "Should call CStateUpdate and assign to *self: {}",
            result
        );
    }

    #[test]
    fn test_wrapper_generation_disabled() {
        let config = TranspilerConfig {
            generate_wrapper_methods: false,
            wrapper_impl_type: Some("CState".to_string()),
            ..Default::default()
        };

        let transpiler = Transpiler::new(config);

        let spec_source = r#"
            verus! {
                pub struct LState {
                    pub value: int,
                }

                pub open spec fn StateUpdate(s: LState, s_: LState, delta: int) -> bool {
                    s_.value == s.value + delta
                }
            }
        "#;
        let annotation_source = r#"
            module test {
                StateUpdate(+, -, +);
            }
        "#;

        let result = transpiler
            .transpile_source(spec_source, annotation_source)
            .unwrap();

        // Should NOT generate wrapper when disabled
        assert!(
            !result.contains("impl CState {"),
            "Should NOT generate impl CState block when disabled: {}",
            result
        );
    }
}
