//! Verus Spec-to-Implementation Transpiler
//!
//! This crate provides tools to transform Verus `spec fn` predicates (TLA-style
//! Init/Next specifications) into verified `exec fn` implementations.
//!
//! # Overview
//!
//! The transpiler pipeline consists of:
//! 1. **Parser** - Parse Verus spec functions from Rust source files
//! 2. **Annotation** - Process mode annotations from `.automan` files
//! 3. **Mode Analysis** - Analyze input/output modes and track assignments
//! 4. **Validation** - Check saturation, harmony, and obligation constraints
//! 5. **Translation** - Generate exec functions with proof linkage
//! 6. **Printing** - Format output as valid Rust/Verus code
//!
//! # Example
//!
//! ```ignore
//! use verus_transpiler::{Transpiler, TranspilerConfig};
//!
//! let config = TranspilerConfig::default();
//! let transpiler = Transpiler::new(config);
//!
//! let result = transpiler.transpile_file(
//!     "src/protocol/RSL/acceptor.rs",
//!     "src/protocol/RSL/acceptor.automan",
//! )?;
//!
//! std::fs::write("src/implementation/RSL/acceptor_gen.rs", result)?;
//! ```

pub mod annotation;
pub mod ast;
pub mod checker;
pub mod config;
pub mod error;
pub mod moder;
pub mod parser;
pub mod printer;
pub mod translator;
pub mod types;

// Re-export commonly used types
pub use annotation::{AnnotationParser, FunctionAnnotation, ModuleAnnotations};
pub use ast::{Expr, Parameter, ParameterMode, SpecFunction, Type};
pub use config::{TranspilerConfig as FileConfig, NamingConfig, OutputConfig, ModuleConfig};
pub use checker::{validate_function, HarmonyChecker, ObligationChecker, SaturationChecker};
pub use error::{DiagnosticAccumulator, TranspileError, TranspileResult, TranspileWarning};
pub use moder::{AnnotatedFunction, AssignmentTracker, ModeAnalyzer, PredicateKind};
pub use parser::{parse_file, VerusParser};
pub use printer::{print_function, Printer, PrinterConfig};
pub use translator::{ExecFunction, Translator, TranslatorConfig};
pub use types::{TypeRegistry, StructDef, EnumDef, FieldDef, FunctionSig, TypeParser};

use std::path::Path;

/// Main transpiler configuration
#[derive(Debug, Clone, Default)]
pub struct TranspilerConfig {
    /// Configuration for the translator
    pub translator: TranslatorConfig,
    /// Configuration for the printer
    pub printer: PrinterConfig,
}

/// Main transpiler orchestrating the pipeline
pub struct Transpiler {
    config: TranspilerConfig,
}

impl Transpiler {
    /// Create a new transpiler with the given configuration
    pub fn new(config: TranspilerConfig) -> Self {
        Self { config }
    }

    /// Transpile a single spec file with its annotation file
    pub fn transpile_file(
        &self,
        spec_path: &Path,
        annotation_path: &Path,
    ) -> TranspileResult<String> {
        // Parse spec file
        let spec_fns = parse_file(spec_path)?;

        // Parse annotations
        let annotations = annotation::parse_annotation_file(annotation_path)?;

        // Process each function
        let mut mode_analyzer = ModeAnalyzer::new();
        let translator = Translator::new(self.config.translator.clone());
        let mut printer = Printer::new(self.config.printer.clone());

        let mut output = String::new();
        output.push_str("// Auto-generated by verus-transpiler\n");
        output.push_str("// DO NOT EDIT MANUALLY\n\n");
        output.push_str("verus! {\n\n");

        for spec_fn in spec_fns {
            // Find matching annotation
            let annotation = annotations
                .iter()
                .flat_map(|m| m.functions.values())
                .find(|a| a.name == spec_fn.name);

            if let Some(annotation) = annotation {
                // Annotate and validate
                let annotated = mode_analyzer.annotate(spec_fn, annotation)?;

                // Check if functionalizable
                if annotated.is_functionalizable {
                    // Translate
                    let exec_fn = translator.translate(&annotated)?;

                    // Print
                    let fn_output = printer.print_function(&exec_fn);
                    output.push_str(&fn_output);
                    output.push('\n');
                }
            }
        }

        output.push_str("} // verus!\n");

        Ok(output)
    }

    /// Transpile a spec function from source strings
    pub fn transpile_source(
        &self,
        spec_source: &str,
        annotation_source: &str,
    ) -> TranspileResult<String> {
        let parser = VerusParser::new(spec_source.to_string());
        let spec_fns = parser.parse_spec_functions()?;

        let ann_parser = AnnotationParser::new(annotation_source.to_string());
        let annotations = ann_parser.parse()?;

        let mut mode_analyzer = ModeAnalyzer::new();
        let translator = Translator::new(self.config.translator.clone());
        let mut printer = Printer::new(self.config.printer.clone());

        let mut output = String::new();

        for spec_fn in spec_fns {
            let annotation = annotations
                .iter()
                .flat_map(|m| m.functions.values())
                .find(|a| a.name == spec_fn.name);

            if let Some(annotation) = annotation {
                let annotated = mode_analyzer.annotate(spec_fn, annotation)?;
                if annotated.is_functionalizable {
                    let exec_fn = translator.translate(&annotated)?;
                    output.push_str(&printer.print_function(&exec_fn));
                    output.push('\n');
                }
            }
        }

        Ok(output)
    }
}

impl Default for Transpiler {
    fn default() -> Self {
        Self::new(TranspilerConfig::default())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_transpiler_creation() {
        let config = TranspilerConfig::default();
        let transpiler = Transpiler::new(config);
        assert!(transpiler.config.translator.spec_prefix == "L");
    }
}
