---- MODULE MoreUpToDate ----
EXTENDS etcd_raftDefs
VARIABLE pc
Step(n, A) == pc = n /\ pc' = n+1 /\ A
Recv(src,dst,ty) == \E m \in DOMAIN messages :
    /\ m.msource = src /\ m.mdest = dst /\ m.mtype = ty /\ Receive(m)
ReplyRecv(src,dst,ty) == \E m \in DOMAIN messages :
    /\ m.msource = src /\ m.mdest = dst /\ m.mtype = ty /\ Receive(m)
    /\ pendingMessages' # pendingMessages
SInit == Init /\ pc = 0
SNext ==
  \/ Step(0, Timeout(1))
  \/ Step(1, RequestVote(1,1))
  \/ Step(2, RequestVote(1,4))
  \/ Step(3, RequestVote(1,5))
  \/ Step(4, Ready(1))
  \/ Step(5, Recv(1,1,RequestVoteResponse))
  \/ Step(6, Recv(1,4,RequestVoteRequest))
  \/ Step(7, Recv(1,4,RequestVoteRequest))
  \/ Step(8, Ready(4))
  \/ Step(9, Recv(4,1,RequestVoteResponse))
  \/ Step(10, Recv(1,5,RequestVoteRequest))
  \/ Step(11, Recv(1,5,RequestVoteRequest))
  \/ Step(12, Ready(5))
  \/ Step(13, Recv(5,1,RequestVoteResponse))
  \/ Step(14, BecomeLeader(1))
  \/ Step(15, ClientRequest(1,0))
  \/ Step(16, Ready(1))
  \/ Step(17, Timeout(2))
  \/ Step(18, Timeout(2))
  \/ Step(19, RequestVote(2,2))
  \/ Step(20, RequestVote(2,3))
  \/ Step(21, RequestVote(2,4))
  \/ Step(22, Ready(2))
  \/ Step(23, Recv(2,2,RequestVoteResponse))
  \/ Step(24, Recv(2,3,RequestVoteRequest))
  \/ Step(25, Recv(2,3,RequestVoteRequest))
  \/ Step(26, Ready(3))
  \/ Step(27, Recv(3,2,RequestVoteResponse))
  \/ Step(28, Recv(2,4,RequestVoteRequest))
  \/ Step(29, Recv(2,4,RequestVoteRequest))
  \/ Step(30, Ready(4))
  \/ Step(31, Recv(4,2,RequestVoteResponse))
  \/ Step(32, BecomeLeader(2))
  \/ Step(33, ClientRequest(2,0))
  \/ Step(34, Ready(2))
  \/ Step(35, StepDownToFollower(1))
  \/ Step(36, Timeout(1))
  \/ Step(37, Timeout(1))
  \/ Step(38, RequestVote(1,1))
  \/ Step(39, RequestVote(1,4))
  \/ Step(40, RequestVote(1,5))
  \/ Step(41, Ready(1))
  \/ Step(42, Recv(1,1,RequestVoteResponse))
  \/ Step(43, Recv(1,4,RequestVoteRequest))
  \/ Step(44, Recv(1,4,RequestVoteRequest))
  \/ Step(45, Ready(4))
  \/ Step(46, Recv(4,1,RequestVoteResponse))
  \/ Step(47, Recv(1,5,RequestVoteRequest))
  \/ Step(48, Recv(1,5,RequestVoteRequest))
  \/ Step(49, Ready(5))
  \/ Step(50, Recv(5,1,RequestVoteResponse))
  \/ Step(51, BecomeLeader(1))
  \/ Step(52, ClientRequest(1,0))
  \/ Step(53, AppendEntriesToSelf(1))
  \/ Step(54, AppendEntries(1,4,<<1,3>>))
  \/ Step(55, AppendEntries(1,5,<<1,3>>))
  \/ Step(56, Ready(1))
  \/ Step(57, Recv(1,1,AppendEntriesResponse))
  \/ Step(58, Recv(1,4,AppendEntriesRequest))
  \/ Step(59, ReplyRecv(1,4,AppendEntriesRequest))
  \/ Step(60, Ready(4))
  \/ Step(61, Recv(4,1,AppendEntriesResponse))
  \/ Step(62, Recv(1,5,AppendEntriesRequest))
  \/ Step(63, ReplyRecv(1,5,AppendEntriesRequest))
  \/ Step(64, Ready(5))
  \/ Step(65, Recv(5,1,AppendEntriesResponse))
  \/ Step(66, AdvanceCommitIndex(1))
  \/ Step(67, SendSnapshot(1,3,1))
  \/ Step(68, Ready(1))
  \/ Step(69, Recv(1,3,AppendEntriesRequest))
  \/ Step(70, Recv(1,3,AppendEntriesRequest))
  \/ Step(71, ReplyRecv(1,3,AppendEntriesRequest))
  \/ (pc = 72 /\ UNCHANGED <<pc,vars>>)
SSpec == SInit /\ [][SNext]_<<pc,vars>> /\ WF_<<pc,vars>>(SNext)
Reached == <>(pc = 72)
FinalWitness == pc = 72 =>
    /\ currentTerm[1] = 3 /\ state[1] = Leader /\ commitIndex[1] = 2
    /\ log[1][1].term = 1 /\ log[1][2].term = 3
    /\ currentTerm[2] = 2 /\ state[2] = Leader /\ log[2][1].term = 2
    /\ currentTerm[3] = 3 /\ log[3][1].term = 1 /\ Len(log[3]) = 1 /\ commitIndex[3] = 1
    /\ ~MoreUpToDateCorrectInv
====
