---- MODULE BadIndex ----
EXTENDS ZkV3_7_0Defs
CONSTANT A, B, C
VARIABLE pc, edge
SimulationValue == {0}
TaggedFLEReceiveNotmsg(i,j) == /\ FLEReceiveNotmsg(i,j) /\ edge' = <<"Receive",i,j>>
TaggedFLENotmsgTimeout(i) == /\ FLENotmsgTimeout(i) /\ edge' = <<"Timeout",i,i>>
TaggedFLEHandleNotmsg(i) == /\ FLEHandleNotmsg(i) /\ edge' = <<"Handle",i,i>>
TaggedFLEWaitNewNotmsg(i) == /\ FLEWaitNewNotmsg(i) /\ edge' = <<"Wait",i,i>>
TaggedConnectAndFollowerSendFOLLOWERINFO(i,j) == /\ ConnectAndFollowerSendFOLLOWERINFO(i,j) /\ edge' = <<"Connect",i,j>>
TaggedLeaderProcessFOLLOWERINFO(i,j) == /\ LeaderProcessFOLLOWERINFO(i,j) /\ edge' = <<"FollowerInfo",i,j>>
TaggedFollowerProcessLEADERINFO(i,j) == /\ FollowerProcessLEADERINFO(i,j) /\ edge' = <<"LeaderInfo",i,j>>
TaggedLeaderProcessACKEPOCH(i,j) == /\ LeaderProcessACKEPOCH(i,j) /\ edge' = <<"AckEpoch",i,j>>
TaggedLeaderSyncFollower(i,j) == /\ LeaderSyncFollower(i,j) /\ edge' = <<"Sync",i,j>>
TaggedFollowerProcessSyncMessage(i,j) == /\ FollowerProcessSyncMessage(i,j) /\ edge' = <<"SyncMessage",i,j>>
TaggedFollowerProcessPROPOSALInSync(i,j) == /\ FollowerProcessPROPOSALInSync(i,j) /\ edge' = <<"ProposalSync",i,j>>
TaggedFollowerProcessCOMMITInSync(i,j) == /\ FollowerProcessCOMMITInSync(i,j) /\ edge' = <<"CommitSync",i,j>>
TaggedFollowerProcessNEWLEADER(i,j) == /\ FollowerProcessNEWLEADER(i,j) /\ edge' = <<"NewLeader",i,j>>
TaggedLeaderProcessACKLD(i,j) == /\ LeaderProcessACKLD(i,j) /\ edge' = <<"AckLd",i,j>>
TaggedFollowerProcessUPTODATE(i,j) == /\ FollowerProcessUPTODATE(i,j) /\ edge' = <<"UpToDate",i,j>>
TaggedLeaderProcessRequest(i) == /\ LeaderProcessRequest(i) /\ edge' = <<"Request",i,i>>
TaggedFollowerProcessPROPOSAL(i,j) == /\ FollowerProcessPROPOSAL(i,j) /\ edge' = <<"Proposal",i,j>>
TaggedLeaderProcessACK(i,j) == /\ LeaderProcessACK(i,j) /\ edge' = <<"Ack",i,j>>
TaggedFollowerProcessCOMMIT(i,j) == /\ FollowerProcessCOMMIT(i,j) /\ edge' = <<"Commit",i,j>>
TaggedNodeCrash(i) == /\ NodeCrash(i) /\ edge' = <<"Crash",i,i>>
TaggedNodeStart(i) == /\ NodeStart(i) /\ edge' = <<"Start",i,i>>
HealthyNext ==  
        
            \/ \E i, j \in Server: TaggedFLEReceiveNotmsg(i, j)
            \/ \E i \in Server:    TaggedFLENotmsgTimeout(i)
            \/ \E i \in Server:    TaggedFLEHandleNotmsg(i)
            \/ \E i \in Server:    TaggedFLEWaitNewNotmsg(i)
        
        
            \/ \E i, j \in Server: TaggedConnectAndFollowerSendFOLLOWERINFO(i, j)
            \/ \E i, j \in Server: TaggedLeaderProcessFOLLOWERINFO(i, j)
            \/ \E i, j \in Server: TaggedFollowerProcessLEADERINFO(i, j)
            \/ \E i, j \in Server: TaggedLeaderProcessACKEPOCH(i, j)
            \/ \E i, j \in Server: TaggedLeaderSyncFollower(i, j)
            \/ \E i, j \in Server: TaggedFollowerProcessSyncMessage(i, j)
            \/ \E i, j \in Server: TaggedFollowerProcessPROPOSALInSync(i, j)
            \/ \E i, j \in Server: TaggedFollowerProcessCOMMITInSync(i, j)
            \/ \E i, j \in Server: TaggedFollowerProcessNEWLEADER(i, j)
            \/ \E i, j \in Server: TaggedLeaderProcessACKLD(i, j)
            \/ \E i, j \in Server: TaggedFollowerProcessUPTODATE(i, j)
        
            \/ \E i, j \in Server: TaggedFollowerProcessPROPOSAL(i, j)
            \/ \E i, j \in Server: TaggedLeaderProcessACK(i, j)
            \/ \E i, j \in Server: TaggedFollowerProcessCOMMIT(i, j)
DiscoveryNext ==  
        
            \/ \E i, j \in Server: TaggedFLEReceiveNotmsg(i, j)
            \/ \E i \in Server:    TaggedFLENotmsgTimeout(i)
            \/ \E i \in Server:    TaggedFLEHandleNotmsg(i)
            \/ \E i \in Server:    TaggedFLEWaitNewNotmsg(i)
        
        
            \/ \E i, j \in Server: TaggedConnectAndFollowerSendFOLLOWERINFO(i, j)
            \/ \E i, j \in Server: TaggedLeaderProcessFOLLOWERINFO(i, j)
            \/ \E i, j \in Server: TaggedFollowerProcessLEADERINFO(i, j)
            \/ \E i, j \in Server: TaggedLeaderProcessACKEPOCH(i, j)
        
FixedAction ==
    CASE pc = 0 -> TaggedFLENotmsgTimeout(A)
    [] pc = 1 -> TaggedFLEHandleNotmsg(A)
    [] pc = 2 -> TaggedFLEReceiveNotmsg(B,A)
    [] pc = 3 -> TaggedFLEHandleNotmsg(B)
    [] pc = 4 -> TaggedFLEReceiveNotmsg(A,B)
    [] pc = 5 -> TaggedFLEHandleNotmsg(A)
    [] pc = 6 -> TaggedFLEWaitNewNotmsg(A)
    [] pc = 7 -> TaggedFLEWaitNewNotmsg(B)
    [] pc = 8 -> TaggedFLEReceiveNotmsg(C,A)
    [] pc = 9 -> TaggedFLEHandleNotmsg(C)
    [] pc = 10 -> TaggedConnectAndFollowerSendFOLLOWERINFO(A,B)
    [] pc = 11 -> TaggedFLEWaitNewNotmsg(C)
    [] pc = 12 -> TaggedFLEReceiveNotmsg(B,C)
    [] pc = 13 -> TaggedConnectAndFollowerSendFOLLOWERINFO(A,C)
    [] pc = 14 -> TaggedLeaderProcessFOLLOWERINFO(A,C)
    [] pc = 15 -> TaggedFLEReceiveNotmsg(C,B)
    [] pc = 16 -> TaggedFLEReceiveNotmsg(B,C)
    [] pc = 17 -> TaggedFLEReceiveNotmsg(A,C)
    [] pc = 18 -> TaggedLeaderProcessFOLLOWERINFO(A,B)
    [] pc = 19 -> TaggedFLEReceiveNotmsg(C,B)
    [] pc = 20 -> TaggedFLEReceiveNotmsg(C,A)
    [] pc = 21 -> TaggedFollowerProcessLEADERINFO(C,A)
    [] pc = 22 -> TaggedFollowerProcessLEADERINFO(B,A)
    [] pc = 23 -> TaggedLeaderProcessACKEPOCH(A,B)
    [] pc = 24 -> TaggedLeaderSyncFollower(A,B)
    [] pc = 25 -> TaggedLeaderProcessACKEPOCH(A,C)
    [] pc = 26 -> TaggedLeaderSyncFollower(A,C)
    [] pc = 27 -> TaggedFollowerProcessSyncMessage(B,A)
    [] pc = 28 -> TaggedFollowerProcessSyncMessage(C,A)
    [] pc = 29 -> TaggedFollowerProcessNEWLEADER(C,A)
    [] pc = 30 -> TaggedFollowerProcessNEWLEADER(B,A)
    [] pc = 31 -> TaggedLeaderProcessACKLD(A,B)
    [] pc = 32 -> TaggedFollowerProcessUPTODATE(B,A)
    [] pc = 33 -> TaggedLeaderProcessACKLD(A,C)
    [] pc = 34 -> TaggedFollowerProcessUPTODATE(C,A)
    [] pc = 35 -> TaggedLeaderProcessRequest(A)
    [] pc = 36 -> TaggedLeaderProcessRequest(A)
    [] pc = 37 -> TaggedLeaderProcessRequest(A)
    [] pc = 38 -> TaggedNodeCrash(A)
    [] pc = 39 -> TaggedFLEHandleNotmsg(C)
    [] pc = 40 -> TaggedFLEHandleNotmsg(B)
    [] pc = 41 -> TaggedFLEReceiveNotmsg(C,B)
    [] pc = 42 -> TaggedFLEReceiveNotmsg(B,C)
    [] pc = 43 -> TaggedFLEHandleNotmsg(B)
    [] pc = 44 -> TaggedFLENotmsgTimeout(B)
    [] pc = 45 -> TaggedFLEHandleNotmsg(C)
    [] pc = 46 -> TaggedFLENotmsgTimeout(C)
    [] pc = 47 -> TaggedFLEHandleNotmsg(B)
    [] pc = 48 -> TaggedFLEReceiveNotmsg(C,B)
    [] pc = 49 -> TaggedFLEWaitNewNotmsg(C)
    [] pc = 50 -> TaggedFLEReceiveNotmsg(B,C)
    [] pc = 51 -> TaggedFLEWaitNewNotmsg(C)
    [] pc = 52 -> TaggedFLEHandleNotmsg(B)
    [] pc = 53 -> TaggedFLENotmsgTimeout(B)
    [] pc = 54 -> TaggedFLEWaitNewNotmsg(B)
    [] pc = 55 -> TaggedConnectAndFollowerSendFOLLOWERINFO(B,C)
    [] pc = 56 -> TaggedLeaderProcessFOLLOWERINFO(B,C)
    [] pc = 57 -> TaggedFollowerProcessLEADERINFO(C,B)
    [] pc = 58 -> TaggedLeaderProcessACKEPOCH(B,C)
    [] pc = 59 -> TaggedNodeCrash(B)
    [] pc = 60 -> TaggedNodeStart(A)
    [] pc = 61 -> TaggedFLEReceiveNotmsg(A,C)
    [] pc = 62 -> TaggedFLEHandleNotmsg(A)
    [] pc = 63 -> TaggedFLEReceiveNotmsg(A,B)
    [] pc = 64 -> TaggedFLEHandleNotmsg(C)
    [] pc = 65 -> TaggedFLENotmsgTimeout(C)
    [] pc = 66 -> TaggedFLEReceiveNotmsg(A,C)
    [] pc = 67 -> TaggedFLEHandleNotmsg(A)
    [] pc = 68 -> TaggedFLEReceiveNotmsg(A,B)
    [] pc = 69 -> TaggedFLEHandleNotmsg(C)
    [] pc = 70 -> TaggedFLEReceiveNotmsg(A,C)
    [] pc = 71 -> TaggedFLEHandleNotmsg(A)
    [] pc = 72 -> TaggedFLEHandleNotmsg(A)
    [] pc = 73 -> TaggedFLEHandleNotmsg(A)
    [] pc = 74 -> TaggedFLEReceiveNotmsg(C,A)
    [] pc = 75 -> TaggedFLEReceiveNotmsg(A,C)
    [] pc = 76 -> TaggedFLEHandleNotmsg(C)
    [] pc = 77 -> TaggedFLENotmsgTimeout(C)
    [] pc = 78 -> TaggedFLEHandleNotmsg(A)
    [] pc = 79 -> TaggedFLEWaitNewNotmsg(C)
    [] pc = 80 -> TaggedFLEReceiveNotmsg(A,C)
    [] pc = 81 -> TaggedFLEHandleNotmsg(A)
    [] pc = 82 -> TaggedFLENotmsgTimeout(A)
    [] pc = 83 -> TaggedFLEWaitNewNotmsg(A)
    [] pc = 84 -> TaggedConnectAndFollowerSendFOLLOWERINFO(A,C)
    [] pc = 85 -> TaggedLeaderProcessFOLLOWERINFO(A,C)
    [] pc = 86 -> TaggedFollowerProcessLEADERINFO(C,A)
    [] pc = 87 -> TaggedLeaderProcessACKEPOCH(A,C)
    [] pc = 88 -> TaggedLeaderSyncFollower(A,C)
    [] pc = 89 -> TaggedFollowerProcessSyncMessage(C,A)
    [] pc = 90 -> TaggedNodeCrash(A)
    [] pc = 91 -> TaggedNodeStart(B)
    [] pc = 92 -> TaggedFLEHandleNotmsg(C)
    [] pc = 93 -> TaggedFLEReceiveNotmsg(B,A)
    [] pc = 94 -> TaggedFLENotmsgTimeout(C)
    [] pc = 95 -> TaggedFLEHandleNotmsg(C)
    [] pc = 96 -> TaggedFLEReceiveNotmsg(B,C)
    [] pc = 97 -> TaggedFLEReceiveNotmsg(B,C)
    [] pc = 98 -> TaggedFLEHandleNotmsg(B)
    [] pc = 99 -> TaggedFLENotmsgTimeout(C)
    [] pc = 100 -> TaggedFLEHandleNotmsg(B)
    [] pc = 101 -> TaggedFLEReceiveNotmsg(B,C)
    [] pc = 102 -> TaggedFLEHandleNotmsg(B)
    [] pc = 103 -> TaggedFLEHandleNotmsg(B)
    [] pc = 104 -> TaggedFLEHandleNotmsg(C)
    [] pc = 105 -> TaggedFLEReceiveNotmsg(B,C)
    [] pc = 106 -> TaggedFLENotmsgTimeout(C)
    [] pc = 107 -> TaggedFLEHandleNotmsg(C)
    [] pc = 108 -> TaggedFLEReceiveNotmsg(B,C)
    [] pc = 109 -> TaggedFLENotmsgTimeout(C)
    [] pc = 110 -> TaggedFLEReceiveNotmsg(B,C)
    [] pc = 111 -> TaggedFLEReceiveNotmsg(B,C)
    [] pc = 112 -> TaggedFLEHandleNotmsg(C)
    [] pc = 113 -> TaggedFLEHandleNotmsg(B)
    [] pc = 114 -> TaggedFLEReceiveNotmsg(C,B)
    [] pc = 115 -> TaggedFLEReceiveNotmsg(B,C)
    [] pc = 116 -> TaggedFLEHandleNotmsg(C)
    [] pc = 117 -> TaggedFLEWaitNewNotmsg(C)
    [] pc = 118 -> TaggedFLEReceiveNotmsg(B,C)
    [] pc = 119 -> TaggedFLEHandleNotmsg(B)
    [] pc = 120 -> TaggedFLEHandleNotmsg(B)
    [] pc = 121 -> TaggedFLEHandleNotmsg(B)
    [] pc = 122 -> TaggedFLEHandleNotmsg(B)
    [] pc = 123 -> TaggedFLEHandleNotmsg(B)
    [] pc = 124 -> TaggedFLEWaitNewNotmsg(B)
    [] pc = 125 -> TaggedConnectAndFollowerSendFOLLOWERINFO(B,C)
    [] pc = 126 -> TaggedLeaderProcessFOLLOWERINFO(B,C)
    [] pc = 127 -> TaggedFollowerProcessLEADERINFO(C,B)
    [] pc = 128 -> TaggedLeaderProcessACKEPOCH(B,C)
    [] pc = 129 -> TaggedLeaderSyncFollower(B,C)
    [] pc = 130 -> TaggedFollowerProcessSyncMessage(C,B)
    [] pc = 131 -> TaggedFollowerProcessNEWLEADER(C,B)
    [] pc = 132 -> TaggedLeaderProcessACKLD(B,C)
    [] pc = 133 -> TaggedFollowerProcessUPTODATE(C,B)
    [] pc = 134 -> TaggedLeaderProcessRequest(B)
    [] pc = 135 -> TaggedFollowerProcessPROPOSAL(C,B)
    [] pc = 136 -> TaggedLeaderProcessACK(B,C)
    [] pc = 137 -> TaggedNodeStart(A)
    [] pc = 138 -> TaggedFLEReceiveNotmsg(A,B)
    [] pc = 139 -> TaggedFLEHandleNotmsg(A)
    [] pc = 140 -> TaggedFLEReceiveNotmsg(A,C)
    [] pc = 141 -> TaggedFLEHandleNotmsg(A)
    [] pc = 142 -> TaggedFLEReceiveNotmsg(A,C)
    [] pc = 143 -> TaggedFLEHandleNotmsg(A)
    [] pc = 144 -> TaggedFLEReceiveNotmsg(A,C)
    [] pc = 145 -> TaggedFLEHandleNotmsg(A)
    [] pc = 146 -> TaggedFLEReceiveNotmsg(A,C)
    [] pc = 147 -> TaggedFLEHandleNotmsg(A)
    [] pc = 148 -> TaggedFLEReceiveNotmsg(A,C)
    [] pc = 149 -> TaggedFLEReceiveNotmsg(A,C)
    [] pc = 150 -> TaggedFLEHandleNotmsg(A)
    [] pc = 151 -> TaggedFLEHandleNotmsg(A)
    [] pc = 152 -> TaggedFLENotmsgTimeout(A)
    [] pc = 153 -> TaggedFLEHandleNotmsg(A)
    [] pc = 154 -> TaggedFLEReceiveNotmsg(B,A)
    [] pc = 155 -> TaggedFLEReceiveNotmsg(C,A)
    [] pc = 156 -> TaggedFLEReceiveNotmsg(A,B)
    [] pc = 157 -> TaggedFLEReceiveNotmsg(A,C)
    [] pc = 158 -> TaggedFLEHandleNotmsg(A)
    [] pc = 159 -> TaggedConnectAndFollowerSendFOLLOWERINFO(B,A)
    [] pc = 160 -> TaggedLeaderProcessFOLLOWERINFO(B,A)
    [] pc = 161 -> TaggedFollowerProcessLEADERINFO(A,B)
    [] pc = 162 -> TaggedLeaderProcessACKEPOCH(B,A)
    [] pc = 163 -> TaggedLeaderSyncFollower(B,A)
    [] pc = 164 -> TaggedFollowerProcessSyncMessage(A,B)
    [] pc = 165 -> TaggedFollowerProcessNEWLEADER(A,B)
    [] pc = 166 -> TaggedLeaderProcessACKLD(B,A)
    [] pc = 167 -> TaggedFollowerProcessUPTODATE(A,B)
    [] pc = 168 -> TaggedFollowerProcessCOMMIT(C,B)
    [] pc = 169 -> TaggedNodeCrash(C)
    [] pc = 170 -> TaggedLeaderProcessRequest(B)
    [] pc = 171 -> TaggedFollowerProcessPROPOSAL(A,B)
    [] pc = 172 -> TaggedLeaderProcessACK(B,A)
    [] pc = 173 -> TaggedFollowerProcessCOMMIT(A,B)
    [] pc = 174 -> TaggedLeaderProcessRequest(B)
    [] pc = 175 -> TaggedNodeStart(C)
    [] pc = 176 -> TaggedFollowerProcessPROPOSAL(A,B)
    [] pc = 177 -> TaggedFLEReceiveNotmsg(B,C)
    [] pc = 178 -> TaggedFLEReceiveNotmsg(A,C)
    [] pc = 179 -> TaggedFLEReceiveNotmsg(C,A)
    [] pc = 180 -> TaggedFLEHandleNotmsg(C)
    [] pc = 181 -> TaggedFLEReceiveNotmsg(C,B)
    [] pc = 182 -> TaggedFLEHandleNotmsg(C)
    [] pc = 183 -> TaggedConnectAndFollowerSendFOLLOWERINFO(B,C)
    [] pc = 184 -> TaggedLeaderProcessFOLLOWERINFO(B,C)
    [] pc = 185 -> TaggedFollowerProcessLEADERINFO(C,B)
    [] pc = 186 -> TaggedLeaderProcessACKEPOCH(B,C)
    [] pc = 187 -> TaggedLeaderSyncFollower(B,C)
    [] pc = 188 -> TaggedFollowerProcessSyncMessage(C,B)
    [] pc = 189 -> TaggedNodeCrash(C)
    [] pc = 190 -> TaggedNodeStart(C)
    [] OTHER -> FALSE
GuidedInit == Init /\ pc = 0 /\ edge = <<"Stutter",A,A>>
GuidedNext == IF pc < 191 THEN /\ FixedAction /\ pc' = pc+1 ELSE /\ HealthyNext /\ UNCHANGED pc
GuidedSpec == GuidedInit /\ [][GuidedNext]_<<vars,pc,edge>>
FollowingBound == \A i \in Server: state[i] = FOLLOWING => lastCommitted[i].index <= Len(history[i])
====
