// Auto-generated by verus-transpiler
// DO NOT EDIT MANUALLY

use std::collections::HashSet;
use vstd::prelude::*;

verus! {

#[derive(Clone)]
pub struct CRecord {
    pub accepted_bal: i64,
    pub accepted_val: i64,
    pub acceptors: i64,
    pub accepts_rcvd: i64,
    pub decided_val: i64,
    pub highest_accepted_bal: i64,
    pub highest_accepted_val: i64,
    pub node_id: i64,
    pub phase: i64,
    pub promised_bal: i64,
    pub promises_rcvd: i64,
    pub proposed_val: i64,
    pub proposer_bal: i64,
    pub quorum_size: i64,
}

impl CRecord {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CRecord {
    type V = LRecord;

    open spec fn view(&self) -> LRecord {
        LRecord {
            accepted_bal: self.accepted_bal as int,
            accepted_val: self.accepted_val as int,
            acceptors: self.acceptors as int,
            accepts_rcvd: self.accepts_rcvd as int,
            decided_val: self.decided_val as int,
            highest_accepted_bal: self.highest_accepted_bal as int,
            highest_accepted_val: self.highest_accepted_val as int,
            node_id: self.node_id as int,
            phase: self.phase as int,
            promised_bal: self.promised_bal as int,
            promises_rcvd: self.promises_rcvd as int,
            proposed_val: self.proposed_val as int,
            proposer_bal: self.proposer_bal as int,
            quorum_size: self.quorum_size as int,
        }
    }
}

#[derive(Clone)]
pub struct CState {
}

impl CState {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CState {
    type V = LState;

    open spec fn view(&self) -> LState {
        LState {
        }
    }
}

pub exec fn CState() -> (result: CRecord)ensures
    result.well_formed(),
    result@ == LState(),
{
    assume(false);
    CRecord {
        accepted_bal: Carbitrary(),
        accepted_val: Carbitrary(),
        acceptors: 0i64,
        accepts_rcvd: Carbitrary(),
        decided_val: Carbitrary(),
        highest_accepted_bal: Carbitrary(),
        highest_accepted_val: Carbitrary(),
        node_id: 0i64,
        phase: Carbitrary(),
        promised_bal: Carbitrary(),
        promises_rcvd: Carbitrary(),
        proposed_val: Carbitrary(),
        proposer_bal: Carbitrary(),
        quorum_size: 0i64,
    }

}

pub exec fn CConstants() -> (result: CRecord)ensures
    result.well_formed(),
    result@ == LConstants(),
{
    assume(false);
    CRecord {
        accepted_bal: 0i64,
        accepted_val: 0i64,
        acceptors: Carbitrary(),
        accepts_rcvd: 0i64,
        decided_val: 0i64,
        highest_accepted_bal: 0i64,
        highest_accepted_val: 0i64,
        node_id: Carbitrary(),
        phase: 0i64,
        promised_bal: 0i64,
        promises_rcvd: 0i64,
        proposed_val: 0i64,
        proposer_bal: 0i64,
        quorum_size: Carbitrary(),
    }

}

pub exec fn CPhase() -> (result: HashSet<i64>)ensures
    result@ == LPhase(),
{
    assume(false);
    { let mut __hs = HashSet::new(); __hs.insert(5126177779); __hs.insert(9996969643); __hs.insert(2508597854); __hs.insert(8313578207); __hs }

}

} // verus!
