//! Generated from TLA+ module: SimpleLeader
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;

verus! {

/// State for SimpleLeader module
pub struct LState {
    pub isLeader: bool,
    pub term: int,
    pub voted: Set<int>,
    pub candidates: Set<int>,
}


/// Init operator
pub open spec fn LInit(s: LState) -> bool {
    ((((s.isLeader == false) && (s.term == 0)) && (s.voted == Set::<int>::empty())) && (s.candidates == Set::<int>::empty()))
}

/// StartElection operator
pub open spec fn LStartElection(s: LState, s_: LState) -> bool {
    (((((s.isLeader == false) && (s_.term == (s.term + 1))) && (s_.candidates == s.candidates.union(set![(s.term + 1)]))) && (s_.voted == s.voted)) && (s_.isLeader == s.isLeader))
}

/// CastVote operator
pub open spec fn LCastVote(s: LState, s_: LState, candidate: int) -> bool {
    (((((s.candidates.contains(candidate) && !s.voted.contains(candidate)) && (s_.voted == s.voted.union(set![candidate]))) && (s_.term == s.term)) && (s_.candidates == s.candidates)) && (s_.isLeader == s.isLeader))
}

/// WinElection operator
pub open spec fn LWinElection(s: LState, s_: LState) -> bool {
    (((((s.isLeader == false) && (s_.isLeader == true)) && (s_.term == s.term)) && (s_.voted == s.voted)) && (s_.candidates == s.candidates))
}

/// StepDown operator
pub open spec fn LStepDown(s: LState, s_: LState) -> bool {
    (((((s.isLeader == true) && (s_.isLeader == false)) && (s_.term == s.term)) && (s_.voted == Set::<int>::empty())) && (s_.candidates == Set::<int>::empty()))
}

/// Next operator
pub open spec fn LNext(s: LState, s_: LState) -> bool {
    ((LStartElection(s, s_) || LWinElection(s, s_)) || LStepDown(s, s_))
}

} // verus!

