//! Generated from TLA+ module: SimplePrimary
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;

verus! {

/// State for SimplePrimary module
pub struct LState {
    pub isPrimary: bool,
    pub logLen: int,
    pub backupLen: int,
    pub pendingVal: int,
    pub isAcked: bool,
    pub viewNum: int,
}


/// Init operator
pub open spec fn LInit(s: LState) -> bool {
    ((((((s.isPrimary == true) && (s.logLen == 0)) && (s.backupLen == 0)) && (s.pendingVal == 0)) && (s.isAcked == true)) && (s.viewNum == 0))
}

/// Write operator
pub open spec fn LWrite(s: LState, s_: LState, val: int) -> bool {
    ((((((((s.isPrimary == true) && (s.isAcked == true)) && (s_.pendingVal == val)) && (s_.isAcked == false)) && (s_.isPrimary == s.isPrimary)) && (s_.logLen == s.logLen)) && (s_.backupLen == s.backupLen)) && (s_.viewNum == s.viewNum))
}

/// Replicate operator
pub open spec fn LReplicate(s: LState, s_: LState) -> bool {
    ((((((((s.isPrimary == true) && (s.isAcked == false)) && (s_.backupLen == (s.backupLen + 1))) && (s_.isPrimary == s.isPrimary)) && (s_.logLen == s.logLen)) && (s_.pendingVal == s.pendingVal)) && (s_.isAcked == s.isAcked)) && (s_.viewNum == s.viewNum))
}

/// Acknowledge operator
pub open spec fn LAcknowledge(s: LState, s_: LState) -> bool {
    (((((((((s.isPrimary == true) && (s.isAcked == false)) && (s.backupLen > s.logLen)) && (s_.isAcked == true)) && (s_.isPrimary == s.isPrimary)) && (s_.logLen == s.logLen)) && (s_.backupLen == s.backupLen)) && (s_.pendingVal == s.pendingVal)) && (s_.viewNum == s.viewNum))
}

/// Commit operator
pub open spec fn LCommit(s: LState, s_: LState) -> bool {
    (((((((((s.isPrimary == true) && (s.isAcked == true)) && (s.pendingVal > 0)) && (s_.logLen == (s.logLen + 1))) && (s_.pendingVal == 0)) && (s_.isPrimary == s.isPrimary)) && (s_.backupLen == s.backupLen)) && (s_.isAcked == s.isAcked)) && (s_.viewNum == s.viewNum))
}

/// Failover operator
pub open spec fn LFailover(s: LState, s_: LState) -> bool {
    (((((((s.isPrimary == true) && (s_.isPrimary == false)) && (s_.logLen == s.logLen)) && (s_.backupLen == s.backupLen)) && (s_.pendingVal == 0)) && (s_.isAcked == true)) && (s_.viewNum == (s.viewNum + 1)))
}

/// Next operator
pub open spec fn LNext(s: LState, s_: LState) -> bool {
    (((LReplicate(s, s_) || LAcknowledge(s, s_)) || LCommit(s, s_)) || LFailover(s, s_))
}

} // verus!

