---- MODULE ChainReplication_MC ----
\* Model-checking wrapper for the relational Chain Replication spec generated by verus2tla.
\* Adapts the (s, s_, c) relational style to standard TLA+ VARIABLE form.
\*
\* NOTE: Full multi-node chain replication model checking is infeasible with TLC
\* due to state space explosion from Seq-based history and multi-node chain state.
\* This wrapper checks single-node local invariants only.

EXTENDS Integers, Sequences, FiniteSets

\* Finite model constants for TLC
CONSTANTS Head_tag, Middle_tag, Tail_tag

\* Chain configuration
ChainLen == 3
NodeId == 0  \* Head node
MaxValues == 3
Values == 1..MaxValues

\* State variables
VARIABLE state, constants

\* Role tags
Head == [tag |-> Head_tag]
Middle == [tag |-> Middle_tag]
Tail == [tag |-> Tail_tag]

\* --- State machine ---

StateInit ==
    /\ constants = [node_id |-> NodeId, chain_len |-> ChainLen]
    /\ state = [role |-> Head, history |-> <<>>, pending_sent |-> {},
                committed_count |-> 0, obj_value |-> 0,
                has_predecessor |-> FALSE, predecessor |-> 0,
                has_successor |-> TRUE, successor |-> 1,
                alive |-> TRUE]

\* HeadReceiveWrite: head receives a new value
HeadReceiveWrite(value) ==
    /\ state.role = Head
    /\ state.alive = TRUE
    /\ ~(value \in state.pending_sent)
    /\ Len(state.history) < MaxValues
    /\ state' = [state EXCEPT
        !.history = Append(state.history, value),
        !.pending_sent = state.pending_sent \cup {value}]
    /\ UNCHANGED constants

\* ForwardToSuccessor: forward a pending value downstream
ForwardToSuccessor(value) ==
    /\ state.role = Head \/ state.role = Middle
    /\ state.alive = TRUE
    /\ value \in state.pending_sent
    /\ state.has_successor = TRUE
    /\ UNCHANGED <<state, constants>>  \* No local state change, just sends message

\* ReceiveAck: receive acknowledgment, remove from pending
ReceiveAck(value) ==
    /\ state.role = Head \/ state.role = Middle
    /\ state.alive = TRUE
    /\ value \in state.pending_sent
    /\ state' = [state EXCEPT
        !.pending_sent = state.pending_sent \ {value}]
    /\ UNCHANGED constants

\* NodeFail: node crashes
NodeFail ==
    /\ state.alive = TRUE
    /\ state' = [state EXCEPT !.alive = FALSE]
    /\ UNCHANGED constants

StateNext ==
    \/ \E v \in Values : HeadReceiveWrite(v)
    \/ \E v \in Values : ForwardToSuccessor(v)
    \/ \E v \in Values : ReceiveAck(v)
    \/ NodeFail

vars == <<state, constants>>
Spec == StateInit /\ [][StateNext]_vars

\* --- Safety Invariants ---

\* Role is a valid tag
RoleValid ==
    state.role \in {Head, Middle, Tail}

\* History only grows (length is monotonically non-decreasing)
HistoryBounded ==
    Len(state.history) <= MaxValues

\* Committed count is non-negative
CommittedNonNeg ==
    state.committed_count >= 0

\* Pending values are a subset of history
PendingInHistory ==
    \A v \in state.pending_sent :
        \E i \in 1..Len(state.history) : state.history[i] = v

\* Dead nodes don't change state (checked implicitly by action guards)
DeadNodeStable ==
    state.alive = FALSE => state.pending_sent = state.pending_sent

\* Chain topology consistent with node ID
TopologyConsistent ==
    /\ (constants.node_id = 0 => state.role = Head)
    /\ (constants.node_id = 0 => state.has_predecessor = FALSE)

====
