---- MODULE EPaxos_MC ----
\* Model-checking wrapper for the relational EPaxos spec generated by verus2tla.
\* Adapts the (s, s_, c) relational style to standard TLA+ VARIABLE form.
\*
\* NOTE: Full multi-node EPaxos model checking is infeasible with TLC due to
\* state space explosion from dependency graphs and fast/slow path branching.
\* This wrapper checks single-node local invariants only.

EXTENDS Integers, Sequences, FiniteSets

\* Finite model constants for TLC
CONSTANTS Empty_tag, PreAccepted_tag, Accepted_tag, Committed_tag, Executed_tag

\* EPaxos parameters
NumReplicas == 3
QuorumSize == 2
FastQuorumSize == 3
MyId == 0
Replicas == 0..(NumReplicas - 1)
MaxBallot == 2
MaxCmd == 2
MaxSeq == 3

\* State variables
VARIABLE state, constants

\* Phase tags
Empty == [tag |-> Empty_tag]
PreAccepted == [tag |-> PreAccepted_tag]
Accepted == [tag |-> Accepted_tag]
Committed == [tag |-> Committed_tag]
Executed == [tag |-> Executed_tag]

\* --- State machine ---

StateInit ==
    /\ constants = [num_replicas |-> NumReplicas, quorum_size |-> QuorumSize,
                     fast_quorum_size |-> FastQuorumSize, my_id |-> MyId]
    /\ state = [ballot |-> 0, phase |-> Empty, cmd |-> 0, seq |-> 0,
                dep_count |-> 0, is_leader |-> FALSE, committed_count |-> 0,
                executed_count |-> 0, preaccept_senders |-> {},
                accept_senders |-> {}, has_conflict |-> FALSE,
                max_resp_seq |-> 0]

\* Propose: leader initiates a new instance
Propose(value) ==
    /\ state.phase = Empty
    /\ value \in 1..MaxCmd
    /\ state' = [state EXCEPT
        !.phase = PreAccepted,
        !.cmd = value,
        !.seq = state.committed_count + 1,
        !.dep_count = 0,
        !.is_leader = TRUE,
        !.preaccept_senders = {constants.my_id},
        !.accept_senders = {},
        !.has_conflict = FALSE,
        !.max_resp_seq = 0]
    /\ UNCHANGED constants

\* ReceivePreAcceptOk: leader collects pre-accept responses
ReceivePreAcceptOk(pa_sender, pa_seq, pa_conflict) ==
    /\ state.phase = PreAccepted
    /\ state.is_leader = TRUE
    /\ pa_sender \in Replicas
    /\ ~(pa_sender \in state.preaccept_senders)
    /\ pa_seq \in 0..MaxSeq
    /\ state' = [state EXCEPT
        !.preaccept_senders = state.preaccept_senders \cup {pa_sender},
        !.has_conflict = IF pa_conflict THEN TRUE ELSE state.has_conflict,
        !.dep_count = IF pa_conflict THEN state.dep_count + 1 ELSE state.dep_count,
        !.max_resp_seq = IF pa_seq > state.max_resp_seq THEN pa_seq ELSE state.max_resp_seq,
        !.seq = IF pa_seq > state.seq THEN pa_seq ELSE state.seq]
    /\ UNCHANGED constants

\* FastCommit: commit on fast path (no conflicts, fast quorum)
FastCommit ==
    /\ state.phase = PreAccepted
    /\ state.is_leader = TRUE
    /\ Cardinality(state.preaccept_senders) >= constants.fast_quorum_size
    /\ state.has_conflict = FALSE
    /\ state' = [state EXCEPT
        !.phase = Committed,
        !.committed_count = state.committed_count + 1]
    /\ UNCHANGED constants

\* StartAccept: fall back to slow path (conflicts detected)
StartAccept ==
    /\ state.phase = PreAccepted
    /\ state.is_leader = TRUE
    /\ Cardinality(state.preaccept_senders) >= constants.quorum_size
    /\ state.has_conflict = TRUE
    /\ state' = [state EXCEPT
        !.phase = Accepted,
        !.accept_senders = {constants.my_id}]
    /\ UNCHANGED constants

\* ReceiveAcceptOk: leader collects accept responses
ReceiveAcceptOk(ao_sender) ==
    /\ state.phase = Accepted
    /\ state.is_leader = TRUE
    /\ ao_sender \in Replicas
    /\ ~(ao_sender \in state.accept_senders)
    /\ state' = [state EXCEPT
        !.accept_senders = state.accept_senders \cup {ao_sender}]
    /\ UNCHANGED constants

\* SlowCommit: commit on slow path
SlowCommit ==
    /\ state.phase = Accepted
    /\ state.is_leader = TRUE
    /\ Cardinality(state.accept_senders) >= constants.quorum_size
    /\ state' = [state EXCEPT
        !.phase = Committed,
        !.committed_count = state.committed_count + 1]
    /\ UNCHANGED constants

\* Execute: execute a committed instance
Execute ==
    /\ state.phase = Committed
    /\ state' = [state EXCEPT
        !.phase = Executed,
        !.executed_count = state.executed_count + 1]
    /\ UNCHANGED constants

\* Recover: take over a stalled instance with a new ballot
Recover(new_ballot) ==
    /\ state.phase \in {PreAccepted, Accepted}
    /\ new_ballot > state.ballot
    /\ new_ballot \in 1..MaxBallot
    /\ state' = [state EXCEPT
        !.ballot = new_ballot,
        !.phase = PreAccepted,
        !.dep_count = 0,
        !.is_leader = TRUE,
        !.preaccept_senders = {constants.my_id},
        !.accept_senders = {},
        !.has_conflict = FALSE,
        !.max_resp_seq = 0]
    /\ UNCHANGED constants

\* NewInstance: start fresh after execution
NewInstance ==
    /\ state.phase = Executed
    /\ state' = [state EXCEPT
        !.phase = Empty,
        !.cmd = 0,
        !.seq = 0,
        !.dep_count = 0,
        !.is_leader = FALSE,
        !.preaccept_senders = {},
        !.accept_senders = {},
        !.has_conflict = FALSE,
        !.max_resp_seq = 0]
    /\ UNCHANGED constants

StateNext ==
    \/ \E v \in 1..MaxCmd : Propose(v)
    \/ \E s \in Replicas, sq \in 0..MaxSeq, c \in BOOLEAN : ReceivePreAcceptOk(s, sq, c)
    \/ FastCommit
    \/ StartAccept
    \/ \E s \in Replicas : ReceiveAcceptOk(s)
    \/ SlowCommit
    \/ Execute
    \/ \E b \in 1..MaxBallot : Recover(b)
    \/ NewInstance

vars == <<state, constants>>
Spec == StateInit /\ [][StateNext]_vars

\* --- Safety Invariants ---

\* Phase is a valid tag
PhaseValid ==
    state.phase \in {Empty, PreAccepted, Accepted, Committed, Executed}

\* Ballot is non-negative
BallotNonNeg ==
    state.ballot >= 0

\* Executed count never exceeds committed count
ExecutedLeqCommitted ==
    state.executed_count <= state.committed_count

\* Sequence number is non-negative
SeqNonNeg ==
    state.seq >= 0

\* Fast commit requires no conflicts
\* (invariant: if committed via fast path, no conflicts were detected)
PreAcceptSendersValid ==
    state.preaccept_senders \subseteq Replicas

\* Accept senders are valid replicas
AcceptSendersValid ==
    state.accept_senders \subseteq Replicas

====
