---- MODULE TwoPhase_MC ----
\* Model-checking wrapper for the relational TwoPhase spec generated by verus2tla.
\* Adds message channel, VARIABLE state, finite domains, and safety invariants.
\*
\* The generated spec uses relational-style (s, s_, c) parameters with sent_packets
\* output. This wrapper adds explicit message tracking to enable TLC model checking.

EXTENDS Integers, Sequences, FiniteSets

\* Finite model constants for TLC
CONSTANTS Init_tag, Committed_tag, Aborted_tag

\* Resource managers (finite set for model checking)
RMs == {1, 2, 3}

\* State variables
VARIABLE state, constants, msgs

\* Construct the constants record
ConstantsRecord == [rm |-> RMs]

\* TMState tags
TMInit == [tag |-> Init_tag]
TMCommitted == [tag |-> Committed_tag]
TMAborted == [tag |-> Aborted_tag]

\* Message types (modeled as tagged records)
PrepareMsg == [type |-> "Prepare"]
CommitMsg == [type |-> "Commit"]
AbortMsg == [type |-> "Abort"]
PreparedMsg(rm) == [type |-> "Prepared", rm |-> rm]

\* --- Protocol actions (adapted from generated Twophase.tla with message tracking) ---

TMSendPrepare ==
    /\ state.tm_state = TMInit
    /\ state' = state  \* No state change
    /\ msgs' = msgs \cup {PrepareMsg}
    /\ UNCHANGED constants

RMReceivePrepare(rm) ==
    /\ rm \in ConstantsRecord.rm
    /\ PrepareMsg \in msgs
    /\ ~(rm \in state.rm_prepared)
    /\ ~(rm \in state.rm_aborted)
    /\ state' = [state EXCEPT !.rm_prepared = state.rm_prepared \cup {rm}]
    /\ msgs' = msgs \cup {PreparedMsg(rm)}
    /\ UNCHANGED constants

RMAbort(rm) ==
    /\ rm \in ConstantsRecord.rm
    /\ ~(rm \in state.rm_prepared)
    /\ ~(rm \in state.rm_aborted)
    /\ ~(rm \in state.rm_committed)
    /\ state' = [state EXCEPT !.rm_aborted = state.rm_aborted \cup {rm}]
    /\ UNCHANGED <<msgs, constants>>

TMRcvPrepared(r) ==
    /\ state.tm_state = TMInit
    /\ PreparedMsg(r) \in msgs
    /\ state' = [state EXCEPT !.tm_prepared = state.tm_prepared \cup {r}]
    /\ UNCHANGED <<msgs, constants>>

TMSendCommit ==
    /\ state.tm_state = TMInit
    /\ state.tm_prepared = ConstantsRecord.rm
    /\ state' = [state EXCEPT !.tm_state = TMCommitted]
    /\ msgs' = msgs \cup {CommitMsg}
    /\ UNCHANGED constants

TMSendAbort ==
    /\ state.tm_state = TMInit
    /\ state' = [state EXCEPT !.tm_state = TMAborted]
    /\ msgs' = msgs \cup {AbortMsg}
    /\ UNCHANGED constants

RMReceiveCommit(rm) ==
    /\ rm \in ConstantsRecord.rm
    /\ CommitMsg \in msgs
    /\ rm \in state.rm_prepared
    /\ ~(rm \in state.rm_committed)
    /\ state' = [state EXCEPT !.rm_committed = state.rm_committed \cup {rm}]
    /\ UNCHANGED <<msgs, constants>>

RMReceiveAbort(rm) ==
    /\ rm \in ConstantsRecord.rm
    /\ AbortMsg \in msgs
    /\ ~(rm \in state.rm_committed)
    /\ ~(rm \in state.rm_aborted)
    /\ state' = [state EXCEPT !.rm_aborted = state.rm_aborted \cup {rm}]
    /\ UNCHANGED <<msgs, constants>>

\* --- Standard TLA+ state machine ---

StateInit ==
    /\ constants = ConstantsRecord
    /\ state = [tm_state |-> TMInit,
                tm_prepared |-> {},
                rm_prepared |-> {},
                rm_committed |-> {},
                rm_aborted |-> {}]
    /\ msgs = {}

StateNext ==
    \/ TMSendPrepare
    \/ \E rm \in RMs : RMReceivePrepare(rm)
    \/ \E rm \in RMs : RMAbort(rm)
    \/ \E r \in RMs : TMRcvPrepared(r)
    \/ TMSendCommit
    \/ TMSendAbort
    \/ \E rm \in RMs : RMReceiveCommit(rm)
    \/ \E rm \in RMs : RMReceiveAbort(rm)

vars == <<state, constants, msgs>>

Spec == StateInit /\ [][StateNext]_vars

\* --- Safety Invariants ---

\* Consistency: No RM is both committed and aborted
Consistency ==
    \A rm \in RMs :
        ~(rm \in state.rm_committed /\ rm \in state.rm_aborted)

\* If TM committed, no RM is aborted
TMCommitImpliesNoAbort ==
    state.tm_state = TMCommitted =>
        state.rm_aborted = {}

\* If TM aborted, no RM is committed
TMAbortImpliesNoCommit ==
    state.tm_state = TMAborted =>
        state.rm_committed = {}

\* All committed RMs must have been prepared
CommittedImpliesPrepared ==
    \A rm \in RMs :
        rm \in state.rm_committed => rm \in state.rm_prepared

\* TM only commits if all RMs prepared
TMCommitRequiresAllPrepared ==
    state.tm_state = TMCommitted =>
        state.tm_prepared = RMs

====
