// Auto-generated by verus-transpiler
// DO NOT EDIT MANUALLY

use std::collections::HashSet;
use vstd::prelude::*;

verus! {

#[derive(Clone)]
pub struct CConstants {
    pub Configuration: i64,
    pub AbstractEndPoint: i64,
}

impl CConstants {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CConstants {
    type V = LConstants;

    open spec fn view(&self) -> LConstants {
        LConstants {
            Configuration: self.Configuration as int,
            AbstractEndPoint: self.AbstractEndPoint as int,
        }
    }
}

#[derive(Clone)]
pub struct CRecord {
    pub clientIds: i64,
    pub replica_ids: i64,
}

impl CRecord {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CRecord {
    type V = LRecord;

    open spec fn view(&self) -> LRecord {
        LRecord {
            clientIds: self.clientIds as int,
            replica_ids: self.replica_ids as int,
        }
    }
}

#[derive(Clone)]
pub struct CState {
}

impl CState {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CState {
    type V = LState;

    open spec fn view(&self) -> LState {
        LState {
        }
    }
}

pub exec fn CConfiguration(c: &CConstants) -> (result: CRecord)
requires
    c.well_formed(),
ensures
    result.well_formed(),
    result@ == LConfiguration(c@),
{
    assume(false);
    CRecord {
        clientIds: Carbitrary(),
        replica_ids: Carbitrary(),
    }

}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CMinQuorumSize(c: &CConstants) -> (result: i64)
{
    unimplemented!()
}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CReplicasDistinct(c: &CConstants, replica_ids: &Vec<i64>, i: &i64, j: &i64)
ensures
    LReplicasDistinct(c@, replica_ids@, *i as int, *j as int),
{
    unimplemented!()
}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CReplicasIsUnique(c: &CConstants, replica_ids: &Vec<i64>)
ensures
    LReplicasIsUnique(c@, replica_ids@),
{
    unimplemented!()
}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CWellFormedLConfiguration(c: &CConstants)
ensures
    LWellFormedLConfiguration(c@),
{
    unimplemented!()
}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CIsReplicaIndex(c: &CConstants, idx: &i64, id: &i64)
ensures
    LIsReplicaIndex(c@, *idx as int, *id as int),
{
    unimplemented!()
}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CGetReplicaIndex(c: &CConstants, id: &i64) -> (result: i64)
{
    unimplemented!()
}

} // verus!
