// Auto-generated by verus-transpiler
// DO NOT EDIT MANUALLY

use std::collections::HashSet;
use vstd::prelude::*;

verus! {

#[derive(Clone)]
pub struct CConstants {
    pub ReplicaConstants: i64,
}

impl CConstants {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CConstants {
    type V = LConstants;

    open spec fn view(&self) -> LConstants {
        LConstants {
            ReplicaConstants: self.ReplicaConstants as int,
        }
    }
}

#[derive(Clone)]
pub struct CRecord {
    pub all: i64,
    pub config: i64,
    pub my_index: i64,
    pub params: i64,
}

impl CRecord {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CRecord {
    type V = LRecord;

    open spec fn view(&self) -> LRecord {
        LRecord {
            all: self.all as int,
            config: self.config as int,
            my_index: self.my_index as int,
            params: self.params as int,
        }
    }
}

#[derive(Clone)]
pub struct CState {
}

impl CState {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CState {
    type V = LState;

    open spec fn view(&self) -> LState {
        LState {
        }
    }
}

pub exec fn CConstants(c: &CConstants) -> (result: CRecord)
requires
    c.well_formed(),
ensures
    result.well_formed(),
    result@ == LConstants(c@),
{
    assume(false);
    CRecord {
        all: 0i64,
        config: 6077433849i64,
        my_index: 0i64,
        params: 5876601465i64,
    }

}

pub exec fn CReplicaConstants(c: &CConstants) -> (result: CRecord)
requires
    c.well_formed(),
ensures
    result.well_formed(),
    result@ == LReplicaConstants(c@),
{
    assume(false);
    CRecord {
        all: Carbitrary(),
        config: 0i64,
        my_index: Carbitrary(),
        params: 0i64,
    }

}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CReplicaConstantsValid(c: &CConstants)
ensures
    LReplicaConstantsValid(c@),
{
    unimplemented!()
}

} // verus!
