// Auto-generated by verus-transpiler
// DO NOT EDIT MANUALLY

use std::collections::HashSet;
use vstd::prelude::*;

verus! {

pub struct CConstants {
    pub AbstractEndPoint: HashSet<i64>,
    pub RslState: i64,
    pub Constants: i64,
    pub RslIo: i64,
}

impl Clone for CConstants {
    #[verifier(external_body)]
    fn clone(&self) -> (res: Self)
    ensures
        res@ == self@,
        res.well_formed() == self.well_formed(),
        res.RslState == self.RslState,
        res.Constants == self.Constants,
        res.RslIo == self.RslIo,
    {
        CConstants {
            AbstractEndPoint: self.AbstractEndPoint.clone(),
            RslState: self.RslState,
            Constants: self.Constants,
            RslIo: self.RslIo,
        }
    }
}

impl CConstants {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CConstants {
    type V = LConstants;

    open spec fn view(&self) -> LConstants {
        LConstants {
            AbstractEndPoint: self.AbstractEndPoint@.map(|x: i64| x as int),
            RslState: self.RslState as int,
            Constants: self.Constants as int,
            RslIo: self.RslIo as int,
        }
    }
}

#[derive(Clone)]
pub struct CRecord {
    pub actor: i64,
    pub all: i64,
    pub clients: i64,
    pub constants: i64,
    pub environment: i64,
    pub ios: i64,
    pub my_index: i64,
    pub replicas: i64,
}

impl CRecord {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CRecord {
    type V = LRecord;

    open spec fn view(&self) -> LRecord {
        LRecord {
            actor: self.actor as int,
            all: self.all as int,
            clients: self.clients as int,
            constants: self.constants as int,
            environment: self.environment as int,
            ios: self.ios as int,
            my_index: self.my_index as int,
            replicas: self.replicas as int,
        }
    }
}

#[derive(Clone)]
pub struct CState {
}

impl CState {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CState {
    type V = LState;

    open spec fn view(&self) -> LState {
        LState {
        }
    }
}

/// Helper proof: mapping an injective function over an empty set yields an empty set.
proof fn lemma_empty_set_map()
ensures
    Set::<i64>::empty().map(|x: i64| x as int) =~= Set::<int>::empty(),
{
    let f = |x: i64| x as int;
    let s = Set::<i64>::empty().map(f);
    assert forall|y: int| !(#[trigger] s.contains(y)) by {
    }
}

/// Helper: clone a HashSet (Verus doesn't support HashSet::clone).
#[verifier(external_body)]
fn clone_hashset<K: std::hash::Hash + Eq + Clone>(s: &HashSet<K>) -> (res: HashSet<K>)
ensures
    res@ == s@,
{
    s.clone()
}


pub exec fn CRslState(c: &CConstants) -> (result: CRecord)
requires
    c.well_formed(),
ensures
    result.well_formed(),
    result@ == LRslState(c@),
{
    assume(false);
    CRecord {
        actor: 0i64,
        all: 0i64,
        clients: Carbitrary(),
        constants: Carbitrary::<int>(),
        environment: 7208647130i64,
        ios: 0i64,
        my_index: 0i64,
        replicas: Carbitrary(),
    }

}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CRslMapsComplete(c: &CConstants, ps: &i64)
ensures
    LRslMapsComplete(c@, *ps as int),
{
    unimplemented!()
}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CRslConstantsUnchanged(c: &CConstants, ps: &i64, ps_: &i64)
ensures
    LRslConstantsUnchanged(c@, *ps as int, *ps_ as int),
{
    unimplemented!()
}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CRslInit(c: &CConstants, con: &i64, ps: &i64)
ensures
    LRslInit(c@, *con as int, *ps as int),
{
    unimplemented!()
}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CRslNextCommon(c: &CConstants, ps: &i64, ps_: &i64)
ensures
    LRslNextCommon(c@, *ps as int, *ps_ as int),
{
    unimplemented!()
}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CRslNextOneReplica(c: &CConstants, ps: &i64, ps_: &i64, idx: &i64, ios: &i64)
ensures
    LRslNextOneReplica(c@, *ps as int, *ps_ as int, *idx as int, *ios as int),
{
    unimplemented!()
}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CRslNextEnvironment(c: &CConstants, ps: &i64, ps_: &i64)
ensures
    LRslNextEnvironment(c@, *ps as int, *ps_ as int),
{
    unimplemented!()
}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CRslNextOneExternal(c: &CConstants, ps: &i64, ps_: &i64, eid: &i64, ios: &i64)
ensures
    LRslNextOneExternal(c@, *ps as int, *ps_ as int, *eid as int, *ios as int),
{
    unimplemented!()
}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CRslNext(c: &CConstants, ps: &i64, ps_: &i64)
ensures
    LRslNext(c@, *ps as int, *ps_ as int),
{
    unimplemented!()
}

} // verus!
