// Auto-generated by verus-transpiler
// DO NOT EDIT MANUALLY

use std::collections::HashSet;
use vstd::prelude::*;

verus! {

pub struct CConstants {
    pub OperationNumber: i64,
    pub AbstractEndPoint: HashSet<i64>,
    pub RequestBatch: i64,
    pub ReplyCache: i64,
    pub ReplicaConstants: i64,
    pub Reply: i64,
    pub RslPacket: HashSet<i64>,
    pub Request: i64,
    pub Ballot: i64,
    pub Executor: i64,
}

impl Clone for CConstants {
    #[verifier(external_body)]
    fn clone(&self) -> (res: Self)
    ensures
        res@ == self@,
        res.well_formed() == self.well_formed(),
        res.OperationNumber == self.OperationNumber,
        res.RequestBatch == self.RequestBatch,
        res.ReplyCache == self.ReplyCache,
        res.ReplicaConstants == self.ReplicaConstants,
        res.Reply == self.Reply,
        res.Request == self.Request,
        res.Ballot == self.Ballot,
        res.Executor == self.Executor,
    {
        CConstants {
            OperationNumber: self.OperationNumber,
            AbstractEndPoint: self.AbstractEndPoint.clone(),
            RequestBatch: self.RequestBatch,
            ReplyCache: self.ReplyCache,
            ReplicaConstants: self.ReplicaConstants,
            Reply: self.Reply,
            RslPacket: self.RslPacket.clone(),
            Request: self.Request,
            Ballot: self.Ballot,
            Executor: self.Executor,
        }
    }
}

impl CConstants {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CConstants {
    type V = LConstants;

    open spec fn view(&self) -> LConstants {
        LConstants {
            OperationNumber: self.OperationNumber as int,
            AbstractEndPoint: self.AbstractEndPoint@.map(|x: i64| x as int),
            RequestBatch: self.RequestBatch as int,
            ReplyCache: self.ReplyCache as int,
            ReplicaConstants: self.ReplicaConstants as int,
            Reply: self.Reply as int,
            RslPacket: self.RslPacket@.map(|x: i64| x as int),
            Request: self.Request as int,
            Ballot: self.Ballot as int,
            Executor: self.Executor as int,
        }
    }
}

#[derive(Clone)]
pub struct CRecord {
    pub app: i64,
    pub app_state: i64,
    pub bal: i64,
    pub bal_state_req: i64,
    pub bal_state_supply: i64,
    pub constants: i64,
    pub dst: i64,
    pub max_bal_reflected: i64,
    pub msg: i64,
    pub next_op_to_execute: i64,
    pub opn_state_req: i64,
    pub opn_state_supply: i64,
    pub ops_complete: i64,
    pub proposer_id: i64,
    pub reply: i64,
    pub reply_cache: i64,
    pub seqno: i64,
    pub seqno_reply: i64,
    pub src: i64,
    pub v: i64,
}

impl CRecord {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CRecord {
    type V = LRecord;

    open spec fn view(&self) -> LRecord {
        LRecord {
            app: self.app as int,
            app_state: self.app_state as int,
            bal: self.bal as int,
            bal_state_req: self.bal_state_req as int,
            bal_state_supply: self.bal_state_supply as int,
            constants: self.constants as int,
            dst: self.dst as int,
            max_bal_reflected: self.max_bal_reflected as int,
            msg: self.msg as int,
            next_op_to_execute: self.next_op_to_execute as int,
            opn_state_req: self.opn_state_req as int,
            opn_state_supply: self.opn_state_supply as int,
            ops_complete: self.ops_complete as int,
            proposer_id: self.proposer_id as int,
            reply: self.reply as int,
            reply_cache: self.reply_cache as int,
            seqno: self.seqno as int,
            seqno_reply: self.seqno_reply as int,
            src: self.src as int,
            v: self.v as int,
        }
    }
}

/// Helper proof: mapping an injective function over an empty set yields an empty set.
proof fn lemma_empty_set_map()
ensures
    Set::<i64>::empty().map(|x: i64| x as int) =~= Set::<int>::empty(),
{
    let f = |x: i64| x as int;
    let s = Set::<i64>::empty().map(f);
    assert forall|y: int| !(#[trigger] s.contains(y)) by {
    }
}

/// Helper: clone a HashSet (Verus doesn't support HashSet::clone).
#[verifier(external_body)]
fn clone_hashset<K: std::hash::Hash + Eq + Clone>(s: &HashSet<K>) -> (res: HashSet<K>)
ensures
    res@ == s@,
{
    s.clone()
}


pub exec fn CExecutor(c: &CConstants) -> (result: CRecord)
requires
    c.well_formed(),
ensures
    result.well_formed(),
    result@ == LExecutor(c@),
{
    assume(false);
    CRecord {
        app: 2467764049i64,
        app_state: 0i64,
        bal: 0i64,
        bal_state_req: 0i64,
        bal_state_supply: 0i64,
        constants: Carbitrary::<int>(),
        dst: 0i64,
        max_bal_reflected: Carbitrary::<int>(),
        msg: 0i64,
        next_op_to_execute: Carbitrary::<int>(),
        opn_state_req: 0i64,
        opn_state_supply: 0i64,
        ops_complete: Carbitrary(),
        proposer_id: 0i64,
        reply: 0i64,
        reply_cache: Carbitrary::<int>(),
        seqno: 0i64,
        seqno_reply: 0i64,
        src: 0i64,
        v: 0i64,
    }

}

pub exec fn COutstandingOperation(c: &CConstants) -> (result: HashSet<i64>)
requires
    c.well_formed(),
ensures
    result@ == LOutstandingOperation(c@),
{
    assume(false);
    { let mut __hs = HashSet::new(); __hs.insert(6764822447); __hs.insert(4689272130); __hs }

}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CExecutorInit(c_consts: &CConstants, s: &i64, c: &i64)
ensures
    LExecutorInit(c_consts@, *s as int, *c as int),
{
    unimplemented!()
}

pub exec fn CExecutorGetDecision(s: &CState, c: &CConstants, bal: &i64, opn: &i64, v: &i64) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
ensures
    result.well_formed(),
    LExecutorGetDecision(s@, result@, c@, *bal as int, *opn as int, *v as int),
{
    assume(false);
    CRecord {
        app: Carbitrary(),
        app_state: 0i64,
        bal: 0i64,
        bal_state_req: 0i64,
        bal_state_supply: 0i64,
        constants: Carbitrary(),
        dst: 0i64,
        max_bal_reflected: Carbitrary(),
        msg: 0i64,
        next_op_to_execute: Carbitrary::<int>(),
        opn_state_req: 0i64,
        opn_state_supply: 0i64,
        ops_complete: Carbitrary(),
        proposer_id: 0i64,
        reply: 0i64,
        reply_cache: Carbitrary(),
        seqno: 0i64,
        seqno_reply: 0i64,
        src: 0i64,
        v: 0i64,
    }

}

// TRANSLATE-TODO: transpilation error: Code generation error: Function 'LGetPacketsFromReplies' is recursive but cannot be automatically translated: Recursive function 'LGetPacketsFromReplies' does not match any known pattern (filter, map, fold). Consider implementing manually.
#[verifier(external_body)]
pub exec fn CGetPacketsFromReplies(c: &CConstants, me: &i64, requests: &Vec<i64>, replies: &i64) -> (result: Vec<i64>)
{
    unimplemented!()
}

pub exec fn CClientsInReplies(c: &CConstants, replies: &Vec<i64>) -> (result: HashMap<i64, i64>)
requires
    c.well_formed(),
ensures
    result@ == LClientsInReplies(c@, replies@),
{
    assume(false);
    Carbitrary()

}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CRepliesAreReplyType(c: &CConstants, replies: &HashSet<i64>)
ensures
    LRepliesAreReplyType(c@, replies@),
{
    unimplemented!()
}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CUpdateNewCache(c_consts: &CConstants, c: &HashMap<i64, i64>, c_: &HashMap<i64, i64>, replies: &Vec<i64>)
ensures
    LUpdateNewCache(c_consts@, c@, c_@, replies@),
{
    unimplemented!()
}

pub exec fn CExecutorExecute(s: &CState, c: &CConstants, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
ensures
    result.well_formed(),
    LExecutorExecute(s@, result@, c@, sent_packets@),
{
    assume(false);
    { let batch = Carbitrary();     let temp = Carbitrary();
    { let new_state = Carbitrary::<Seq<int>>()[((Carbitrary::<Seq<Seq<int>>>()[1].len() as i64) - 1)];     let replies = Carbitrary::<Seq<Seq<int>>>()[2];
    { let clients = CClientsInReplies(c, Carbitrary::<Seq<int>>()); ((((Carbitrary::<int>() == Carbitrary::<int>()) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == (Carbitrary::<int>() + 1))) && (Carbitrary::<bool>() == if Carbitrary() {
        Carbitrary()
    } else {
        ((((Carbitrary() && (Carbitrary::<Seq<int>>() == vec![])) && CUpdateNewCache(c, Carbitrary::<Map<int, int>>(), Carbitrary::<Map<int, int>>(), Carbitrary::<Seq<int>>())) && (sent_packets == CGetPacketsFromReplies(c, &Carbitrary::<Seq<int>>()[Carbitrary()], Carbitrary::<Seq<int>>(), Carbitrary::<int>()))) && CRepliesAreReplyType(c, Carbitrary::<Set<int>>()))
    })) }
 }
 }

}

pub exec fn CExecutorProcessAppStateSupply(s: &CState, c: &CConstants, inp: &i64) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
ensures
    result.well_formed(),
    LExecutorProcessAppStateSupply(s@, result@, c@, *inp as int),
{
    assume(false);
    { let m = Carbitrary(); CRecord {
        app: Carbitrary(),
        app_state: 0i64,
        bal: 0i64,
        bal_state_req: 0i64,
        bal_state_supply: 0i64,
        constants: Carbitrary(),
        dst: 0i64,
        max_bal_reflected: Carbitrary(),
        msg: 0i64,
        next_op_to_execute: Carbitrary::<int>(),
        opn_state_req: 0i64,
        opn_state_supply: 0i64,
        ops_complete: Carbitrary(),
        proposer_id: 0i64,
        reply: 0i64,
        reply_cache: Carbitrary(),
        seqno: 0i64,
        seqno_reply: 0i64,
        src: 0i64,
        v: 0i64,
    } }

}

pub exec fn CExecutorProcessAppStateRequest(s: &CState, c: &CConstants, inp: &i64, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
ensures
    result.well_formed(),
    LExecutorProcessAppStateRequest(s@, result@, c@, *inp as int, sent_packets@),
{
    assume(false);
    { let m = Carbitrary(); if (((contains(&HashSet::new(), &Carbitrary::<int>()) && Carbitrary()) && (Carbitrary::<int>() >= Carbitrary::<int>())) && Carbitrary()) {
        s.clone()
    } else {
        s.clone()
    } }

}

pub exec fn CExecutorProcessStartingPhase2(s: &CState, c: &CConstants, inp: &i64, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
ensures
    result.well_formed(),
    LExecutorProcessStartingPhase2(s@, result@, c@, *inp as int, sent_packets@),
{
    assume(false);
    if (contains(&HashSet::new(), &Carbitrary::<int>()) && (Carbitrary::<int>() > Carbitrary::<int>())) {
        s.clone()
    } else {
        s.clone()
    }

}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CExecutorProcessRequest(c: &CConstants, s: &i64, inp: &i64, sent_packets: &Vec<i64>)
ensures
    LExecutorProcessRequest(c@, *s as int, *inp as int, sent_packets@),
{
    unimplemented!()
}

} // verus!
