// Auto-generated by verus-transpiler
// DO NOT EDIT MANUALLY

use std::collections::HashSet;
use vstd::prelude::*;

verus! {

#[derive(Clone)]
pub struct CConstants {
    pub Request: i64,
    pub AppState: i64,
    pub RequestBatch: i64,
}

impl CConstants {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CConstants {
    type V = LConstants;

    open spec fn view(&self) -> LConstants {
        LConstants {
            Request: self.Request as int,
            AppState: self.AppState as int,
            RequestBatch: self.RequestBatch as int,
        }
    }
}

#[derive(Clone)]
pub struct CRecord {
    pub client: i64,
    pub reply: i64,
    pub seqno: i64,
}

impl CRecord {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CRecord {
    type V = LRecord;

    open spec fn view(&self) -> LRecord {
        LRecord {
            client: self.client as int,
            reply: self.reply as int,
            seqno: self.seqno as int,
        }
    }
}

#[derive(Clone)]
pub struct CState {
}

impl CState {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CState {
    type V = LState;

    open spec fn view(&self) -> LState {
        LState {
        }
    }
}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CHandleRequest(c: &CConstants, state: &i64, request: &i64) -> (result: (i64, CRecord))
ensures
    result.well_formed(),
{
    unimplemented!()
}

pub exec fn CHandleRequestBatchHidden(c: &CConstants, state: &i64, batch: &i64) -> (result: ((i64), ()))
requires
    c.well_formed(),
ensures
    result.well_formed(),
    result@ == LHandleRequestBatchHidden(c@, *state as int, *batch as int),
{
    assume(false);
    Carbitrary()

}

// TRANSLATE-TODO: not functionalizable: No output parameters
#[verifier(external_body)]
pub exec fn CHandleRequestBatch(c: &CConstants, state: &i64, batch: &i64) -> (result: (i64, i64))
ensures
    result.well_formed(),
{
    unimplemented!()
}

} // verus!
