//! Generated from TLA+ module: Chain
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Chain module
pub struct LRecord {
    pub value: int,
}

/// State for Chain module
pub struct LState {
}

/// Constants for the module
pub struct LConstants {
    pub State: int,
    pub CRMessage: int,
    pub Constants: int,
}


/// Init operator
pub open spec fn LInit(c: LConstants, s: int) -> bool {
    (((((((((arbitrary::<Seq<int>>() == Seq::<int>::empty()) && (Set::<int>::empty() == Set::<int>::empty())) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && ((arbitrary::<int>() == 0) ==> (arbitrary::<int>() == 3419909347int))) && ((arbitrary::<int>() == (arbitrary::<int>() - 1)) ==> (arbitrary::<int>() == 8736718595int))) && (((arbitrary::<int>() > 0) && (arbitrary::<int>() < (arbitrary::<int>() - 1))) ==> (arbitrary::<int>() == 9863251288int))) && (arbitrary::<bool>() == (arbitrary::<int>() > 0))) && (arbitrary::<int>() == arbitrary::<int>()))
}

/// HeadReceiveWrite operator
pub open spec fn LHeadReceiveWrite(s: LState, s_: LState, c: LConstants, value: int, sent_packets: ()) -> bool {
    ((((((((((((((arbitrary::<int>() == 3419909347int) && (arbitrary::<bool>() == true)) && !Set::<int>::empty().contains(value)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<Seq<int>>() == arbitrary::<Seq<int>>().push(value))) && (Set::<int>::empty() == Set::<int>::empty().union(set![value]))) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == Seq::<int>::empty()))
}

/// ForwardToSuccessor operator
pub open spec fn LForwardToSuccessor(s: LState, s_: LState, c: LConstants, value: int, sent_packets: (LRecord)) -> bool {
    ((arbitrary::<int>() == 3419909347int) || (((((((((((((((arbitrary::<int>() == 9863251288int) && (arbitrary::<bool>() == true)) && Set::<int>::empty().contains(value)) && (arbitrary::<bool>() == true)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == arbitrary())))
}

/// ReceiveUpdate operator
pub open spec fn LReceiveUpdate(s: LState, s_: LState, c: LConstants, value: int, sent_packets: ()) -> bool {
    ((arbitrary::<int>() == 9863251288int) || ((((((arbitrary::<int>() == 8736718595int) && (arbitrary::<bool>() == true)) && !Set::<int>::empty().contains(value)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<Seq<int>>() == arbitrary::<Seq<int>>().push(value))) && if (arbitrary::<int>() == 9863251288int) { (Set::<int>::empty() == Set::<int>::empty().union(set![value])) } else { (((((((((arbitrary::<int>() == arbitrary::<int>()) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == Seq::<int>::empty())) }))
}

/// TailCommit operator
pub open spec fn LTailCommit(s: LState, s_: LState, c: LConstants, value: int, sent_packets: (LRecord)) -> bool {
    ((((((((((((((arbitrary::<int>() == 8736718595int) && (arbitrary::<bool>() == true)) && Set::<int>::empty().contains(value)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == (arbitrary::<int>() + 1))) && (arbitrary() == value)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == arbitrary()))
}

/// ReceiveAck operator
pub open spec fn LReceiveAck(s: LState, s_: LState, c: LConstants, value: int, sent_packets: ()) -> bool {
    ((arbitrary::<int>() == 3419909347int) || ((((((((((((((arbitrary::<int>() == 9863251288int) && (arbitrary::<bool>() == true)) && Set::<int>::empty().contains(value)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (Set::<int>::empty() == Set::<int>::empty().difference(set![value]))) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == Seq::<int>::empty())))
}

/// ClientRead operator
pub open spec fn LClientRead(s: LState, s_: LState, c: LConstants, sent_packets: ()) -> bool {
    (((((((((((((arbitrary::<int>() == 8736718595int) && (arbitrary::<bool>() == true)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == Seq::<int>::empty()))
}

/// NodeFail operator
pub open spec fn LNodeFail(s: LState, s_: LState, c: LConstants, sent_packets: ()) -> bool {
    ((((((((((((arbitrary::<bool>() == true) && (arbitrary::<bool>() == false)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == Seq::<int>::empty()))
}

/// Reconfigure operator
pub open spec fn LReconfigure(s: LState, s_: LState, c: LConstants, new_has_predecessor: int, new_predecessor: int, new_has_successor: int, new_successor: int, sent_packets: ()) -> bool {
    ((((((((((((arbitrary::<bool>() == true) && (arbitrary() == new_has_predecessor)) && (arbitrary() == new_predecessor)) && (arbitrary() == new_has_successor)) && (arbitrary() == new_successor)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == Seq::<int>::empty()))
}

/// Next operator
pub open spec fn LNext(s: LState, s_: LState, c: LConstants) -> bool {
    exists |value, sent_packets| (LHeadReceiveWrite(s, s_, c, value, sent_packets) || exists |value, sent_packets| (LForwardToSuccessor(s, s_, c, value, sent_packets) || exists |value, sent_packets| (LReceiveUpdate(s, s_, c, value, sent_packets) || exists |value, sent_packets| (LTailCommit(s, s_, c, value, sent_packets) || exists |value, sent_packets| (LReceiveAck(s, s_, c, value, sent_packets) || exists |sent_packets| (LClientRead(s, s_, c, sent_packets) || exists |sent_packets| (LNodeFail(s, s_, c, sent_packets) || exists |new_has_predecessor, new_predecessor, new_has_successor, new_successor, sent_packets| LReconfigure(s, s_, c, new_has_predecessor, new_predecessor, new_has_successor, new_successor, sent_packets))))))))
}

} // verus!
