//! Generated from TLA+ module: Types
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Types module
pub struct LRecord {
    pub alive: int,
    pub chain_len: int,
    pub committed_count: int,
    pub has_predecessor: int,
    pub has_successor: int,
    pub history: int,
    pub node_id: int,
    pub obj_value: int,
    pub pending_sent: int,
    pub predecessor: int,
    pub role: int,
    pub successor: int,
}

/// State for Types module
pub struct LState {
}


/// State operator
pub open spec fn LState() -> { has_successor: Set<bool>, obj_value: Set<int>, history: int, predecessor: Set<int>, has_predecessor: Set<bool>, successor: Set<int>, alive: Set<bool>, pending_sent: Set<Set<int>>, committed_count: Set<int>, role: int } {
    LRecord { alive: bool, chain_len: 0int, committed_count: int, has_predecessor: bool, has_successor: bool, history: Seq(int), node_id: 0int, obj_value: int, pending_sent: int.powerset(), predecessor: int, role: LNodeRole(), successor: int }
}

/// Constants operator
pub open spec fn LConstants() -> { node_id: Set<int>, chain_len: Set<int> } {
    LRecord { alive: 0int, chain_len: int, committed_count: 0int, has_predecessor: 0int, has_successor: 0int, history: 0int, node_id: int, obj_value: 0int, pending_sent: 0int, predecessor: 0int, role: 0int, successor: 0int }
}

/// CRMessage operator
pub open spec fn LCRMessage() -> Set<int> {
    set![Forward, Ack]
}

/// NodeRole operator
pub open spec fn LNodeRole() -> Set<int> {
    set![Head, Middle, Tail]
}

} // verus!
