//! Single-process Verus spec projected from TLA+ module `DiningPhilosophersClean`.
//!
//! Generated by `verus-transpile clean-tla`. Do not edit by hand: the
//! clean-subset spec it came from is the source of truth. Only this header is
//! written by a human; `tests/corpus/scripts/refresh_goldens.sh` replaces the
//! `verus!` block and leaves the prose alone.
//!
//! **What this case shows that the others do not: a fork is not an object.**
//! The original models each fork as a global record with a `holder`, so
//! handing one over is a write into state the neighbour also reads. After
//! projection there is nowhere for that record to live. `hasFork`,
//! `fork_clean` and `has_token` are the same information held *per edge, at
//! each end* — `Map<int, bool>` keyed by neighbour — which is exactly the
//! shape LamportMutex's `req` table has, and for the same reason.
//!
//! **`LMessage` has no payload at all.** `Req` and `Fork` are bare variants:
//! everything they carry is routing, and routing lives on the packet. This is
//! the smallest message enum in the corpus and it is worth seeing, because it
//! is what a protocol looks like when the message *is* the signal.
//!
//! **`LLeft` and `LRight` take no argument.** The source's `Left(p)` /
//! `Right(p)` are node-parameterized, so the parameter projects away and the
//! node's own identity survives as `c.node_id`. `LAdjacent(c, q)` keeps its
//! `q`, because that one is a peer rather than the acting node.
//!
//! **`c.proc` exists because `Init` needs it**, not because any action does.
//! Constant pruning used to run before `Init` was projected, which dropped the
//! node set as unused and then left `Init` referring to a constant that no
//! longer existed. This case is what found it.

use vstd::prelude::*;

verus! {
    /// Wire messages. Routing lives on the packet, not in the payload.
    pub enum LMessage {
        Req,
        Fork,
    }

    /// A message addressed to a peer.
    pub struct LPacket {
        pub dst: int,
        pub msg: LMessage,
    }

    /// This node's state.
    pub struct LState {
        pub has_fork: Map<int, bool>,
        pub fork_clean: Map<int, bool>,
        pub has_token: Map<int, bool>,
        pub hungry: bool,
        pub eating: bool,
    }

    /// Protocol constants, including this node's own identity.
    pub struct LConstants {
        pub n_p: int,
        pub proc: Set<int>,
        pub node_id: int,
    }

    pub open spec fn LLeft(c: LConstants) -> int {
        if c.node_id == 1 { c.n_p } else { c.node_id - 1 }
    }

    pub open spec fn LRight(c: LConstants) -> int {
        if c.node_id == c.n_p { 1 } else { c.node_id + 1 }
    }

    pub open spec fn LAdjacent(c: LConstants, q: int) -> bool {
        q == LLeft(c) || q == LRight(c)
    }

    pub open spec fn LInit(s: LState, c: LConstants) -> bool {
        &&& s.has_fork == Map::new(c.proc, |q: int| LAdjacent(c, q) && c.node_id < q)
        &&& s.fork_clean == Map::new(c.proc, |q: int| false)
        &&& s.has_token == Map::new(c.proc, |q: int| LAdjacent(c, q) && c.node_id > q)
        &&& s.hungry == true
        &&& s.eating == false
    }

    pub open spec fn LRequestFork(
        s: LState,
        s_: LState,
        c: LConstants,
        q: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& s.hungry
        &&& !(s.eating)
        &&& LAdjacent(c, q)
        &&& !(s.has_fork[q])
        &&& s.has_token[q]
        &&& s_.has_token == s.has_token.insert(q, false)
        &&& sent_packets == set![LPacket { dst: q, msg: LMessage::Req }]
        &&& s_.has_fork == s.has_fork
        &&& s_.fork_clean == s.fork_clean
        &&& s_.hungry == s.hungry
        &&& s_.eating == s.eating
    }

    pub open spec fn LHandleRequest(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& s_.has_token == s.has_token.insert(src, true)
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.has_fork == s.has_fork
        &&& s_.fork_clean == s.fork_clean
        &&& s_.hungry == s.hungry
        &&& s_.eating == s.eating
    }

    pub open spec fn LReleaseFork(
        s: LState,
        s_: LState,
        c: LConstants,
        q: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& LAdjacent(c, q)
        &&& s.has_fork[q]
        &&& !(s.fork_clean[q])
        &&& s.has_token[q]
        &&& !(s.eating)
        &&& s_.has_fork == s.has_fork.insert(q, false)
        &&& sent_packets == set![LPacket { dst: q, msg: LMessage::Fork }]
        &&& s_.fork_clean == s.fork_clean
        &&& s_.has_token == s.has_token
        &&& s_.hungry == s.hungry
        &&& s_.eating == s.eating
    }

    pub open spec fn LHandleFork(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& s_.has_fork == s.has_fork.insert(src, true)
        &&& s_.fork_clean == s.fork_clean.insert(src, true)
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.has_token == s.has_token
        &&& s_.hungry == s.hungry
        &&& s_.eating == s.eating
    }

    pub open spec fn LEat(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& s.hungry
        &&& !(s.eating)
        &&& s.has_fork[LLeft(c)]
        &&& s.has_fork[LRight(c)]
        &&& s.fork_clean[LLeft(c)]
        &&& s.fork_clean[LRight(c)]
        &&& s_.eating == true
        &&& s_.hungry == false
        &&& s_.fork_clean == s.fork_clean.insert(LLeft(c), false).insert(LRight(c), false)
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.has_fork == s.has_fork
        &&& s_.has_token == s.has_token
    }

    pub open spec fn LThink(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& s.eating
        &&& s_.eating == false
        &&& s_.hungry == true
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.has_fork == s.has_fork
        &&& s_.fork_clean == s.fork_clean
        &&& s_.has_token == s.has_token
    }

    /// Dispatch on the received message. Delivery and the tag are the
    /// framework's; each handler states only its own conditions.
    pub open spec fn LHandleMessage(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        msg: LMessage,
        sent_packets: Set<LPacket>,
    ) -> bool {
        match msg {
            LMessage::Req =>
                LHandleRequest(s, s_, c, src, sent_packets),
            LMessage::Fork =>
                LHandleFork(s, s_, c, src, sent_packets),
        }
    }

    pub open spec fn LNext(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        ||| (exists|q: int|
                1 <= q && q <= c.n_p && LRequestFork(s, s_, c, q, sent_packets))
        ||| (exists|q: int|
                1 <= q && q <= c.n_p && LReleaseFork(s, s_, c, q, sent_packets))
        ||| LEat(s, s_, c, sent_packets)
        ||| LThink(s, s_, c, sent_packets)
        ||| (exists|src: int, msg: LMessage|
                LHandleMessage(s, s_, c, src, msg, sent_packets))
    }
}
