// Auto-generated by verus-transpiler
// DO NOT EDIT MANUALLY

use std::collections::HashSet;
use vstd::prelude::*;

verus! {

#[derive(Clone)]
pub struct CRecord {
    pub accept_senders: i64,
    pub ballot: i64,
    pub cmd: i64,
    pub committed_count: i64,
    pub dep_count: i64,
    pub executed_count: i64,
    pub fast_quorum_size: i64,
    pub has_conflict: i64,
    pub is_leader: i64,
    pub max_resp_seq: i64,
    pub my_id: i64,
    pub num_replicas: i64,
    pub phase: i64,
    pub preaccept_senders: i64,
    pub quorum_size: i64,
    pub seq: i64,
}

impl CRecord {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CRecord {
    type V = LRecord;

    open spec fn view(&self) -> LRecord {
        LRecord {
            accept_senders: self.accept_senders as int,
            ballot: self.ballot as int,
            cmd: self.cmd as int,
            committed_count: self.committed_count as int,
            dep_count: self.dep_count as int,
            executed_count: self.executed_count as int,
            fast_quorum_size: self.fast_quorum_size as int,
            has_conflict: self.has_conflict as int,
            is_leader: self.is_leader as int,
            max_resp_seq: self.max_resp_seq as int,
            my_id: self.my_id as int,
            num_replicas: self.num_replicas as int,
            phase: self.phase as int,
            preaccept_senders: self.preaccept_senders as int,
            quorum_size: self.quorum_size as int,
            seq: self.seq as int,
        }
    }
}

#[derive(Clone)]
pub struct CState {
}

impl CState {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CState {
    type V = LState;

    open spec fn view(&self) -> LState {
        LState {
        }
    }
}

pub exec fn CConstants() -> (result: CRecord)ensures
    result.well_formed(),
    result@ == LConstants(),
{
    assume(false);
    CRecord {
        accept_senders: 0i64,
        ballot: 0i64,
        cmd: 0i64,
        committed_count: 0i64,
        dep_count: 0i64,
        executed_count: 0i64,
        fast_quorum_size: Carbitrary(),
        has_conflict: 0i64,
        is_leader: 0i64,
        max_resp_seq: 0i64,
        my_id: Carbitrary(),
        num_replicas: Carbitrary(),
        phase: 0i64,
        preaccept_senders: 0i64,
        quorum_size: Carbitrary(),
        seq: 0i64,
    }

}

pub exec fn CState() -> (result: CRecord)ensures
    result.well_formed(),
    result@ == LState(),
{
    assume(false);
    CRecord {
        accept_senders: Carbitrary(),
        ballot: Carbitrary(),
        cmd: Carbitrary(),
        committed_count: Carbitrary(),
        dep_count: Carbitrary(),
        executed_count: Carbitrary(),
        fast_quorum_size: 0i64,
        has_conflict: Carbitrary(),
        is_leader: Carbitrary(),
        max_resp_seq: Carbitrary(),
        my_id: 0i64,
        num_replicas: 0i64,
        phase: Carbitrary(),
        preaccept_senders: Carbitrary(),
        quorum_size: 0i64,
        seq: Carbitrary(),
    }

}

pub exec fn CInstancePhase() -> (result: HashSet<i64>)ensures
    result@ == LInstancePhase(),
{
    assume(false);
    { let mut __hs = HashSet::new(); __hs.insert(6464590606); __hs.insert(6635974839); __hs.insert(5046330240); __hs.insert(1819226073); __hs.insert(6951385236); __hs }

}

pub exec fn CEPaxosMessage() -> (result: HashSet<i64>)ensures
    result@ == LEPaxosMessage(),
{
    assume(false);
    { let mut __hs = HashSet::new(); __hs.insert(7983981238); __hs.insert(8383016784); __hs.insert(4031255529); __hs.insert(7932070043); __hs.insert(9385017532); __hs }

}

} // verus!
