//! Single-process Verus spec projected from TLA+ module `EPaxosClean`.
//!
//! Generated by `verus-transpile clean-tla`. Do not edit by hand: the
//! clean-subset spec it came from is the source of truth. Only this header is
//! written by a human; `tests/corpus/scripts/refresh_goldens.sh` replaces the
//! `verus!` block and leaves the prose alone.
//!
//! **The case that cost the most translator work, and every bit of it was
//! about types.** EPaxos's data is nested — a record inside a record inside a
//! set — and nine defects fell out of translating it, listed here against what
//! they produce (`rewrite.md` has the fidelity claims):
//!
//! - **`LRecordStatus`.** An enum inside a *record* has no variable to be
//!   named after, so it took the record's name and the field's. Unnamed, the
//!   emitter wrote `pub status: ,` — a field with no type at all.
//! - **`PreAccepted`, not `Pre-accepted`.** The status tags contain a hyphen,
//!   and the variant-name rule only uppercased the first letter. Paxos's
//!   `"1a"`/`"2b"` had forced a leading-`M` rule but never a word split.
//! - **`LRec(.., LRecordStatus::PreAccepted, ..)`.** A literal in an argument
//!   position the callee types as an enum names a variant. Passed through, it
//!   was a `&str` where an enum was expected.
//! - **`LRec` returns `LRecord`**, and `LInst` returns `LInstance`. A record
//!   literal's type is the struct its field names match; without that the
//!   return type came from the emitted text, which said `int`.
//! - **`LMax` returns `int`** and **`LKnownInstances` returns
//!   `Set<LInstance>`** — a `CHOOSE` has the element type of its set, and a
//!   comprehension is a set of whatever its body produces.
//! - **`choose|x: int| ..`.** `CHOOSE x \in S : P` translates directly:
//!   Verus's `choose` is Hilbert's epsilon and so is TLA+'s, both deterministic
//!   in the predicate. `Max(s) == CHOOSE x \in s : \A y \in s : x >= y` is
//!   the idiom that needed it.
//! - **`exists|rec: LRecord| s.cmd_log.contains(rec) && ..`.** An action that
//!   picks a record out of its own state and updates from it. The binder is
//!   quantified in the conjunct, its updates are the action's updates, and it
//!   is *typed* inside its own body — otherwise `rec.status = "pre-accepted"`
//!   compares a string to an enum.
//! - **`c_arg`.** EPaxos has a parameter literally called `c`, which is the
//!   constants record here. Actions were not renaming their own parameters the
//!   way helpers already did.
//! - **`LMax` is emitted at all.** The helper set was the directly-called one;
//!   `NextSeq` calls `Max`, and the output referenced `LMax` without defining
//!   it. The closure is transitive now.
//!
//! **Read `LIsFastQuorum` beside `LIsSlowQuorum`.** They are the whole point of
//! EPaxos: the fast path commits without an Accept round, but only on a larger
//! quorum *and* unanimous agreement on the attributes (`s.agreed`). The
//! original expresses that by scanning the network for a quorum's worth of
//! replies and asking whether they all match; a replica cannot read the network
//! that way, so `clean.tla` accumulates the answer as replies arrive.

use vstd::prelude::*;

verus! {
    pub enum LRecordStatus {
        PreAccepted,
        Accepted,
        Committed,
    }

    pub struct LInstance {
        pub owner: int,
        pub num: int,
    }

    pub struct LRecord {
        pub inst: LInstance,
        pub status: LRecordStatus,
        pub cmd: int,
        pub deps: Set<LInstance>,
        pub seq: int,
    }

    /// Wire messages. Routing lives on the packet, not in the payload.
    pub enum LMessage {
        Paq { minst: LInstance, mcmd: int, mdeps: Set<LInstance>, mseq: int },
        Pap { minst: LInstance, mdeps: Set<LInstance>, mseq: int },
        Aq { minst: LInstance, mcmd: int, mdeps: Set<LInstance>, mseq: int },
        Ap { minst: LInstance },
        Cmt { minst: LInstance, mcmd: int, mdeps: Set<LInstance>, mseq: int },
    }

    /// A message addressed to a peer.
    pub struct LPacket {
        pub dst: int,
        pub msg: LMessage,
    }

    /// This node's state.
    pub struct LState {
        pub cmd_log: Set<LRecord>,
        pub crt_inst: int,
        pub leading: int,
        pub pre_accept_rcvd: Set<int>,
        pub accept_rcvd: Set<int>,
        pub agreed: bool,
        pub leader_deps: Set<LInstance>,
        pub leader_seq: int,
    }

    /// Protocol constants, including this node's own identity.
    pub struct LConstants {
        pub replicas: Set<int>,
        pub commands: Set<int>,
        pub max_instance: int,
        pub max_seq: int,
        pub node_id: int,
    }

    pub open spec fn LInst(c: LConstants, n: int) -> LInstance {
        LInstance { owner: c.node_id, num: n }
    }

    pub open spec fn LRec(c: LConstants, i: LInstance, st: LRecordStatus, c_arg: int, d: Set<LInstance>, s_arg: int) -> LRecord {
        LRecord { inst: i, status: st, cmd: c_arg, deps: d, seq: s_arg }
    }

    pub open spec fn LIsSlowQuorum(c: LConstants, s_arg: Set<int>) -> bool {
        (s_arg.len() as int) * 2 > (c.replicas.len() as int)
    }

    pub open spec fn LIsFastQuorum(c: LConstants, s_arg: Set<int>) -> bool {
        (s_arg.len() as int) * 4 > (c.replicas.len() as int) * 3
    }

    pub open spec fn LMax(c: LConstants, s_arg: Set<int>) -> int {
        choose|x: int| s_arg.contains(x) && forall|y: int| s_arg.contains(y) ==> x >= y
    }

    pub open spec fn LKnownInstances(c: LConstants, log: Set<LRecord>) -> Set<LInstance> {
        log.map(|rec: LRecord| rec.inst)
    }

    pub open spec fn LNextSeq(c: LConstants, log: Set<LRecord>) -> int {
        1 + LMax(c, log.map(|rec: LRecord| rec.seq).union(set![0]))
    }

    pub open spec fn LInit(s: LState, c: LConstants) -> bool {
        &&& s.cmd_log == Set::<LRecord>::empty()
        &&& s.crt_inst == 1
        &&& s.leading == 0
        &&& s.pre_accept_rcvd == Set::<int>::empty()
        &&& s.accept_rcvd == Set::<int>::empty()
        &&& s.agreed == true
        &&& s.leader_deps == Set::<LInstance>::empty()
        &&& s.leader_seq == 0
    }

    pub open spec fn LPropose(
        s: LState,
        s_: LState,
        c: LConstants,
        c_arg: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& s.leading == 0
        &&& s.crt_inst <= c.max_instance
        &&& LNextSeq(c, s.cmd_log) <= c.max_seq
        &&& s_.leading == s.crt_inst
        &&& s_.crt_inst == s.crt_inst + 1
        &&& s_.leader_deps == LKnownInstances(c, s.cmd_log)
        &&& s_.leader_seq == LNextSeq(c, s.cmd_log)
        &&& s_.pre_accept_rcvd == Set::<int>::empty()
        &&& s_.accept_rcvd == Set::<int>::empty()
        &&& s_.agreed == true
        &&& s_.cmd_log == s.cmd_log.union(set![LRec(c, LInst(c, s.crt_inst), LRecordStatus::PreAccepted, c_arg, LKnownInstances(c, s.cmd_log), LNextSeq(c, s.cmd_log))])
        &&& sent_packets == c.replicas.map(|d: int| LPacket { dst: d, msg: LMessage::Paq { minst: LInst(c, s.crt_inst), mcmd: c_arg, mdeps: LKnownInstances(c, s.cmd_log), mseq: LNextSeq(c, s.cmd_log) } })
    }

    pub open spec fn LHandlePreAcceptReq(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        minst: LInstance,
        mcmd: int,
        mdeps: Set<LInstance>,
        mseq: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& LNextSeq(c, s.cmd_log) <= c.max_seq
        &&& s_.cmd_log == s.cmd_log.union(set![LRec(c, minst, LRecordStatus::PreAccepted, mcmd, mdeps.union(LKnownInstances(c, s.cmd_log)), if LNextSeq(c, s.cmd_log) > mseq { LNextSeq(c, s.cmd_log) } else { mseq })])
        &&& sent_packets == set![LPacket { dst: src, msg: LMessage::Pap { minst: minst, mdeps: mdeps.union(LKnownInstances(c, s.cmd_log)), mseq: if LNextSeq(c, s.cmd_log) > mseq { LNextSeq(c, s.cmd_log) } else { mseq } } }]
        &&& s_.crt_inst == s.crt_inst
        &&& s_.leading == s.leading
        &&& s_.pre_accept_rcvd == s.pre_accept_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.agreed == s.agreed
        &&& s_.leader_deps == s.leader_deps
        &&& s_.leader_seq == s.leader_seq
    }

    pub open spec fn LHandlePreAcceptResp(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        minst: LInstance,
        mdeps: Set<LInstance>,
        mseq: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& minst.owner == c.node_id
        &&& minst.num == s.leading
        &&& s_.pre_accept_rcvd == s.pre_accept_rcvd.union(set![src])
        &&& s_.agreed == s.agreed && mdeps == s.leader_deps && mseq == s.leader_seq
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.cmd_log == s.cmd_log
        &&& s_.crt_inst == s.crt_inst
        &&& s_.leading == s.leading
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.leader_deps == s.leader_deps
        &&& s_.leader_seq == s.leader_seq
    }

    pub open spec fn LCommitFast(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& s.leading != 0
        &&& LIsFastQuorum(c, s.pre_accept_rcvd)
        &&& s.agreed
        &&& exists|rec: LRecord| s.cmd_log.contains(rec) && rec.inst == LInst(c, s.leading) && rec.status is PreAccepted && s_.cmd_log == s.cmd_log.difference(set![rec]).union(set![LRec(c, rec.inst, LRecordStatus::Committed, rec.cmd, s.leader_deps, s.leader_seq)]) && sent_packets == c.replicas.map(|d: int| LPacket { dst: d, msg: LMessage::Cmt { minst: rec.inst, mcmd: rec.cmd, mdeps: s.leader_deps, mseq: s.leader_seq } })
        &&& s_.leading == 0
        &&& s_.crt_inst == s.crt_inst
        &&& s_.pre_accept_rcvd == s.pre_accept_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.agreed == s.agreed
        &&& s_.leader_deps == s.leader_deps
        &&& s_.leader_seq == s.leader_seq
    }

    pub open spec fn LStartAccept(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& s.leading != 0
        &&& LIsSlowQuorum(c, s.pre_accept_rcvd)
        &&& !(s.agreed)
        &&& exists|rec: LRecord| s.cmd_log.contains(rec) && rec.inst == LInst(c, s.leading) && rec.status is PreAccepted && s_.cmd_log == s.cmd_log.difference(set![rec]).union(set![LRec(c, rec.inst, LRecordStatus::Accepted, rec.cmd, s.leader_deps, s.leader_seq)]) && sent_packets == c.replicas.map(|d: int| LPacket { dst: d, msg: LMessage::Aq { minst: rec.inst, mcmd: rec.cmd, mdeps: s.leader_deps, mseq: s.leader_seq } })
        &&& s_.accept_rcvd == Set::<int>::empty()
        &&& s_.crt_inst == s.crt_inst
        &&& s_.leading == s.leading
        &&& s_.pre_accept_rcvd == s.pre_accept_rcvd
        &&& s_.agreed == s.agreed
        &&& s_.leader_deps == s.leader_deps
        &&& s_.leader_seq == s.leader_seq
    }

    pub open spec fn LHandleAcceptReq(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        minst: LInstance,
        mcmd: int,
        mdeps: Set<LInstance>,
        mseq: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& s_.cmd_log == s.cmd_log.union(set![LRec(c, minst, LRecordStatus::Accepted, mcmd, mdeps, mseq)])
        &&& sent_packets == set![LPacket { dst: src, msg: LMessage::Ap { minst: minst } }]
        &&& s_.crt_inst == s.crt_inst
        &&& s_.leading == s.leading
        &&& s_.pre_accept_rcvd == s.pre_accept_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.agreed == s.agreed
        &&& s_.leader_deps == s.leader_deps
        &&& s_.leader_seq == s.leader_seq
    }

    pub open spec fn LHandleAcceptResp(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        minst: LInstance,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& minst.owner == c.node_id
        &&& minst.num == s.leading
        &&& s_.accept_rcvd == s.accept_rcvd.union(set![src])
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.cmd_log == s.cmd_log
        &&& s_.crt_inst == s.crt_inst
        &&& s_.leading == s.leading
        &&& s_.pre_accept_rcvd == s.pre_accept_rcvd
        &&& s_.agreed == s.agreed
        &&& s_.leader_deps == s.leader_deps
        &&& s_.leader_seq == s.leader_seq
    }

    pub open spec fn LCommitSlow(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& s.leading != 0
        &&& LIsSlowQuorum(c, s.accept_rcvd)
        &&& exists|rec: LRecord| s.cmd_log.contains(rec) && rec.inst == LInst(c, s.leading) && rec.status is Accepted && s_.cmd_log == s.cmd_log.difference(set![rec]).union(set![LRec(c, rec.inst, LRecordStatus::Committed, rec.cmd, rec.deps, rec.seq)]) && sent_packets == c.replicas.map(|d: int| LPacket { dst: d, msg: LMessage::Cmt { minst: rec.inst, mcmd: rec.cmd, mdeps: rec.deps, mseq: rec.seq } })
        &&& s_.leading == 0
        &&& s_.crt_inst == s.crt_inst
        &&& s_.pre_accept_rcvd == s.pre_accept_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.agreed == s.agreed
        &&& s_.leader_deps == s.leader_deps
        &&& s_.leader_seq == s.leader_seq
    }

    pub open spec fn LHandleCommit(
        s: LState,
        s_: LState,
        c: LConstants,
        minst: LInstance,
        mcmd: int,
        mdeps: Set<LInstance>,
        mseq: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& s_.cmd_log == s.cmd_log.union(set![LRec(c, minst, LRecordStatus::Committed, mcmd, mdeps, mseq)])
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.crt_inst == s.crt_inst
        &&& s_.leading == s.leading
        &&& s_.pre_accept_rcvd == s.pre_accept_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.agreed == s.agreed
        &&& s_.leader_deps == s.leader_deps
        &&& s_.leader_seq == s.leader_seq
    }

    /// Dispatch on the received message. Delivery and the tag are the
    /// framework's; each handler states only its own conditions.
    pub open spec fn LHandleMessage(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        msg: LMessage,
        sent_packets: Set<LPacket>,
    ) -> bool {
        match msg {
            LMessage::Paq { minst, mcmd, mdeps, mseq } =>
                LHandlePreAcceptReq(s, s_, c, src, minst, mcmd, mdeps, mseq, sent_packets),
            LMessage::Pap { minst, mdeps, mseq } =>
                LHandlePreAcceptResp(s, s_, c, src, minst, mdeps, mseq, sent_packets),
            LMessage::Aq { minst, mcmd, mdeps, mseq } =>
                LHandleAcceptReq(s, s_, c, src, minst, mcmd, mdeps, mseq, sent_packets),
            LMessage::Ap { minst } =>
                LHandleAcceptResp(s, s_, c, src, minst, sent_packets),
            LMessage::Cmt { minst, mcmd, mdeps, mseq } =>
                LHandleCommit(s, s_, c, minst, mcmd, mdeps, mseq, sent_packets),
        }
    }

    pub open spec fn LNext(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        ||| (exists|c_arg: int|
                c.commands.contains(c_arg) && LPropose(s, s_, c, c_arg, sent_packets))
        ||| LCommitFast(s, s_, c, sent_packets)
        ||| LStartAccept(s, s_, c, sent_packets)
        ||| LCommitSlow(s, s_, c, sent_packets)
        ||| (exists|src: int, msg: LMessage|
                LHandleMessage(s, s_, c, src, msg, sent_packets))
    }
}
