//! Generated from TLA+ module: Types
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Types module
pub struct LRecord {
    pub rm: int,
    pub rm_aborted: int,
    pub rm_committed: int,
    pub rm_prepared: int,
    pub tm_prepared: int,
    pub tm_state: int,
}

/// State for Types module
pub struct LState {
}


/// State operator
pub open spec fn LState() -> { rm_committed: Set<Set<int>>, rm_prepared: Set<Set<int>>, tm_prepared: Set<Set<int>>, tm_state: int, rm_aborted: Set<Set<int>> } {
    LRecord { rm: 0int, rm_aborted: int.powerset(), rm_committed: int.powerset(), rm_prepared: int.powerset(), tm_prepared: int.powerset(), tm_state: LTMState() }
}

/// Constants operator
pub open spec fn LConstants() -> { rm: Set<Set<int>> } {
    LRecord { rm: int.powerset(), rm_aborted: 0int, rm_committed: 0int, rm_prepared: 0int, tm_prepared: 0int, tm_state: 0int }
}

/// TMState operator
pub open spec fn LTMState() -> Set<int> {
    set![Init, Committed, Aborted]
}

/// RMState operator
pub open spec fn LRMState() -> Set<int> {
    set![Working, Prepared, Committed, Aborted]
}

/// TPCMessage operator
pub open spec fn LTPCMessage() -> Set<int> {
    set![Prepare, PreparedVote, Commit, Abort]
}

} // verus!
