//! Generated from TLA+ module: Types
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Types module
pub struct LRecord {
    pub rm: int,
    pub rm_aborted: int,
    pub rm_committed: int,
    pub rm_prepared: int,
    pub tm_prepared: int,
    pub tm_state: int,
}

/// State for Types module
pub struct LState {
}


/// State operator
pub open spec fn LState() -> LRecord {
    LRecord { rm: 0int, rm_aborted: arbitrary(), rm_committed: arbitrary(), rm_prepared: arbitrary(), tm_prepared: arbitrary(), tm_state: arbitrary() }
}

/// Constants operator
pub open spec fn LConstants() -> LRecord {
    LRecord { rm: arbitrary(), rm_aborted: 0int, rm_committed: 0int, rm_prepared: 0int, tm_prepared: 0int, tm_state: 0int }
}

/// TMState operator
pub open spec fn LTMState() -> Set<int> {
    set![1755428851int, 1819226073int, 4391523824int]
}

/// RMState operator
pub open spec fn LRMState() -> Set<int> {
    set![7249365736int, 9617861224int, 1819226073int, 4391523824int]
}

/// TPCMessage operator
pub open spec fn LTPCMessage() -> Set<int> {
    set![6989001116int, 8119312364int, 9385017532int, 8579416217int]
}

} // verus!
