//! Generated from TLA+ module: Primarybackup
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Primarybackup module
pub struct LRecord {
    pub val: int,
}

/// State for Primarybackup module
pub struct LState {
}

/// Constants for the module
pub struct LConstants {
    pub Constants: int,
    pub State: int,
    pub PBMessage: int,
}


/// Init operator
pub open spec fn LInit(s: LState, c: LConstants) -> bool {
    ((((((((((arbitrary::<int>() == 6049598361int) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == false)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == 0))
}

/// PrimaryWrite operator
pub open spec fn LPrimaryWrite(s: LState, c: LConstants, s_: int, val: int, sent_packets: int) -> bool {
    (((((((((((((((arbitrary::<int>() == 6049598361int) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == false)) && (arbitrary::<int>() < arbitrary::<int>())) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == val)) && (arbitrary::<int>() == false)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == seq![]))
}

/// PrimarySendReplicate operator
pub open spec fn LPrimarySendReplicate(s: LState, c: LConstants, s_: int, sent_packets: int) -> bool {
    ((((((((((((((arbitrary::<int>() == 6049598361int) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == false)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == seq![LRecord { val: arbitrary::<int>() }]))
}

/// BackupReceiveReplicate operator
pub open spec fn LBackupReceiveReplicate(s: LState, c: LConstants, s_: int, val: int, sent_packets: int) -> bool {
    ((((((((((((arbitrary::<int>() == 6049598361int) && (arbitrary::<int>() == (arbitrary::<int>() + 1))) && (arbitrary::<int>() == val)) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == seq![]))
}

/// BackupSendAck operator
pub open spec fn LBackupSendAck(s: LState, c: LConstants, s_: int, sent_packets: int) -> bool {
    (((((((((((((arbitrary::<int>() == 6049598361int) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == seq![7544150754int]))
}

/// PrimaryReceiveAck operator
pub open spec fn LPrimaryReceiveAck(s: LState, c: LConstants, s_: int, sent_packets: int) -> bool {
    (((((((((((((arbitrary::<int>() == 6049598361int) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == seq![]))
}

/// PrimaryCommit operator
pub open spec fn LPrimaryCommit(s: LState, c: LConstants, s_: int, sent_packets: int) -> bool {
    ((((((((((((((arbitrary::<int>() == 6049598361int) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == (arbitrary::<int>() + 1))) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == false)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == seq![]))
}

/// PrimaryFail operator
pub open spec fn LPrimaryFail(s: LState, c: LConstants, s_: int, sent_packets: int) -> bool {
    ((((((((((((arbitrary::<int>() == 6049598361int) && (arbitrary::<int>() == 1048442360int)) && (arbitrary::<int>() == false)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == false)) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == seq![]))
}

/// BackupPromote operator
pub open spec fn LBackupPromote(s: LState, c: LConstants, s_: int, sent_packets: int) -> bool {
    ((((((((((((arbitrary::<int>() == 1048442360int) && (arbitrary::<int>() == 6049598361int)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == false)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == (arbitrary::<int>() + 1))) && (sent_packets == seq![]))
}

/// Next operator
pub open spec fn LNext(s: LState, c: LConstants, s_: int) -> bool {
    exists |val, sent_packets| (LPrimaryWrite(s, c, s, s_, c, val, sent_packets) || exists |sent_packets| (LPrimarySendReplicate(s, c, s, s_, c, sent_packets) || exists |val, sent_packets| (LBackupReceiveReplicate(s, c, s, s_, c, val, sent_packets) || exists |sent_packets| (LBackupSendAck(s, c, s, s_, c, sent_packets) || exists |sent_packets| (LPrimaryReceiveAck(s, c, s, s_, c, sent_packets) || exists |sent_packets| (LPrimaryCommit(s, c, s, s_, c, sent_packets) || exists |sent_packets| (LPrimaryFail(s, c, s, s_, c, sent_packets) || exists |sent_packets| LBackupPromote(s, c, s, s_, c, sent_packets))))))))
}

} // verus!
