//! Generated from TLA+ module: Epaxos
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Epaxos module
pub struct LRecord {
    pub ballot: int,
    pub cmd: int,
    pub conflict: int,
    pub sender: int,
    pub seq: int,
}

/// State for Epaxos module
pub struct LState {
}

/// Constants for the module
pub struct LConstants {
    pub EPaxosMessage: int,
    pub State: int,
    pub Constants: int,
}


/// Init operator
pub open spec fn LInit(s: LState, c: LConstants) -> bool {
    (((((((((((((((arbitrary::<int>() == 0) && (arbitrary::<int>() == 6464590606int)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && (arbitrary::<bool>() == false)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && (Set::<int>::empty() == Set::<int>::empty())) && (Set::<int>::empty() == Set::<int>::empty())) && (arbitrary::<bool>() == false)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() >= 3)) && (arbitrary::<int>() > 0)) && (arbitrary::<int>() >= arbitrary::<int>()))
}

/// Propose operator
pub open spec fn LPropose(s: LState, s_: LState, c: LConstants, value: int, sent_packets: (LRecord)) -> bool {
    ((((((((((((((arbitrary::<int>() == 6464590606int) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 6635974839int)) && (arbitrary() == value)) && (arbitrary::<int>() == (arbitrary::<int>() + 1))) && (arbitrary::<int>() == 0)) && (arbitrary::<bool>() == true)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary() == Set::<int>::empty().union(set![arbitrary()]))) && (Set::<int>::empty() == Set::<int>::empty())) && (arbitrary::<bool>() == false)) && (arbitrary::<int>() == 0)) && (sent_packets == arbitrary()))
}

/// SendPreAcceptOk operator
pub open spec fn LSendPreAcceptOk(s: LState, s_: LState, c: LConstants, local_conflict: int, local_seq: int, sent_packets: (LRecord)) -> bool {
    (((((((((((((sent_packets == arbitrary()) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>()))
}

/// ReceivePreAcceptOk operator
pub open spec fn LReceivePreAcceptOk(s: LState, s_: LState, c: LConstants, pa_sender: int, pa_seq: bool, pa_conflict: bool, sent_packets: ()) -> bool {
    (((((arbitrary::<int>() == 6635974839int) && (arbitrary::<bool>() == true)) && !Set::<int>::empty().contains(pa_sender)) && (arbitrary() == Set::<int>::empty().union(set![pa_sender]))) && (arbitrary::<bool>() == if pa_conflict { true } else { (arbitrary() && (arbitrary::<int>() == arbitrary::<int>())) }))
}

/// FastCommit operator
pub open spec fn LFastCommit(s: LState, s_: LState, c: LConstants, sent_packets: (LRecord)) -> bool {
    (((((((((((((((((arbitrary::<int>() == 6635974839int) && (arbitrary::<bool>() == true)) && (arbitrary().len() >= arbitrary::<int>())) && (arbitrary::<bool>() == false)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 1819226073int)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == (arbitrary::<int>() + 1))) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == arbitrary()))
}

/// StartAccept operator
pub open spec fn LStartAccept(s: LState, s_: LState, c: LConstants, sent_packets: (LRecord)) -> bool {
    (((((((((((((((((arbitrary::<int>() == 6635974839int) && (arbitrary::<bool>() == true)) && (arbitrary().len() >= arbitrary::<int>())) && (arbitrary::<bool>() == true)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 5046330240int)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary() == Set::<int>::empty().union(set![arbitrary()]))) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == arbitrary()))
}

/// SendAcceptOk operator
pub open spec fn LSendAcceptOk(s: LState, s_: LState, c: LConstants, sent_packets: (LRecord)) -> bool {
    (((((((((((((sent_packets == arbitrary()) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>()))
}

/// ReceiveAcceptOk operator
pub open spec fn LReceiveAcceptOk(s: LState, s_: LState, c: LConstants, ao_sender: int, sent_packets: ()) -> bool {
    ((((((((((((((((arbitrary::<int>() == 5046330240int) && (arbitrary::<bool>() == true)) && !Set::<int>::empty().contains(ao_sender)) && (arbitrary() == Set::<int>::empty().union(set![ao_sender]))) && (sent_packets == Seq::<int>::empty())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>()))
}

/// SlowCommit operator
pub open spec fn LSlowCommit(s: LState, s_: LState, c: LConstants, sent_packets: (LRecord)) -> bool {
    ((((((((((((((((arbitrary::<int>() == 5046330240int) && (arbitrary::<bool>() == true)) && (arbitrary().len() >= arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 1819226073int)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == (arbitrary::<int>() + 1))) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == arbitrary()))
}

/// Execute operator
pub open spec fn LExecute(s: LState, s_: LState, c: LConstants, sent_packets: ()) -> bool {
    ((((((((((((((arbitrary::<int>() == 1819226073int) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 6951385236int)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == (arbitrary::<int>() + 1))) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == Seq::<int>::empty()))
}

/// Recover operator
pub open spec fn LRecover(s: LState, s_: LState, c: LConstants, new_ballot: int, sent_packets: (LRecord)) -> bool {
    ((arbitrary::<int>() == 6635974839int) || (((((((((((((((arbitrary::<int>() == 5046330240int) && (new_ballot > arbitrary::<int>())) && (arbitrary() == new_ballot)) && (arbitrary::<int>() == 6635974839int)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 0)) && (arbitrary::<bool>() == true)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary() == Set::<int>::empty().union(set![arbitrary()]))) && (Set::<int>::empty() == Set::<int>::empty())) && (arbitrary::<bool>() == false)) && (arbitrary::<int>() == 0)) && (sent_packets == arbitrary())))
}

/// NewInstance operator
pub open spec fn LNewInstance(s: LState, s_: LState, c: LConstants, sent_packets: ()) -> bool {
    ((((((((((((((arbitrary::<int>() == 6951385236int) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 6464590606int)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && (arbitrary::<bool>() == false)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (Set::<int>::empty() == Set::<int>::empty())) && (Set::<int>::empty() == Set::<int>::empty())) && (arbitrary::<bool>() == false)) && (arbitrary::<int>() == 0)) && (sent_packets == Seq::<int>::empty()))
}

/// Next operator
pub open spec fn LNext(s: LState, s_: LState, c: LConstants) -> bool {
    exists |value, sent_packets| (LPropose(s, s_, c, value, sent_packets) || exists |local_conflict, local_seq, sent_packets| (LSendPreAcceptOk(s, s_, c, local_conflict, local_seq, sent_packets) || exists |pa_sender, pa_seq, pa_conflict, sent_packets| (LReceivePreAcceptOk(s, s_, c, pa_sender, pa_seq, pa_conflict, sent_packets) || exists |sent_packets| (LFastCommit(s, s_, c, sent_packets) || exists |sent_packets| (LStartAccept(s, s_, c, sent_packets) || exists |sent_packets| (LSendAcceptOk(s, s_, c, sent_packets) || exists |ao_sender, sent_packets| (LReceiveAcceptOk(s, s_, c, ao_sender, sent_packets) || exists |sent_packets| (LSlowCommit(s, s_, c, sent_packets) || exists |sent_packets| (LExecute(s, s_, c, sent_packets) || exists |new_ballot, sent_packets| (LRecover(s, s_, c, new_ballot, sent_packets) || exists |sent_packets| LNewInstance(s, s_, c, sent_packets)))))))))))
}

} // verus!
