//! Generated from TLA+ module: Epaxos
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Epaxos module
pub struct LRecord {
    pub ballot: int,
    pub cmd: int,
    pub conflict: int,
    pub sender: int,
    pub seq: int,
}

/// State for Epaxos module
pub struct LState {
}

/// Constants for the module
pub struct LConstants {
    pub EPaxosMessage: int,
    pub State: int,
    pub Constants: int,
}


/// Init operator
pub open spec fn LInit(s: LState, c: LConstants) -> bool {
    (((((((((((((((arbitrary::<int>() == 0) && (arbitrary::<int>() == 6464590606int)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == false)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == Set::<int>::empty())) && (arbitrary::<int>() == Set::<int>::empty())) && (arbitrary::<int>() == false)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() >= 3)) && (arbitrary::<int>() > 0)) && (arbitrary::<int>() >= arbitrary::<int>()))
}

/// Propose operator
pub open spec fn LPropose(s: LState, c: LConstants, s_: int, value: int, sent_packets: int) -> bool {
    ((((((((((((((arbitrary::<int>() == 6464590606int) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 6635974839int)) && (arbitrary::<int>() == value)) && (arbitrary::<int>() == (arbitrary::<int>() + 1))) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == Set::<int>::empty().union(set![arbitrary::<int>()]))) && (arbitrary::<int>() == Set::<int>::empty())) && (arbitrary::<int>() == false)) && (arbitrary::<int>() == 0)) && (sent_packets == seq![LRecord { ballot: arbitrary::<int>(), cmd: value, conflict: 0int, sender: 0int, seq: (arbitrary::<int>() + 1) }]))
}

/// SendPreAcceptOk operator
pub open spec fn LSendPreAcceptOk(s: LState, c: LConstants, s_: int, local_conflict: int, local_seq: int, sent_packets: int) -> bool {
    (((((((((((((sent_packets == seq![LRecord { ballot: 0int, cmd: 0int, conflict: local_conflict, sender: arbitrary::<int>(), seq: local_seq }]) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>()))
}

/// ReceivePreAcceptOk operator
pub open spec fn LReceivePreAcceptOk(s: LState, c: LConstants, s_: int, pa_sender: int, pa_seq: int, pa_conflict: int, sent_packets: int) -> bool {
    (((((arbitrary::<int>() == 6635974839int) && (arbitrary::<int>() == true)) && arbitrary::<int>().contains(!(pa_sender))) && (arbitrary::<int>() == arbitrary::<int>().union(set![pa_sender]))) && (arbitrary::<int>() == if pa_conflict { true } else { (arbitrary::<int>() && (arbitrary::<int>() == if pa_conflict { (arbitrary::<int>() + 1) } else { (arbitrary::<int>() && (arbitrary::<int>() == if (pa_seq > arbitrary::<int>()) { pa_seq } else { (arbitrary::<int>() && (arbitrary::<int>() == if (pa_seq > arbitrary::<int>()) { pa_seq } else { ((((((((arbitrary::<int>() && (sent_packets == seq![])) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) })) })) })) }))
}

/// FastCommit operator
pub open spec fn LFastCommit(s: LState, c: LConstants, s_: int, sent_packets: int) -> bool {
    (((((((((((((((((arbitrary::<int>() == 6635974839int) && (arbitrary::<int>() == true)) && (arbitrary::<int>().len() >= arbitrary::<int>())) && (arbitrary::<int>() == false)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 1819226073int)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == (arbitrary::<int>() + 1))) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == seq![LRecord { ballot: 0int, cmd: arbitrary::<int>(), conflict: 0int, sender: 0int, seq: arbitrary::<int>() }]))
}

/// StartAccept operator
pub open spec fn LStartAccept(s: LState, c: LConstants, s_: int, sent_packets: int) -> bool {
    (((((((((((((((((arbitrary::<int>() == 6635974839int) && (arbitrary::<int>() == true)) && (arbitrary::<int>().len() >= arbitrary::<int>())) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 5046330240int)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == Set::<int>::empty().union(set![arbitrary::<int>()]))) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == seq![LRecord { ballot: arbitrary::<int>(), cmd: arbitrary::<int>(), conflict: 0int, sender: 0int, seq: arbitrary::<int>() }]))
}

/// SendAcceptOk operator
pub open spec fn LSendAcceptOk(s: LState, c: LConstants, s_: int, sent_packets: int) -> bool {
    (((((((((((((sent_packets == seq![LRecord { ballot: 0int, cmd: 0int, conflict: 0int, sender: arbitrary::<int>(), seq: 0int }]) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>()))
}

/// ReceiveAcceptOk operator
pub open spec fn LReceiveAcceptOk(s: LState, c: LConstants, s_: int, ao_sender: int, sent_packets: int) -> bool {
    ((((((((((((((((arbitrary::<int>() == 5046330240int) && (arbitrary::<int>() == true)) && arbitrary::<int>().contains(!(ao_sender))) && (arbitrary::<int>() == arbitrary::<int>().union(set![ao_sender]))) && (sent_packets == seq![])) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>()))
}

/// SlowCommit operator
pub open spec fn LSlowCommit(s: LState, c: LConstants, s_: int, sent_packets: int) -> bool {
    ((((((((((((((((arbitrary::<int>() == 5046330240int) && (arbitrary::<int>() == true)) && (arbitrary::<int>().len() >= arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 1819226073int)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == (arbitrary::<int>() + 1))) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == seq![LRecord { ballot: 0int, cmd: arbitrary::<int>(), conflict: 0int, sender: 0int, seq: arbitrary::<int>() }]))
}

/// Execute operator
pub open spec fn LExecute(s: LState, c: LConstants, s_: int, sent_packets: int) -> bool {
    ((((((((((((((arbitrary::<int>() == 1819226073int) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 6951385236int)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == (arbitrary::<int>() + 1))) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (sent_packets == seq![]))
}

/// Recover operator
pub open spec fn LRecover(s: LState, c: LConstants, s_: int, new_ballot: int, sent_packets: int) -> bool {
    ((arbitrary::<int>() == 6635974839int) || (((((((((((((((arbitrary::<int>() == 5046330240int) && (new_ballot > arbitrary::<int>())) && (arbitrary::<int>() == new_ballot)) && (arbitrary::<int>() == 6635974839int)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == true)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == Set::<int>::empty().union(set![arbitrary::<int>()]))) && (arbitrary::<int>() == Set::<int>::empty())) && (arbitrary::<int>() == false)) && (arbitrary::<int>() == 0)) && (sent_packets == seq![LRecord { ballot: new_ballot, cmd: arbitrary::<int>(), conflict: 0int, sender: 0int, seq: arbitrary::<int>() }])))
}

/// NewInstance operator
pub open spec fn LNewInstance(s: LState, c: LConstants, s_: int, sent_packets: int) -> bool {
    ((((((((((((((arbitrary::<int>() == 6951385236int) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 6464590606int)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == false)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == Set::<int>::empty())) && (arbitrary::<int>() == Set::<int>::empty())) && (arbitrary::<int>() == false)) && (arbitrary::<int>() == 0)) && (sent_packets == seq![]))
}

/// Next operator
pub open spec fn LNext(s: LState, c: LConstants, s_: int) -> bool {
    exists |value, sent_packets| (LPropose(s, c, s, s_, c, value, sent_packets) || exists |local_conflict, local_seq, sent_packets| (LSendPreAcceptOk(s, c, s, s_, c, local_conflict, local_seq, sent_packets) || exists |pa_sender, pa_seq, pa_conflict, sent_packets| (LReceivePreAcceptOk(s, c, s, s_, c, pa_sender, pa_seq, pa_conflict, sent_packets) || exists |sent_packets| (LFastCommit(s, c, s, s_, c, sent_packets) || exists |sent_packets| (LStartAccept(s, c, s, s_, c, sent_packets) || exists |sent_packets| (LSendAcceptOk(s, c, s, s_, c, sent_packets) || exists |ao_sender, sent_packets| (LReceiveAcceptOk(s, c, s, s_, c, ao_sender, sent_packets) || exists |sent_packets| (LSlowCommit(s, c, s, s_, c, sent_packets) || exists |sent_packets| (LExecute(s, c, s, s_, c, sent_packets) || exists |new_ballot, sent_packets| (LRecover(s, c, s, s_, c, new_ballot, sent_packets) || exists |sent_packets| LNewInstance(s, c, s, s_, c, sent_packets)))))))))))
}

} // verus!
