// Auto-generated by verus-transpiler
// DO NOT EDIT MANUALLY

use std::collections::HashSet;
use vstd::prelude::*;

verus! {

#[derive(Clone)]
pub struct CConstants {
    pub ElectionMessage: i64,
    pub Constants: i64,
    pub State: i64,
}

impl CConstants {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CConstants {
    type V = LConstants;

    open spec fn view(&self) -> LConstants {
        LConstants {
            ElectionMessage: self.ElectionMessage as int,
            Constants: self.Constants as int,
            State: self.State as int,
        }
    }
}

#[derive(Clone)]
pub struct CRecord {
    pub leader: i64,
    pub responder: i64,
    pub sender: i64,
}

impl CRecord {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CRecord {
    type V = LRecord;

    open spec fn view(&self) -> LRecord {
        LRecord {
            leader: self.leader as int,
            responder: self.responder as int,
            sender: self.sender as int,
        }
    }
}

#[derive(Clone)]
pub struct CState {
}

impl CState {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CState {
    type V = LState;

    open spec fn view(&self) -> LState {
        LState {
        }
    }
}

pub exec fn CInit(s: &i64) -> (result: CConstants)
requires
    Set::<int>::empty() == Set::<int>::empty(),
    Carbitrary::<bool>() == false,
    Carbitrary::<int>() == 0,
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<bool>() == false,
    Carbitrary::<int>() == 0,
    Carbitrary::<bool>() == false,
    Carbitrary::<int>() == 0,
ensures
    result.well_formed(),
    LInit(result@, *s as int),
{
    assume(false);
    ((((((((HashSet::new() == HashSet::new()) && (Carbitrary::<bool>() == false)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<bool>() == false)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<bool>() == false)) && (Carbitrary::<int>() == 0))

}

pub exec fn CDetectFailure(s: &CState, c: &CConstants, node: &i64, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Set::<int>::empty()@.contains(*node as int),
    Carbitrary::<bool>() == true,
    !Set::<int>::empty()@.contains(Carbitrary::<int>()),
    Set::<int>::empty() == Set::<int>::empty().union(set![node]),
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == *node,
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    sent_packets == Carbitrary::<Seq<int>>(),
ensures
    result.well_formed(),
    LDetectFailure(s@, result@, c@, *node as int, sent_packets@),
{
    assume(false);
    (((((((((((contains(&HashSet::new(), node) && (Carbitrary::<bool>() == true)) && !contains(&HashSet::new(), &Carbitrary::<int>())) && (HashSet::new() ==     let mut __hs = HashSet::new().clone();
    __hs.insert(*node);
    __hs
)) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == *node)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (sent_packets == Carbitrary::<Seq<int>>()))

}

pub exec fn CStartElection(s: &CState, c: &CConstants, node: &i64, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Set::<int>::empty()@.contains(*node as int),
    Set::<int>::empty() == Set::<int>::empty().union(set![node]),
    Carbitrary::<bool>() == false,
    Carbitrary::<int>() == 0,
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == *node,
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    sent_packets == Carbitrary::<Seq<int>>(),
ensures
    result.well_formed(),
    LStartElection(s@, result@, c@, *node as int, sent_packets@),
{
    assume(false);
    (((((((((contains(&HashSet::new(), node) && (HashSet::new() ==     let mut __hs = HashSet::new().clone();
    __hs.insert(*node);
    __hs
)) && (Carbitrary::<bool>() == false)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == *node)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (sent_packets == Carbitrary::<Seq<int>>()))

}

pub exec fn CSendAnswer(s: &CState, c: &CConstants, node: &i64, sender: &i64, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Set::<int>::empty()@.contains(*node as int),
    (*node > *sender),
    Set::<int>::empty() == Set::<int>::empty().union(set![node]),
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == Carbitrary::<int>(),
ensures
    result.well_formed(),
    LSendAnswer(s@, result@, c@, *node as int, *sender as int, sent_packets@),
{
    assume(false);
    ((((contains(&HashSet::new(), node) && (*node > *sender)) && (HashSet::new() ==     let mut __hs = HashSet::new().clone();
    __hs.insert(*node);
    __hs
)) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == Carbitrary::<int>()))

}

pub exec fn CReceiveAnswer(s: &CState, c: &CConstants, node: &i64, responder: &i64, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Set::<int>::empty()@.contains(*node as int),
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == *node,
    Carbitrary::<bool>() == false,
    Carbitrary::<int>() == 0,
    Set::<int>::empty() == Set::<int>::empty().difference(set![node]),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    sent_packets == Seq::<int>::empty(),
ensures
    result.well_formed(),
    LReceiveAnswer(s@, result@, c@, *node as int, *responder as int, sent_packets@),
{
    assume(false);
    (((((((((((contains(&HashSet::new(), node) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == *node)) && (Carbitrary::<bool>() == false)) && (Carbitrary::<int>() == 0)) && (HashSet::new() ==     let mut __hs = HashSet::new().clone();
    __hs.remove(&*node);
    __hs
)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (sent_packets == vec![]))

}

pub exec fn CSendCoordinator(s: &CState, c: &CConstants, node: &i64, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Set::<int>::empty()@.contains(*node as int),
    Set::<int>::empty()@.contains(*node as int),
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == *node,
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == *node,
    Set::<int>::empty() == Set::<int>::empty().difference(set![node]),
    Carbitrary::<bool>() == false,
    Carbitrary::<int>() == 0,
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    sent_packets == Carbitrary::<Seq<int>>(),
ensures
    result.well_formed(),
    LSendCoordinator(s@, result@, c@, *node as int, sent_packets@),
{
    assume(false);
    ((((((((((((contains(&HashSet::new(), node) && contains(&HashSet::new(), node)) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == *node)) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == *node)) && (HashSet::new() ==     let mut __hs = HashSet::new().clone();
    __hs.remove(&*node);
    __hs
)) && (Carbitrary::<bool>() == false)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (sent_packets == Carbitrary::<Seq<int>>()))

}

pub exec fn CReceiveCoordinator(s: &CState, c: &CConstants, node: &i64, leader: &i64, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Set::<int>::empty()@.contains(*node as int),
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == *leader,
    Set::<int>::empty() == Set::<int>::empty().difference(set![node]),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    sent_packets == Seq::<int>::empty(),
ensures
    result.well_formed(),
    LReceiveCoordinator(s@, result@, c@, *node as int, *leader as int, sent_packets@),
{
    assume(false);
    (((((((((contains(&HashSet::new(), node) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == *leader)) && (HashSet::new() ==     let mut __hs = HashSet::new().clone();
    __hs.remove(&*node);
    __hs
)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (sent_packets == vec![]))

}

pub exec fn CNodeFail(s: &CState, c: &CConstants, node: &i64, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Set::<int>::empty()@.contains(*node as int),
    Set::<int>::empty() == Set::<int>::empty().difference(set![node]),
    Set::<int>::empty() == Set::<int>::empty().difference(set![node]),
    Carbitrary::<bool>() == If { cond: Binary(Call { func: Path { segments: ["arbitrary"] }, args: [] }, And, Eq(Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] }, Ident("node"))), then_branch: Literal(Bool(false)), else_branch: Some(Binary(Call { func: Path { segments: ["arbitrary"] }, args: [] }, And, Eq(Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] }, Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] }))) },
ensures
    result.well_formed(),
    LNodeFail(s@, result@, c@, *node as int, sent_packets@),
{
    assume(false);
    (((contains(&HashSet::new(), node) && (HashSet::new() ==     let mut __hs = HashSet::new().clone();
    __hs.remove(&*node);
    __hs
)) && (HashSet::new() ==     let mut __hs = HashSet::new().clone();
    __hs.remove(&*node);
    __hs
)) && (Carbitrary::<bool>() == if (Carbitrary() && (Carbitrary::<int>() == *node)) {
        false
    } else {
        (Carbitrary() && (Carbitrary::<int>() == Carbitrary::<int>()))
    }))

}

// TRANSLATE-TODO: not functionalizable: Exists quantifier with 2 variables (node, sent_packets) not supported (only single-variable exists can be converted to executable code)
#[verifier(external_body)]
pub exec fn CNext(s: &CState, c: &CConstants) -> (result: CState)
ensures
    result.well_formed(),
    LNext(s@, result@, c@),
{
    unimplemented!()
}

} // verus!
