// Auto-generated by verus-transpiler
// DO NOT EDIT MANUALLY

use crate::common::collections::hashsets::clone_hashset;
use crate::generated::ChainReplication::types_gen::*;
use crate::protocol::ChainReplication::chain::*;
use crate::protocol::ChainReplication::types::*;
use std::collections::HashSet;
use vstd::prelude::*;
use vstd::set::*;
use vstd::set_lib::*;

verus! {

/// Helper proof: mapping an injective function over an empty set yields an empty set.
proof fn lemma_empty_set_map()
ensures
    Set::<u64>::empty().map(|x: u64| x as int) =~= Set::<int>::empty(),
{
    let f = |x: u64| x as int;
    let s = Set::<u64>::empty().map(f);
    assert forall|y: int| !(#[trigger] s.contains(y)) by {
    }
}

/// Helper proof: removing an element commutes with mapping for injective functions.
proof fn lemma_set_map_remove_commute(s: Set<u64>, elt: u64)
ensures
    s.remove(elt).map(|x: u64| x as int) =~= s.map(|x: u64| x as int).remove(elt as int),
{
    let f = |x: u64| x as int;
    let lhs = s.remove(elt).map(f);
    let rhs = s.map(f).remove(f(elt));
    assert forall|y: int| (#[trigger] lhs.contains(y)) implies rhs.contains(y) by {
        let x = choose|x: u64| s.remove(elt).contains(x) && f(x) == y;
        assert(s.contains(x));
        assert(x != elt);
        assert(f(x) != f(elt));
        assert(s.map(f).contains(y));
    }
    assert forall|y: int| (#[trigger] rhs.contains(y)) implies lhs.contains(y) by {
        let x = choose|x: u64| s.contains(x) && f(x) == y;
        assert(y != f(elt));
        assert(f(x) != f(elt));
        assert(x != elt);
        assert(s.remove(elt).contains(x));
    }
}

/// Helper proof: mapping over an empty Seq yields an empty Seq.
proof fn lemma_empty_seq_map()
ensures
    Seq::<u64>::empty().map(|i: int, v: u64| v as int) =~= Seq::<int>::empty(),
{
}

/// Helper proof: push commutes with Seq::map for index-ignoring functions.
proof fn lemma_seq_push_map_commute(s: Seq<u64>, x: u64)
ensures
    s.push(x).map(|i: int, v: u64| v as int) =~= s.map(|i: int, v: u64| v as int).push(x as int),
{
}


/// Helper: clone CNodeRole preserving view (workaround for missing derive Clone spec).
fn clone_role(r: &CNodeRole) -> (res: CNodeRole)
ensures
    res@ == r@,
    res.valid() == r.valid(),
{
    match r {
        CNodeRole::Head => CNodeRole::Head,
        CNodeRole::Middle => CNodeRole::Middle,
        CNodeRole::Tail => CNodeRole::Tail,
    }
}


pub exec fn CInit(c: &CConstants) -> (result: CState)
requires
    c.valid(),
    c.chain_len >= 2,
    c.node_id < c.chain_len,
ensures
    result.valid(),
    LInit(result@, c@),
{
    let result = CState {
        history: vec![],
        pending_sent: HashSet::new(),
        committed_count: 0u64,
        obj_value: 0u64,
        role: if (c.node_id == 0) {
            CNodeRole::Head
        } else {
            if (c.node_id == (c.chain_len - 1)) {
                CNodeRole::Tail
            } else {
                CNodeRole::Middle
            }
        },
    };
    proof {
        lemma_empty_set_map();
        lemma_empty_seq_map();
    }
    result

}

pub exec fn CHeadReceiveWrite(s: &CState, c: &CConstants, value: &u64) -> (result: CState)
requires
    s.valid(),
    c.valid(),
    s.role is Head,
    !s@.pending_sent.contains(*value as int),
ensures
    result.valid(),
    LHeadReceiveWrite(s@, result@, c@, *value as int),
{
    let result = {
        let mut __history = s.history.clone();
        __history.push(*value);
        let mut __pending_sent = clone_hashset(&s.pending_sent);
        __pending_sent.insert(*value);
        CState {
            role: clone_role(&s.role),
            history: __history,
            pending_sent: __pending_sent,
            committed_count: s.committed_count,
            obj_value: s.obj_value,
        }
    };
    proof {
        broadcast use Set::lemma_set_map_insert_commute;
        lemma_seq_push_map_commute(s.history@, *value);
    }
    result

}

pub exec fn CReceiveUpdate(s: &CState, c: &CConstants, value: &u64) -> (result: CState)
requires
    s.valid(),
    c.valid(),
    (s.role is Middle || s.role is Tail),
    !s@.history.contains(*value as int),
ensures
    result.valid(),
    LReceiveUpdate(s@, result@, c@, *value as int),
{
    let result = {
        let mut __history = s.history.clone();
        __history.push(*value);
        let mut __pending_sent = clone_hashset(&s.pending_sent);
        match &s.role {
            CNodeRole::Middle => {
                __pending_sent.insert(*value);
                
            },
            _ => {},
        };
        CState {
            role: clone_role(&s.role),
            history: __history,
            pending_sent: __pending_sent,
            committed_count: s.committed_count,
            obj_value: s.obj_value,
        }
    };
    proof {
        broadcast use Set::lemma_set_map_insert_commute;
        lemma_seq_push_map_commute(s.history@, *value);
    }
    result

}

pub exec fn CTailCommit(s: &CState, c: &CConstants, value: &u64) -> (result: CState)
requires
    s.valid(),
    c.valid(),
    s.role is Tail,
    s@.history.contains(*value as int),
    s.committed_count < u64::MAX,
ensures
    result.valid(),
    LTailCommit(s@, result@, c@, *value as int),
{
CState {
        role: clone_role(&s.role),
        history: s.history.clone(),
        pending_sent: clone_hashset(&s.pending_sent),
        committed_count: (s.committed_count + 1),
        obj_value: *value,
    }
}

pub exec fn CReceiveAck(s: &CState, c: &CConstants, value: &u64) -> (result: CState)
requires
    s.valid(),
    c.valid(),
    (s.role is Head || s.role is Middle),
    s@.pending_sent.contains(*value as int),
ensures
    result.valid(),
    LReceiveAck(s@, result@, c@, *value as int),
{
    let result = {
        let mut __pending_sent = clone_hashset(&s.pending_sent);
        __pending_sent.remove(value);
        CState {
            role: clone_role(&s.role),
            history: s.history.clone(),
            pending_sent: __pending_sent,
            committed_count: s.committed_count,
            obj_value: s.obj_value,
        }
    };
    proof {
        lemma_set_map_remove_commute(s.pending_sent@, *value);
    }
    result

}

pub exec fn CClientRead(s: &CState, c: &CConstants) -> (result: CState)
requires
    s.valid(),
    c.valid(),
    s.role is Tail,
ensures
    result.valid(),
    LClientRead(s@, result@, c@),
{
s.clone()
}

} // verus!
