//! Generated from TLA+ module: Acceptor
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Acceptor module
pub struct LRecord {
    pub constants: int,
    pub last_checkpointed_operation: int,
    pub log_truncation_point: int,
    pub max_bal: int,
    pub proposer_id: int,
    pub seqno: int,
    pub votes: int,
}

/// State for Acceptor module
pub struct LState {
}

/// Constants for the module
pub struct LConstants {
    pub Votes: int,
    pub ReplicaConstants: int,
    pub OperationNumber: int,
    pub Acceptor: int,
    pub Configuration: int,
    pub Vote: int,
    pub RslPacket: int,
}


/// Acceptor operator
pub open spec fn LAcceptor(c: LConstants) -> { votes: int, log_truncation_point: int, constants: int, max_bal: int, last_checkpointed_operation: int } {
    LRecord { constants: c.ReplicaConstants, last_checkpointed_operation: Seq(c.OperationNumber), log_truncation_point: c.OperationNumber, max_bal: Ballot, proposer_id: 0int, seqno: 0int, votes: c.Votes }
}

/// IsLogTruncationPointValid operator
pub open spec fn LIsLogTruncationPointValid(s: LState, c: LConstants, log_truncation_point: int, last_checkpointed_operation: int, config: int) -> int {
    IsNthHighestValueInSequence(log_truncation_point, last_checkpointed_operation, MinQuorumSize(config))
}

/// RemoveVotesBeforeLogTruncationPoint operator
pub open spec fn LRemoveVotesBeforeLogTruncationPoint(s: LState, c: LConstants, votes: int, votes_: int, log_truncation_point: int) -> bool {
    forall |opn| c.OperationNumber.contains(opn) ==> ((votes_.dom().contains(opn) ==> (votes.dom().contains(opn) && (votes_[opn] == votes[opn]))) && forall |opn| c.OperationNumber.contains(opn) ==> (((opn < log_truncation_point) ==> votes_.dom().contains(!(opn))) && forall |opn| c.OperationNumber.contains(opn) ==> (((opn >= log_truncation_point) && votes.dom().contains(opn)) ==> votes_.dom().contains(opn))))
}

/// AddVoteAndRemoveOldOnes operator
pub open spec fn LAddVoteAndRemoveOldOnes(s: LState, c: LConstants, votes: int, votes_: int, new_opn: int, new_vote: int, log_truncation_point: int) -> bool {
    forall |opn| c.OperationNumber.contains(opn) ==> ((votes_.dom().contains(opn) <==> ((opn >= log_truncation_point) && (votes.dom().contains(opn) || (opn == new_opn)))) && forall |opn| c.OperationNumber.contains(opn) ==> (votes_.dom().contains(opn) ==> (votes_[opn] == if (opn == new_opn) { new_vote } else { votes[opn] })))
}

/// AcceptorInit operator
pub open spec fn LAcceptorInit(s: LState, c: LConstants, a: int) -> bool {
    (((((a.constants == c) && (a.max_bal == LRecord { constants: 0int, last_checkpointed_operation: 0int, log_truncation_point: 0int, max_bal: 0int, proposer_id: 0, seqno: 0, votes: 0int })) && (a.votes == seq![])) && (a.last_checkpointed_operation.len() == c.all.config.replica_ids.len())) && forall |idx| int.contains(idx) ==> ((((0 <= idx) && (idx < a.last_checkpointed_operation.len())) ==> (a.last_checkpointed_operation[idx] == 0)) && (a.log_truncation_point == 0)))
}

/// AcceptorProcess1a operator
pub open spec fn LAcceptorProcess1a(s: LState, c: LConstants, s_: int, inp: int, sent_packets: int) -> bool {
    {
    let m = inp.msg;
    {
    let bal = inp.msg.bal_1a;
    if ((s.constants.all.config.replica_ids.contains(inp.src) && BalLt(s.max_bal, bal)) && ReplicaConstantsValid(s.constants)) { ((sent_packets == seq![{ src: s.constants.all.config.replica_ids[s.constants.my_index], dst: inp.src, msg: { bal_1b: bal, log_truncation_point: s.log_truncation_point, votes: s.votes } }]) && (s_ == LRecord { constants: s.constants, last_checkpointed_operation: s.last_checkpointed_operation, log_truncation_point: s.log_truncation_point, max_bal: bal, proposer_id: 0int, seqno: 0int, votes: s.votes })) } else { ((s_ == s) && (sent_packets == seq![])) }
}
}
}

/// AcceptorProcess2a operator
pub open spec fn LAcceptorProcess2a(s: LState, c: LConstants, s_: int, inp: int, sent_packets: int) -> bool {
    {
    let m = inp.msg;
    {
    let newLogTruncationPoint = if (((inp.msg.opn_2a - s.constants.all.params.max_log_length) + 1) > s.log_truncation_point) { ((inp.msg.opn_2a - s.constants.all.params.max_log_length) + 1) } else { s.log_truncation_point };
    (((BroadcastToEveryone(s.constants.all.config, s.constants.my_index, { bal_2b: m.bal_2a, opn_2b: m.opn_2a, val_2b: m.val_2a }, sent_packets) && (s_.max_bal == m.bal_2a)) && (s_.log_truncation_point == newLogTruncationPoint)) && if (s.log_truncation_point <= m.opn_2a) { LAddVoteAndRemoveOldOnes(s, c)(s.votes, s_.votes, m.opn_2a, { max_value_bal: m.bal_2a, max_val: m.val_2a }, newLogTruncationPoint) } else { (((s_.votes == s.votes) && (s_.constants == s.constants)) && (s_.last_checkpointed_operation == s.last_checkpointed_operation)) })
}
}
}

/// AcceptorProcessHeartbeat operator
pub open spec fn LAcceptorProcessHeartbeat(s: LState, c: LConstants, s_: int, inp: int) -> bool {
    if s.constants.all.config.replica_ids.contains(inp.src) { {
    let sender_index = GetReplicaIndex(inp.src, s.constants.all.config);
    if (((0 <= sender_index) && (sender_index < s.last_checkpointed_operation.len())) && (inp.msg.opn_ckpt > s.last_checkpointed_operation[sender_index])) { (((((s_.last_checkpointed_operation == update(s.last_checkpointed_operation, sender_index, inp.msg.opn_ckpt)) && (s_.constants == s.constants)) && (s_.max_bal == s.max_bal)) && (s_.votes == s.votes)) && (s_.log_truncation_point == s.log_truncation_point)) } else { (s_ == s) }
} } else { (s_ == s) }
}

/// AcceptorTruncateLog operator
pub open spec fn LAcceptorTruncateLog(s: LState, c: LConstants, s_: int, opn: int) -> bool {
    if (opn <= s.log_truncation_point) { (s_ == s) } else { ((s_ == LRecord { constants: s.constants, last_checkpointed_operation: s.last_checkpointed_operation, log_truncation_point: opn, max_bal: s.max_bal, proposer_id: 0int, seqno: 0int, votes: s_.votes }) && LRemoveVotesBeforeLogTruncationPoint(s, c)(s.votes, s_.votes, opn)) }
}

} // verus!
