//! Generated from TLA+ module: Acceptor
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Acceptor module
pub struct LRecord {
    pub bal_1b: int,
    pub bal_2b: int,
    pub constants: int,
    pub dst: int,
    pub last_checkpointed_operation: int,
    pub log_truncation_point: int,
    pub max_bal: int,
    pub max_val: int,
    pub max_value_bal: int,
    pub msg: int,
    pub opn_2b: int,
    pub proposer_id: int,
    pub seqno: int,
    pub src: int,
    pub val_2b: int,
    pub votes: int,
}

/// State for Acceptor module
pub type LState = LRecord;

/// Constants for the module
pub struct LConstants {
    pub Votes: int,
    pub ReplicaConstants: int,
    pub OperationNumber: Set<int>,
    pub Acceptor: int,
    pub Configuration: int,
    pub Vote: int,
    pub RslPacket: int,
}


/// Acceptor operator
pub open spec fn LAcceptor(c: LConstants) -> LRecord {
    LRecord { bal_1b: 0int, bal_2b: 0int, constants: arbitrary::<int>(), dst: 0int, last_checkpointed_operation: arbitrary(), log_truncation_point: arbitrary::<int>(), max_bal: 8530703455int, max_val: 0int, max_value_bal: 0int, msg: 0int, opn_2b: 0int, proposer_id: 0int, seqno: 0int, src: 0int, val_2b: 0int, votes: arbitrary::<int>() }
}

/// IsLogTruncationPointValid operator
pub open spec fn LIsLogTruncationPointValid(c: LConstants, log_truncation_point: int, last_checkpointed_operation: int, config: int) -> int {
    arbitrary()
}

/// RemoveVotesBeforeLogTruncationPoint operator
pub open spec fn LRemoveVotesBeforeLogTruncationPoint(c: LConstants, votes: Map<int, int>, votes_: Map<int, int>, log_truncation_point: int) -> bool {
    forall |opn| c.OperationNumber.contains(opn) ==> ((votes_.dom().contains(opn) ==> (votes.dom().contains(opn) && (votes_[opn] == votes[opn]))) && forall |opn| c.OperationNumber.contains(opn) ==> (((opn < log_truncation_point) ==> !votes_.dom().contains(opn)) && forall |opn| c.OperationNumber.contains(opn) ==> (((opn >= log_truncation_point) && votes.dom().contains(opn)) ==> votes_.dom().contains(opn))))
}

/// AddVoteAndRemoveOldOnes operator
pub open spec fn LAddVoteAndRemoveOldOnes(c: LConstants, votes: Map<int, int>, votes_: Map<int, int>, new_opn: int, new_vote: int, log_truncation_point: int) -> bool {
    forall |opn| c.OperationNumber.contains(opn) ==> ((votes_.dom().contains(opn) <==> ((opn >= log_truncation_point) && (votes.dom().contains(opn) || (opn == new_opn)))) && forall |opn| c.OperationNumber.contains(opn) ==> (votes_.dom().contains(opn) ==> (votes_[opn] == if (opn == new_opn) { new_vote } else { votes[opn] })))
}

/// AcceptorInit operator
pub open spec fn LAcceptorInit(c: LConstants, a: int) -> bool {
    (((((arbitrary::<LConstants>() == c) && (arbitrary::<LRecord>() == LRecord { bal_1b: 0int, bal_2b: 0int, constants: 0int, dst: 0int, last_checkpointed_operation: 0int, log_truncation_point: 0int, max_bal: 0int, max_val: 0int, max_value_bal: 0int, msg: 0int, opn_2b: 0int, proposer_id: 0, seqno: 0, src: 0int, val_2b: 0int, votes: 0int })) && (arbitrary::<Seq<int>>() == Seq::<int>::empty())) && ((arbitrary::<Seq<int>>().len() as int) == (arbitrary::<Seq<int>>().len() as int))) && forall |idx: int| ((((0 <= idx) && (idx < (arbitrary::<Seq<int>>().len() as int))) ==> (arbitrary::<Seq<int>>()[idx] == 0)) && (arbitrary::<int>() == 0)))
}

/// AcceptorProcess1a operator
pub open spec fn LAcceptorProcess1a(s: LState, s_: LState, c: LConstants, inp: int, sent_packets: Seq<int>) -> bool {
    {
    let m: int = arbitrary();
    {
    let bal: int = arbitrary();
    if ((Set::<int>::empty().contains(arbitrary::<int>()) && arbitrary()) && arbitrary()) { ((sent_packets == arbitrary::<Seq<int>>()) && (s_ == LRecord { bal_1b: 0int, bal_2b: 0int, constants: arbitrary(), dst: 0int, last_checkpointed_operation: arbitrary(), log_truncation_point: arbitrary(), max_bal: bal, max_val: 0int, max_value_bal: 0int, msg: 0int, opn_2b: 0int, proposer_id: 0int, seqno: 0int, src: 0int, val_2b: 0int, votes: arbitrary() })) } else { ((s_ == s) && (sent_packets == Seq::<int>::empty())) }
}
}
}

/// AcceptorProcess2a operator
pub open spec fn LAcceptorProcess2a(s: LState, s_: LState, c: LConstants, inp: int, sent_packets: int) -> bool {
    {
    let m: int = arbitrary();
    {
    let newLogTruncationPoint = if (((arbitrary::<int>() - arbitrary::<int>()) + 1) > arbitrary::<int>()) { ((arbitrary::<int>() - arbitrary::<int>()) + 1) } else { arbitrary() };
    (((arbitrary() && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == newLogTruncationPoint)) && if (arbitrary::<int>() <= arbitrary::<int>()) { LAddVoteAndRemoveOldOnes(c, arbitrary::<Map<int, int>>(), arbitrary::<Map<int, int>>(), arbitrary::<int>(), arbitrary::<int>(), newLogTruncationPoint) } else { (((arbitrary::<int>() == arbitrary::<int>()) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) })
}
}
}

/// AcceptorProcessHeartbeat operator
pub open spec fn LAcceptorProcessHeartbeat(s: LState, s_: LState, c: LConstants, inp: int) -> bool {
    if Set::<int>::empty().contains(arbitrary::<int>()) { {
    let sender_index: int = arbitrary();
    if (((0 <= sender_index) && (sender_index < (arbitrary::<Seq<int>>().len() as int))) && (arbitrary::<int>() > arbitrary::<Seq<int>>()[sender_index])) { (((((arbitrary::<Seq<int>>() == arbitrary::<Seq<int>>().update(sender_index, arbitrary())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) } else { (s_ == s) }
} } else { (s_ == s) }
}

/// AcceptorTruncateLog operator
pub open spec fn LAcceptorTruncateLog(s: LState, s_: LState, c: LConstants, opn: int) -> bool {
    if (opn <= arbitrary::<int>()) { (s_ == s) } else { ((s_ == LRecord { bal_1b: 0int, bal_2b: 0int, constants: arbitrary(), dst: 0int, last_checkpointed_operation: arbitrary(), log_truncation_point: opn, max_bal: arbitrary(), max_val: 0int, max_value_bal: 0int, msg: 0int, opn_2b: 0int, proposer_id: 0int, seqno: 0int, src: 0int, val_2b: 0int, votes: arbitrary() }) && LRemoveVotesBeforeLogTruncationPoint(c, arbitrary::<Map<int, int>>(), arbitrary::<Map<int, int>>(), opn)) }
}

} // verus!
