//! Generated from TLA+ module: Broadcast
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Broadcast module
pub struct LRecord {
    pub dst: int,
    pub msg: int,
    pub src: int,
}

/// State for Broadcast module
pub struct LState {
}

/// Constants for the module
pub struct LConstants {
    pub RslMessage: int,
    pub Configuration: int,
    pub AbstractEndPoint: int,
    pub RslPacket: int,
}


/// BroadcastToEveryone operator
pub open spec fn LBroadcastToEveryone(c: LConstants, myidx: int, m: int, sent_packets: Seq<LRecord>) -> bool {
    (((((sent_packets.len() as int) == (arbitrary::<Seq<int>>().len() as int)) && (0 <= myidx)) && (myidx < (arbitrary::<Seq<int>>().len() as int))) && forall |idx: int| (((0 <= idx) && (idx < (sent_packets.len() as int))) ==> (sent_packets[idx] == LRecord { dst: arbitrary::<Seq<int>>()[idx], msg: m, src: arbitrary::<Seq<int>>()[myidx] })))
}

/// BuildLBroadcast operator
pub open spec fn LBuildLBroadcast(c: LConstants, src: int, dsts: Seq<int>, m: int) -> Seq<int> {
    if ((dsts.len() as int) == 0) { Seq::<int>::empty() } else { (arbitrary::<Seq<int>>() + LBuildLBroadcast(c, src, dsts.skip(1), m)) }
}

} // verus!
