//! Generated from TLA+ module: Broadcast
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Broadcast module
pub struct LRecord {
    pub dst: int,
    pub msg: int,
    pub src: int,
}

/// State for Broadcast module
pub struct LState {
}

/// Constants for the module
pub struct LConstants {
    pub RslMessage: int,
    pub Configuration: int,
    pub AbstractEndPoint: int,
    pub RslPacket: int,
}


/// BroadcastToEveryone operator
pub open spec fn LBroadcastToEveryone(s: LState, c: LConstants, myidx: int, m: int, sent_packets: int) -> bool {
    ((((sent_packets.len() == arbitrary().len()) && (0 <= myidx)) && (myidx < arbitrary().len())) && forall |idx| (((0 <= idx) && (idx < sent_packets.len())) ==> (sent_packets[idx] == LRecord { dst: arbitrary()[idx], msg: m, src: arbitrary()[myidx] })))
}

/// BuildLBroadcast operator
pub open spec fn LBuildLBroadcast(s: LState, c: LConstants, src: int, dsts: int, m: int) -> () {
    if (dsts.len() == 0) { seq![] } else { (seq![LRecord { dst: dsts[0], msg: m, src: src }] + LBuildLBroadcast(s, c, src, dsts.skip(1), m)) }
}

} // verus!
