//! Generated from TLA+ module: Constants
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Constants module
pub struct LRecord {
    pub all: int,
    pub config: int,
    pub my_index: int,
    pub params: int,
}

/// State for Constants module
pub struct LState {
}

/// Constants for the module
pub struct LConstants {
    pub ReplicaConstants: int,
}


/// Constants operator
pub open spec fn LConstants(c: LConstants) -> LRecord {
    LRecord { all: 0int, config: 6077433849int, my_index: 0int, params: 5876601465int }
}

/// ReplicaConstants operator
pub open spec fn LReplicaConstants(c: LConstants) -> LRecord {
    LRecord { all: arbitrary(), config: 0int, my_index: arbitrary(), params: 0int }
}

/// ReplicaConstantsValid operator
pub open spec fn LReplicaConstantsValid(s: LState, c: LConstants) -> bool {
    ((0 <= arbitrary::<int>()) && (arbitrary::<int>() < arbitrary().len()))
}

} // verus!
