//! Generated from TLA+ module: Distributed_system
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Distributed_system module
pub struct LRecord {
    pub actor: int,
    pub all: int,
    pub clients: int,
    pub constants: int,
    pub environment: int,
    pub ios: int,
    pub my_index: int,
    pub replicas: int,
}

/// State for Distributed_system module
pub struct LState {
}

/// Constants for the module
pub struct LConstants {
    pub AbstractEndPoint: int,
    pub RslState: int,
    pub Constants: int,
    pub RslIo: int,
}


/// RslState operator
pub open spec fn LRslState(c: LConstants) -> LRecord {
    LRecord { actor: 0int, all: 0int, clients: Seq(c.AbstractEndPoint), constants: c.Constants, environment: Environment, ios: 0int, my_index: 0int, replicas: Seq(Scheduler) }
}

/// RslMapsComplete operator
pub open spec fn LRslMapsComplete(s: LState, c: LConstants, ps: int) -> bool {
    (ps.replicas.len() == ps.constants.config.replica_ids.len())
}

/// RslConstantsUnchanged operator
pub open spec fn LRslConstantsUnchanged(s: LState, c: LConstants, ps: int, ps_: int) -> bool {
    (((ps_.replicas.len() == ps.replicas.len()) && (ps_.clients == ps.clients)) && (ps_.constants == ps.constants))
}

/// RslInit operator
pub open spec fn LRslInit(s: LState, c: LConstants, con: int, ps: int) -> bool {
    (((((WellFormedLConfiguration(con.config) && WFLParameters(con.params)) && (ps.constants == con)) && Environment_Init(ps.environment)) && LRslMapsComplete(s, c, ps)) && forall |i| int.contains(i) ==> (((0 <= i) && (i < con.config.replica_ids.len())) ==> SchedulerInit(ps.replicas[i], LRecord { actor: 0int, all: con, clients: 0int, constants: 0int, environment: 0int, ios: 0int, my_index: i, replicas: 0int })))
}

/// RslNextCommon operator
pub open spec fn LRslNextCommon(s: LState, c: LConstants, ps: int, ps_: int) -> bool {
    ((LRslMapsComplete(s, c, ps) && LRslConstantsUnchanged(s, c, ps, ps_)) && Environment_Next(ps.environment, ps_.environment))
}

/// RslNextOneReplica operator
pub open spec fn LRslNextOneReplica(s: LState, c: LConstants, ps: int, ps_: int, idx: int, ios: int) -> bool {
    (((((LRslNextCommon(s, c, ps, ps_) && (0 <= idx)) && (idx < ps.constants.config.replica_ids.len())) && SchedulerNext(ps.replicas[idx], ps_.replicas[idx], ios)) && (ps.environment.nextStep == LRecord { actor: ps.constants.config.replica_ids[idx], all: 0int, clients: 0int, constants: 0int, environment: 0int, ios: ios, my_index: 0int, replicas: 0int })) && (ps_.replicas == update(ps.replicas, idx, ps_.replicas[idx])))
}

/// RslNextEnvironment operator
pub open spec fn LRslNextEnvironment(s: LState, c: LConstants, ps: int, ps_: int) -> bool {
    ((LRslNextCommon(s, c, ps, ps_) && (!(ps.environment.nextStep.tag) == LEnvStepHostIos)) && (ps_.replicas == ps.replicas))
}

/// RslNextOneExternal operator
pub open spec fn LRslNextOneExternal(s: LState, c: LConstants, ps: int, ps_: int, eid: int, ios: int) -> bool {
    (((LRslNextCommon(s, c, ps, ps_) && ps.constants.config.replica_ids.contains(!(eid))) && (ps.environment.nextStep == LRecord { actor: eid, all: 0int, clients: 0int, constants: 0int, environment: 0int, ios: ios, my_index: 0int, replicas: 0int })) && (ps_.replicas == ps.replicas))
}

/// RslNext operator
pub open spec fn LRslNext(s: LState, c: LConstants, ps: int, ps_: int) -> bool {
    exists |idx, ios| (int.contains(idx) && Seq(c.RslIo).contains(ios)) && (LRslNextOneReplica(s, c, ps, ps_, idx, ios) || exists |eid, ios| (c.AbstractEndPoint.contains(eid) && Seq(c.RslIo).contains(ios)) && (LRslNextOneExternal(s, c, ps, ps_, eid, ios) || LRslNextEnvironment(s, c, ps, ps_)))
}

} // verus!
