//! Generated from TLA+ module: Distributed_system
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Distributed_system module
pub struct LRecord {
    pub actor: int,
    pub all: int,
    pub clients: int,
    pub constants: int,
    pub environment: int,
    pub ios: int,
    pub my_index: int,
    pub replicas: int,
}

/// State for Distributed_system module
pub struct LState {
}

/// Constants for the module
pub struct LConstants {
    pub AbstractEndPoint: Set<int>,
    pub RslState: int,
    pub Constants: int,
    pub RslIo: int,
}


/// RslState operator
pub open spec fn LRslState(c: LConstants) -> LRecord {
    LRecord { actor: 0int, all: 0int, clients: arbitrary(), constants: c.Constants, environment: 7208647130int, ios: 0int, my_index: 0int, replicas: arbitrary() }
}

/// RslMapsComplete operator
pub open spec fn LRslMapsComplete(s: LState, c: LConstants, ps: int) -> bool {
    (arbitrary().len() == arbitrary().len())
}

/// RslConstantsUnchanged operator
pub open spec fn LRslConstantsUnchanged(s: LState, c: LConstants, ps: int, ps_: int) -> bool {
    (((arbitrary().len() == arbitrary().len()) && (arbitrary() == arbitrary())) && (arbitrary() == arbitrary()))
}

/// RslInit operator
pub open spec fn LRslInit(s: LState, c: LConstants, con: int, ps: int) -> bool {
    (((((arbitrary() && arbitrary()) && (arbitrary() == con)) && arbitrary()) && LRslMapsComplete(s, c, ps)) && forall |i| (((0 <= i) && (i < arbitrary().len())) ==> arbitrary()))
}

/// RslNextCommon operator
pub open spec fn LRslNextCommon(s: LState, c: LConstants, ps: int, ps_: int) -> bool {
    ((LRslMapsComplete(s, c, ps) && LRslConstantsUnchanged(s, c, ps, ps_)) && arbitrary())
}

/// RslNextOneReplica operator
pub open spec fn LRslNextOneReplica(s: LState, c: LConstants, ps: int, ps_: int, idx: int, ios: int) -> bool {
    (((((LRslNextCommon(s, c, ps, ps_) && (0 <= idx)) && (idx < arbitrary().len())) && arbitrary()) && (arbitrary() == LRecord { actor: arbitrary()[idx], all: 0int, clients: 0int, constants: 0int, environment: 0int, ios: ios, my_index: 0int, replicas: 0int })) && (arbitrary() == arbitrary().update(idx, arbitrary()[idx])))
}

/// RslNextEnvironment operator
pub open spec fn LRslNextEnvironment(s: LState, c: LConstants, ps: int, ps_: int) -> bool {
    ((LRslNextCommon(s, c, ps, ps_) && (!(arbitrary()) == 2375175031int)) && (arbitrary() == arbitrary()))
}

/// RslNextOneExternal operator
pub open spec fn LRslNextOneExternal(s: LState, c: LConstants, ps: int, ps_: int, eid: bool, ios: int) -> bool {
    (((LRslNextCommon(s, c, ps, ps_) && Set::<int>::empty().contains(!(eid))) && (arbitrary() == LRecord { actor: eid, all: 0int, clients: 0int, constants: 0int, environment: 0int, ios: ios, my_index: 0int, replicas: 0int })) && (arbitrary() == arbitrary()))
}

/// RslNext operator
pub open spec fn LRslNext(s: LState, c: LConstants, ps: int, ps_: int) -> bool {
    exists |idx, ios| (LRslNextOneReplica(s, c, ps, ps_, idx, ios) || exists |eid, ios| (c.AbstractEndPoint.contains(eid)) && (LRslNextOneExternal(s, c, ps, ps_, eid, ios) || LRslNextEnvironment(s, c, ps, ps_)))
}

} // verus!
