//! Generated from TLA+ module: Executor
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Executor module
pub struct LRecord {
    pub app: int,
    pub app_state: int,
    pub bal: int,
    pub bal_state_req: int,
    pub bal_state_supply: int,
    pub constants: int,
    pub dst: int,
    pub max_bal_reflected: int,
    pub msg: int,
    pub next_op_to_execute: int,
    pub opn_state_req: int,
    pub opn_state_supply: int,
    pub ops_complete: int,
    pub proposer_id: int,
    pub reply: int,
    pub reply_cache: int,
    pub seqno: int,
    pub seqno_reply: int,
    pub src: int,
    pub v: int,
}

/// State for Executor module
pub struct LState {
}

/// Constants for the module
pub struct LConstants {
    pub OperationNumber: int,
    pub AbstractEndPoint: int,
    pub RequestBatch: int,
    pub ReplyCache: int,
    pub ReplicaConstants: int,
    pub Reply: int,
    pub RslPacket: int,
    pub Request: int,
    pub Ballot: int,
    pub Executor: int,
}


/// Executor operator
pub open spec fn LExecutor(c: LConstants) -> LRecord {
    LRecord { app: 2467764049int, app_state: 0int, bal: 0int, bal_state_req: 0int, bal_state_supply: 0int, constants: c.ReplicaConstants, dst: 0int, max_bal_reflected: c.Ballot, msg: 0int, next_op_to_execute: LOutstandingOperation(c), opn_state_req: 0int, opn_state_supply: 0int, ops_complete: int, proposer_id: 0int, reply: 0int, reply_cache: c.ReplyCache, seqno: 0int, seqno_reply: 0int, src: 0int, v: 0int }
}

/// OutstandingOperation operator
pub open spec fn LOutstandingOperation(c: LConstants) -> Set<int> {
    set![6764822447int, 4689272130int]
}

/// ExecutorInit operator
pub open spec fn LExecutorInit(s: LState, c: LConstants) -> bool {
    ((((((s.constants == c) && (s.app == 2250457826int)) && (s.ops_complete == 0)) && (s.max_bal_reflected == LRecord { app: 0int, app_state: 0int, bal: 0int, bal_state_req: 0int, bal_state_supply: 0int, constants: 0int, dst: 0int, max_bal_reflected: 0int, msg: 0int, next_op_to_execute: 0int, opn_state_req: 0int, opn_state_supply: 0int, ops_complete: 0int, proposer_id: 0, reply: 0int, reply_cache: 0int, seqno: 0, seqno_reply: 0int, src: 0int, v: 0int })) && (s.next_op_to_execute == seq![])) && (s.reply_cache == seq![]))
}

/// ExecutorGetDecision operator
pub open spec fn LExecutorGetDecision(s: LState, c: LConstants, s_: int, bal: int, opn: int, v: int) -> bool {
    (s_ == LRecord { app: s.app, app_state: 0int, bal: 0int, bal_state_req: 0int, bal_state_supply: 0int, constants: s.constants, dst: 0int, max_bal_reflected: s.max_bal_reflected, msg: 0int, next_op_to_execute: LRecord { app: 0int, app_state: 0int, bal: bal, bal_state_req: 0int, bal_state_supply: 0int, constants: 0int, dst: 0int, max_bal_reflected: 0int, msg: 0int, next_op_to_execute: 0int, opn_state_req: 0int, opn_state_supply: 0int, ops_complete: 0int, proposer_id: 0int, reply: 0int, reply_cache: 0int, seqno: 0int, seqno_reply: 0int, src: 0int, v: v }, opn_state_req: 0int, opn_state_supply: 0int, ops_complete: s.ops_complete, proposer_id: 0int, reply: 0int, reply_cache: s.reply_cache, seqno: 0int, seqno_reply: 0int, src: 0int, v: 0int })
}

/// GetPacketsFromReplies operator
pub open spec fn LGetPacketsFromReplies(s: LState, c: LConstants, me: int, requests: int, replies: int) -> () {
    if (requests.len() == 0) { seq![] } else { (seq![LRecord { app: 0int, app_state: 0int, bal: 0int, bal_state_req: 0int, bal_state_supply: 0int, constants: 0int, dst: requests[0].client, max_bal_reflected: 0int, msg: LRecord { app: 0int, app_state: 0int, bal: 0int, bal_state_req: 0int, bal_state_supply: 0int, constants: 0int, dst: 0int, max_bal_reflected: 0int, msg: 0int, next_op_to_execute: 0int, opn_state_req: 0int, opn_state_supply: 0int, ops_complete: 0int, proposer_id: 0int, reply: arbitrary()[0].reply, reply_cache: 0int, seqno: 0int, seqno_reply: requests[0].seqno, src: 0int, v: 0int }, next_op_to_execute: 0int, opn_state_req: 0int, opn_state_supply: 0int, ops_complete: 0int, proposer_id: 0int, reply: 0int, reply_cache: 0int, seqno: 0int, seqno_reply: 0int, src: me, v: 0int }] + LGetPacketsFromReplies(s, c, me, requests.drop_first(), arbitrary().drop_first())) }
}

/// ClientsInReplies operator
pub open spec fn LClientsInReplies(s: LState, c: LConstants, replies: int) -> () {
    if (arbitrary().len() == 0) { seq![] } else { LClientsInReplies(s, c, arbitrary().drop_first()).insert(arbitrary()[0].client, arbitrary()[0]) }
}

/// RepliesAreReplyType operator
pub open spec fn LRepliesAreReplyType(s: LState, c: LConstants, replies: int) -> bool {
    forall |p| c.RslPacket.contains(p) ==> (arbitrary().contains(p) ==> (p.msg.tag == 1959719083int))
}

/// UpdateNewCache operator
pub open spec fn LUpdateNewCache(s: LState, c: LConstants, c_: int, replies: int) -> bool {
    {
    let nc = LClientsInReplies(s, c, arbitrary());
    forall |client| c.AbstractEndPoint.contains(client) ==> ((c_.dom().contains(client) ==> ((c.dom().contains(client) && (c_[client] == c[client])) || exists |req_idx| ((((0 <= req_idx) && (req_idx < arbitrary().len())) && (arbitrary()[req_idx].client == client)) && (c_[client] == arbitrary()[req_idx])))) && forall |client| c.AbstractEndPoint.contains(client) ==> ((c_.dom().contains(client) <==> (nc.dom().contains(client) || c.dom().contains(client))) && forall |client| c.AbstractEndPoint.contains(client) ==> (c_.dom().contains(client) ==> (c_[client] == if c.dom().contains(client) { c[client] } else { (nc[client] && forall |client| c.AbstractEndPoint.contains(client) ==> ((nc.dom().contains(client) || c.dom().contains(client)) ==> (c_.dom().contains(client) && (c_[client] == if c.dom().contains(client) { c[client] } else { nc[client] })))) }))))
}
}

/// ExecutorExecute operator
pub open spec fn LExecutorExecute(s: LState, c: LConstants, s_: int, sent_packets: int) -> bool {
    {
    let batch = s.next_op_to_execute.v;
    {
    let temp = arbitrary();
    {
    let new_state = temp[1][(temp[1].len() - 1)];
    {
    let replies = temp[2];
    {
    let clients = LClientsInReplies(s, c, arbitrary());
    ((((s_.constants == s.constants) && (s_.app == arbitrary())) && (s_.ops_complete == (s.ops_complete + 1))) && (s_.max_bal_reflected == if arbitrary() { s.next_op_to_execute.bal } else { ((((s.max_bal_reflected && (s_.next_op_to_execute == seq![])) && LUpdateNewCache(s, c, s.reply_cache, s_.reply_cache, arbitrary())) && (sent_packets == LGetPacketsFromReplies(s, c, s.constants.all.config.replica_ids[s.constants.my_index], batch, arbitrary()))) && LRepliesAreReplyType(s, c, sent_packets)) }))
}
}
}
}
}
}

/// ExecutorProcessAppStateSupply operator
pub open spec fn LExecutorProcessAppStateSupply(s: LState, c: LConstants, s_: int, inp: int) -> bool {
    {
    let m = inp.msg;
    (s_ == LRecord { app: m.app_state, app_state: 0int, bal: 0int, bal_state_req: 0int, bal_state_supply: 0int, constants: s.constants, dst: 0int, max_bal_reflected: m.bal_state_supply, msg: 0int, next_op_to_execute: seq![], opn_state_req: 0int, opn_state_supply: 0int, ops_complete: m.opn_state_supply, proposer_id: 0int, reply: 0int, reply_cache: m.reply_cache, seqno: 0int, seqno_reply: 0int, src: 0int, v: 0int })
}
}

/// ExecutorProcessAppStateRequest operator
pub open spec fn LExecutorProcessAppStateRequest(s: LState, c: LConstants, s_: int, inp: int, sent_packets: int) -> bool {
    {
    let m = inp.msg;
    if (((s.constants.all.config.replica_ids.contains(inp.src) && arbitrary()) && (s.ops_complete >= m.opn_state_req)) && arbitrary()) { ((s_ == s) && (sent_packets == seq![LRecord { app: 0int, app_state: 0int, bal: 0int, bal_state_req: 0int, bal_state_supply: 0int, constants: 0int, dst: inp.src, max_bal_reflected: 0int, msg: LRecord { app: 0int, app_state: s.app, bal: 0int, bal_state_req: 0int, bal_state_supply: s.max_bal_reflected, constants: 0int, dst: 0int, max_bal_reflected: 0int, msg: 0int, next_op_to_execute: 0int, opn_state_req: 0int, opn_state_supply: s.ops_complete, ops_complete: 0int, proposer_id: 0int, reply: 0int, reply_cache: s.reply_cache, seqno: 0int, seqno_reply: 0int, src: 0int, v: 0int }, next_op_to_execute: 0int, opn_state_req: 0int, opn_state_supply: 0int, ops_complete: 0int, proposer_id: 0int, reply: 0int, reply_cache: 0int, seqno: 0int, seqno_reply: 0int, src: s.constants.all.config.replica_ids[s.constants.my_index], v: 0int }])) } else { ((s_ == s) && (sent_packets == seq![])) }
}
}

/// ExecutorProcessStartingPhase2 operator
pub open spec fn LExecutorProcessStartingPhase2(s: LState, c: LConstants, s_: int, inp: int, sent_packets: int) -> bool {
    if (s.constants.all.config.replica_ids.contains(inp.src) && (inp.msg.logTruncationPoint_2 > s.ops_complete)) { ((s_ == s) && arbitrary()) } else { ((s_ == s) && (sent_packets == seq![])) }
}

/// ExecutorProcessRequest operator
pub open spec fn LExecutorProcessRequest(s: LState, c: LConstants, inp: int, sent_packets: int) -> bool {
    if ((inp.msg.seqno_req == s.reply_cache[inp.src].seqno) && arbitrary()) { {
    let r = s.reply_cache[inp.src];
    (sent_packets == seq![LRecord { app: 0int, app_state: 0int, bal: 0int, bal_state_req: 0int, bal_state_supply: 0int, constants: 0int, dst: r.client, max_bal_reflected: 0int, msg: LRecord { app: 0int, app_state: 0int, bal: 0int, bal_state_req: 0int, bal_state_supply: 0int, constants: 0int, dst: 0int, max_bal_reflected: 0int, msg: 0int, next_op_to_execute: 0int, opn_state_req: 0int, opn_state_supply: 0int, ops_complete: 0int, proposer_id: 0int, reply: r.reply, reply_cache: 0int, seqno: 0int, seqno_reply: r.seqno, src: 0int, v: 0int }, next_op_to_execute: 0int, opn_state_req: 0int, opn_state_supply: 0int, ops_complete: 0int, proposer_id: 0int, reply: 0int, reply_cache: 0int, seqno: 0int, seqno_reply: 0int, src: s.constants.all.config.replica_ids[s.constants.my_index], v: 0int }])
} } else { (sent_packets == seq![]) }
}

} // verus!
