//! Generated from TLA+ module: Learner
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Learner module
pub struct LRecord {
    pub candidate_learned_value: int,
    pub constants: int,
    pub max_ballot_seen: int,
    pub proposer_id: int,
    pub received_2b_message_senders: int,
    pub seqno: int,
    pub unexecuted_learner_state: int,
}

/// State for Learner module
pub struct LState {
}

/// Constants for the module
pub struct LConstants {
    pub ReplicaConstants: int,
    pub RslPacket: int,
    pub Learner: int,
    pub OperationNumber: int,
}


/// Learner operator
pub open spec fn LLearner(c: LConstants) -> LRecord {
    LRecord { candidate_learned_value: 0int, constants: c.ReplicaConstants, max_ballot_seen: 8530703455int, proposer_id: 0int, received_2b_message_senders: 0int, seqno: 0int, unexecuted_learner_state: arbitrary() }
}

/// LearnerInit operator
pub open spec fn LLearnerInit(s: LState, c: LConstants, l: int) -> bool {
    (((arbitrary() == c) && (arbitrary() == LRecord { candidate_learned_value: 0int, constants: 0int, max_ballot_seen: 0int, proposer_id: 0, received_2b_message_senders: 0int, seqno: 0, unexecuted_learner_state: 0int })) && (arbitrary() == seq![]))
}

/// LearnerProcess2b operator
pub open spec fn LLearnerProcess2b(s: LState, s_: LState, c: LConstants, packet: int) -> bool {
    {
    let m = arbitrary();
    {
    let opn = arbitrary();
    if (Set::<int>::empty().contains(!(arbitrary())) || arbitrary()) { (s_ == s) } else { if arbitrary() { {
    let tup_ = LRecord { candidate_learned_value: arbitrary(), constants: 0int, max_ballot_seen: 0int, proposer_id: 0int, received_2b_message_senders: arbitrary(), seqno: 0int, unexecuted_learner_state: 0int };
    (s_ == LRecord { candidate_learned_value: 0int, constants: arbitrary(), max_ballot_seen: arbitrary(), proposer_id: 0int, received_2b_message_senders: 0int, seqno: 0int, unexecuted_learner_state: arbitrary() })
} } else { if arbitrary().dom().contains(!(opn)) { {
    let tup_ = LRecord { candidate_learned_value: arbitrary(), constants: 0int, max_ballot_seen: 0int, proposer_id: 0int, received_2b_message_senders: arbitrary(), seqno: 0int, unexecuted_learner_state: 0int };
    (s_ == LRecord { candidate_learned_value: 0int, constants: arbitrary(), max_ballot_seen: arbitrary(), proposer_id: 0int, received_2b_message_senders: 0int, seqno: 0int, unexecuted_learner_state: arbitrary().insert(opn, tup_) })
} } else { if arbitrary()[opn].received_2b_message_senders.contains(arbitrary::<int>()) { (s_ == s) } else { {
    let tup = arbitrary()[opn];
    {
    let tup_ = LRecord { candidate_learned_value: arbitrary(), constants: 0int, max_ballot_seen: 0int, proposer_id: 0int, received_2b_message_senders: (arbitrary::<int>() + set![arbitrary()]), seqno: 0int, unexecuted_learner_state: 0int };
    (s_ == LRecord { candidate_learned_value: 0int, constants: arbitrary(), max_ballot_seen: arbitrary(), proposer_id: 0int, received_2b_message_senders: 0int, seqno: 0int, unexecuted_learner_state: arbitrary().insert(opn, tup_) })
}
} } } } }
}
}
}

/// LearnerForgetDecision operator
pub open spec fn LLearnerForgetDecision(s: LState, s_: LState, c: LConstants, opn: int) -> bool {
    if arbitrary().dom().contains(opn) { (s_ == LRecord { candidate_learned_value: 0int, constants: arbitrary(), max_ballot_seen: arbitrary(), proposer_id: 0int, received_2b_message_senders: 0int, seqno: 0int, unexecuted_learner_state: Set::<int>::empty().difference(set![opn]) }) } else { (s_ == s) }
}

/// LearnerForgetOperationsBefore operator
pub open spec fn LLearnerForgetOperationsBefore(s: LState, s_: LState, c: LConstants, ops_complete: int) -> bool {
    forall |k| c.OperationNumber.contains(k) ==> ((arbitrary().dom().contains(k) <==> ((k >= ops_complete) && arbitrary().dom().contains(k))) && forall |k| c.OperationNumber.contains(k) ==> ((arbitrary().dom().contains(k) ==> (arbitrary()[k] == arbitrary()[k])) && (s_ == LRecord { candidate_learned_value: 0int, constants: arbitrary(), max_ballot_seen: arbitrary(), proposer_id: 0int, received_2b_message_senders: 0int, seqno: 0int, unexecuted_learner_state: arbitrary() })))
}

} // verus!
