//! Generated from TLA+ module: Message
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// State for Message module
pub struct LState {
}


/// RslMessage operator
pub open spec fn LRslMessage() -> Set<int> {
    set![RslMessageInvalid, RslMessageRequest, RslMessage1a, RslMessage1b, RslMessage2a, RslMessage2b, RslMessageHeartbeat, RslMessageReply, RslMessageAppStateRequest, RslMessageAppStateSupply, RslMessageStartingPhase2]
}

} // verus!
