//! Generated from TLA+ module: Parameters
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Parameters module
pub struct LRecord {
    pub baseline_view_timeout_period: int,
    pub heartbeat_period: int,
    pub max_batch_delay: int,
    pub max_batch_size: int,
    pub max_integer_val: int,
    pub max_log_length: int,
}

/// State for Parameters module
pub struct LState {
}

/// Constants for the module
pub struct LConstants {
    pub Parameters: int,
}


/// Parameters operator
pub open spec fn LParameters(c: LConstants) -> { max_batch_size: Set<int>, max_integer_val: int, max_batch_delay: Set<int>, baseline_view_timeout_period: Set<int>, heartbeat_period: Set<int>, max_log_length: Set<int> } {
    LRecord { baseline_view_timeout_period: int, heartbeat_period: int, max_batch_delay: int, max_batch_size: int, max_integer_val: UpperBound, max_log_length: int }
}

/// WFLParameters operator
pub open spec fn LWFLParameters(s: LState, c: LConstants, p: int) -> bool {
    (((((p.max_log_length > 0) && (p.baseline_view_timeout_period > 0)) && (p.heartbeat_period > 0)) && (p.max_batch_size > 0)) && (p.max_batch_delay >= 0))
}

} // verus!
