//! Generated from TLA+ module: Replica
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Replica module
pub struct LRecord {
    pub acceptor: int,
    pub bal_heartbeat: int,
    pub constants: int,
    pub executor: int,
    pub learner: int,
    pub nextActionIndex: int,
    pub nextHeartbeatTime: int,
    pub opn_ckpt: int,
    pub proposer: int,
    pub replica: int,
    pub suspicious: int,
    pub t: int,
}

/// State for Replica module
pub struct LState {
}

/// Constants for the module
pub struct LConstants {
    pub Replica: int,
    pub ClockReading: int,
    pub Scheduler: int,
    pub RslIo: Set<int>,
    pub RslPacket: Set<int>,
    pub ReplicaConstants: int,
}


/// Replica operator
pub open spec fn LReplica(c: LConstants) -> LRecord {
    LRecord { acceptor: 8673820224int, bal_heartbeat: 0int, constants: arbitrary::<int>(), executor: 4113746780int, learner: 9096504070int, nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: 1982643813int, replica: 0int, suspicious: 0int, t: 0int }
}

/// Scheduler operator
pub open spec fn LScheduler(c: LConstants) -> LRecord {
    LRecord { acceptor: 0int, bal_heartbeat: 0int, constants: 0int, executor: 0int, learner: 0int, nextActionIndex: arbitrary(), nextHeartbeatTime: 0int, opn_ckpt: 0int, proposer: 0int, replica: arbitrary(), suspicious: 0int, t: 0int }
}

/// ReplicaInit operator
pub open spec fn LReplicaInit(c: LConstants, r: int) -> bool {
    ((((((arbitrary::<LConstants>() == c) && (arbitrary::<int>() == 0)) && arbitrary()) && arbitrary()) && arbitrary()) && arbitrary())
}

/// ReplicaNextProcessInvalid operator
pub open spec fn LReplicaNextProcessInvalid(s: LState, s_: LState, c: LConstants, received_packet: int, sent_packets: Seq<int>) -> bool {
    ((s_ == s) && (sent_packets == Seq::<int>::empty()))
}

/// ReplicaNextProcessRequest operator
pub open spec fn LReplicaNextProcessRequest(s: LState, s_: LState, c: LConstants, received_packet: int, sent_packets: Seq<int>) -> bool {
    if (arbitrary::<Map<int, int>>().dom().contains(arbitrary::<int>()) && (arbitrary::<int>() <= arbitrary::<int>())) { (arbitrary() && (s_ == s)) } else { ((arbitrary() && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int })) && (sent_packets == Seq::<int>::empty())) }
}

/// ReplicaNextProcess1a operator
pub open spec fn LReplicaNextProcess1a(s: LState, s_: LState, c: LConstants, received_packet: int, sent_packets: int) -> bool {
    (arbitrary() && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int }))
}

/// ReplicaNextProcess1b operator
pub open spec fn LReplicaNextProcess1b(s: LState, s_: LState, c: LConstants, received_packet: int, sent_packets: Seq<int>) -> bool {
    if (((Set::<int>::empty().contains(arbitrary::<int>()) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 1)) && forall |other_packet| c.RslPacket.contains(other_packet) ==> (Set::<int>::empty().contains(other_packet) ==> (arbitrary::<int>() != arbitrary::<int>()))) { (((arbitrary() && arbitrary()) && (sent_packets == Seq::<int>::empty())) && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int })) } else { ((s_ == s) && (sent_packets == Seq::<int>::empty())) }
}

/// ReplicaNextProcessStartingPhase2 operator
pub open spec fn LReplicaNextProcessStartingPhase2(s: LState, s_: LState, c: LConstants, received_packet: int, sent_packets: int) -> bool {
    (arbitrary() && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int }))
}

/// ReplicaNextProcess2a operator
pub open spec fn LReplicaNextProcess2a(s: LState, s_: LState, c: LConstants, received_packet: int, sent_packets: Seq<int>) -> bool {
    {
    let m: int = arbitrary();
    if ((Set::<int>::empty().contains(arbitrary::<int>()) && arbitrary()) && arbitrary()) { (arbitrary() && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int })) } else { ((s_ == s) && (sent_packets == Seq::<int>::empty())) }
}
}

/// ReplicaNextProcess2b operator
pub open spec fn LReplicaNextProcess2b(s: LState, s_: LState, c: LConstants, received_packet: int, sent_packets: Seq<int>) -> bool {
    {
    let opn: int = arbitrary();
    {
    let op_learnable = ((arbitrary::<int>() < opn) || ((arbitrary() == opn) && (arbitrary::<int>() == 4689272130int)));
    if op_learnable { ((arbitrary() && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int })) && (sent_packets == Seq::<int>::empty())) } else { ((s_ == s) && (sent_packets == Seq::<int>::empty())) }
}
}
}

/// ReplicaNextProcessReply operator
pub open spec fn LReplicaNextProcessReply(s: LState, s_: LState, c: LConstants, received_packet: int, sent_packets: Seq<int>) -> bool {
    ((s_ == s) && (sent_packets == Seq::<int>::empty()))
}

/// ReplicaNextProcessAppStateSupply operator
pub open spec fn LReplicaNextProcessAppStateSupply(s: LState, s_: LState, c: LConstants, received_packet: int, sent_packets: Seq<int>) -> bool {
    if (Set::<int>::empty().contains(arbitrary::<int>()) && (arbitrary::<int>() > arbitrary::<int>())) { (((arbitrary() && arbitrary()) && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int })) && (sent_packets == Seq::<int>::empty())) } else { ((s_ == s) && (sent_packets == Seq::<int>::empty())) }
}

/// ReplicaNextProcessAppStateRequest operator
pub open spec fn LReplicaNextProcessAppStateRequest(s: LState, s_: LState, c: LConstants, received_packet: int, sent_packets: int) -> bool {
    (arbitrary() && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int }))
}

/// ReplicaNextProcessHeartbeat operator
pub open spec fn LReplicaNextProcessHeartbeat(s: LState, s_: LState, c: LConstants, received_packet: int, clock: int, sent_packets: Seq<int>) -> bool {
    (((arbitrary() && arbitrary()) && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int })) && (sent_packets == Seq::<int>::empty()))
}

/// ReplicaNextSpontaneousMaybeEnterNewViewAndSend1a operator
pub open spec fn LReplicaNextSpontaneousMaybeEnterNewViewAndSend1a(s: LState, s_: LState, c: LConstants, sent_packets: int) -> bool {
    (arbitrary() && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int }))
}

/// ReplicaNextSpontaneousMaybeEnterPhase2 operator
pub open spec fn LReplicaNextSpontaneousMaybeEnterPhase2(s: LState, s_: LState, c: LConstants, sent_packets: int) -> bool {
    (arbitrary() && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int }))
}

/// ReplicaNextReadClockMaybeNominateValueAndSend2a operator
pub open spec fn LReplicaNextReadClockMaybeNominateValueAndSend2a(s: LState, s_: LState, c: LConstants, clock: int, sent_packets: int) -> bool {
    (arbitrary() && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int }))
}

/// ReplicaNextSpontaneousTruncateLogBasedOnCheckpoints operator
pub open spec fn LReplicaNextSpontaneousTruncateLogBasedOnCheckpoints(s: LState, s_: LState, c: LConstants, sent_packets: Seq<int>) -> bool {
    exists |opn| 6996286291int.contains(opn) && ((Set::<int>::empty().contains(opn) && arbitrary()) && if (opn > arbitrary::<int>()) { ((arbitrary() && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int })) && (sent_packets == Seq::<int>::empty())) } else { ((s_ == s) && (sent_packets == Seq::<int>::empty())) })
}

/// ReplicaNextSpontaneousMaybeMakeDecision operator
pub open spec fn LReplicaNextSpontaneousMaybeMakeDecision(s: LState, s_: LState, c: LConstants, sent_packets: Seq<int>) -> bool {
    {
    let opn: int = arbitrary();
    if (((arbitrary::<int>() == 4689272130int) && arbitrary::<Map<int, int>>().dom().contains(opn)) && ((arbitrary::<Seq<int>>().len() as int) >= arbitrary::<int>())) { ((arbitrary() && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int })) && (sent_packets == Seq::<int>::empty())) } else { ((s_ == s) && (sent_packets == Seq::<int>::empty())) }
}
}

/// ReplicaNextSpontaneousMaybeExecute operator
pub open spec fn LReplicaNextSpontaneousMaybeExecute(s: LState, s_: LState, c: LConstants, sent_packets: Seq<int>) -> bool {
    if (((arbitrary::<int>() == 6764822447int) && arbitrary()) && arbitrary()) { {
    let v: int = arbitrary();
    (((arbitrary() && arbitrary()) && arbitrary()) && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int }))
} } else { ((s_ == s) && (sent_packets == Seq::<int>::empty())) }
}

/// ReplicaNextReadClockMaybeSendHeartbeat operator
pub open spec fn LReplicaNextReadClockMaybeSendHeartbeat(s: LState, s_: LState, c: LConstants, clock: int, sent_packets: Seq<int>) -> bool {
    if (arbitrary::<int>() < arbitrary::<int>()) { ((s_ == s) && (sent_packets == Seq::<int>::empty())) } else { (((arbitrary::<int>() == arbitrary::<int>()) && arbitrary()) && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int })) }
}

/// ReplicaNextReadClockCheckForViewTimeout operator
pub open spec fn LReplicaNextReadClockCheckForViewTimeout(s: LState, s_: LState, c: LConstants, clock: int, sent_packets: Seq<int>) -> bool {
    ((arbitrary() && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int })) && (sent_packets == Seq::<int>::empty()))
}

/// ReplicaNextReadClockCheckForQuorumOfViewSuspicions operator
pub open spec fn LReplicaNextReadClockCheckForQuorumOfViewSuspicions(s: LState, s_: LState, c: LConstants, clock: int, sent_packets: Seq<int>) -> bool {
    ((arbitrary() && (s_ == LRecord { acceptor: arbitrary(), bal_heartbeat: 0int, constants: arbitrary(), executor: arbitrary(), learner: arbitrary(), nextActionIndex: 0int, nextHeartbeatTime: arbitrary(), opn_ckpt: 0int, proposer: arbitrary(), replica: 0int, suspicious: 0int, t: 0int })) && (sent_packets == Seq::<int>::empty()))
}

/// ExtractSentPacketsFromIos operator
pub open spec fn LExtractSentPacketsFromIos(c: LConstants, ios: Seq<int>) -> Seq<int> {
    if ((ios.len() as int) == 0) { Seq::<int>::empty() } else { if (arbitrary::<int>() == 5308382735int) { (seq![arbitrary()] + LExtractSentPacketsFromIos(c, ios.drop_first())) } else { LExtractSentPacketsFromIos(c, ios.drop_first()) } }
}

/// ReplicaNextReadClockAndProcessPacket operator
pub open spec fn LReplicaNextReadClockAndProcessPacket(s: LState, s_: LState, c: LConstants, ios: Seq<int>) -> bool {
    ((((ios.len() as int) > 1) && (arbitrary::<int>() == 9416806621int)) && forall |io| c.RslIo.contains(io) ==> ((ios.subrange(2 - 1, (ios.len() as int)).contains(io) ==> (arbitrary::<int>() == 5308382735int)) && LReplicaNextProcessHeartbeat(s, s_, c, s, s_, arbitrary::<Seq<int>>(), arbitrary(), LExtractSentPacketsFromIos(c, ios))))
}

/// ReplicaNextProcessPacketWithoutReadingClock operator
pub open spec fn LReplicaNextProcessPacketWithoutReadingClock(s: LState, s_: LState, c: LConstants, ios: int) -> bool {
    {
    let sent_packets = LExtractSentPacketsFromIos(c, ios);
    forall |io| c.RslIo.contains(io) ==> ((ios.drop_first().contains(io) ==> (arbitrary::<int>() == 5308382735int)) && LReplicaNextProcessInvalid(s, s_, c, s, s_, arbitrary(), sent_packets))
}
}

/// ReplicaNextProcessPacket operator
pub open spec fn LReplicaNextProcessPacket(s: LState, s_: LState, c: LConstants, ios: Seq<int>) -> bool {
    (((ios.len() as int) >= 1) && if (arbitrary::<int>() == 5897376741int) { ((s_ == s) && ((ios.len() as int) == 1)) } else { ((arbitrary::<int>() == 1912102818int) && if (arbitrary::<int>() == 2135448699int) { LReplicaNextReadClockAndProcessPacket(s, s_, c, s, s_, ios) } else { LReplicaNextProcessPacketWithoutReadingClock(s, s_, c, s, s_, ios) }) })
}

/// ReplicaNumActions operator
pub open spec fn LReplicaNumActions(c: LConstants) -> int {
    10
}

/// SpontaneousIos operator
pub open spec fn LSpontaneousIos(c: LConstants, ios: Seq<int>, clocks: int) -> bool {
    ((clocks <= (ios.len() as int)) && forall |i: int| ((((0 <= i) && (i < clocks)) ==> (arbitrary::<int>() == 9416806621int)) && forall |i: int| (((clocks <= i) && (i < (ios.len() as int))) ==> (arbitrary::<int>() == 5308382735int))))
}

/// SpontaneousClock operator
pub open spec fn LSpontaneousClock(c: LConstants, ios: int) -> LRecord {
    if LSpontaneousIos(c, ios, 1) { LRecord { acceptor: 0int, bal_heartbeat: 0int, constants: 0int, executor: 0int, learner: 0int, nextActionIndex: 0int, nextHeartbeatTime: 0int, opn_ckpt: 0int, proposer: 0int, replica: 0int, suspicious: 0int, t: arbitrary() } } else { LRecord { acceptor: 0int, bal_heartbeat: 0int, constants: 0int, executor: 0int, learner: 0int, nextActionIndex: 0int, nextHeartbeatTime: 0int, opn_ckpt: 0int, proposer: 0int, replica: 0int, suspicious: 0int, t: 0 } }
}

/// ReplicaNoReceiveNext operator
pub open spec fn LReplicaNoReceiveNext(s: LState, s_: LState, c: LConstants, nextActionIndex: int, ios: int) -> bool {
    {
    let sent_packets = LExtractSentPacketsFromIos(c, ios);
    if (nextActionIndex == 1) { (LSpontaneousIos(c, ios, 0) && LReplicaNextSpontaneousMaybeEnterNewViewAndSend1a(s, s_, c, s, s_, sent_packets)) } else { if (nextActionIndex == 2) { (LSpontaneousIos(c, ios, 0) && LReplicaNextSpontaneousMaybeEnterPhase2(s, s_, c, s, s_, sent_packets)) } else { if (nextActionIndex == 3) { (LSpontaneousIos(c, ios, 1) && LReplicaNextReadClockMaybeNominateValueAndSend2a(s, s_, c, s, s_, LSpontaneousClock(c, ios), sent_packets)) } else { if (nextActionIndex == 4) { (LSpontaneousIos(c, ios, 0) && LReplicaNextSpontaneousTruncateLogBasedOnCheckpoints(s, s_, c, s, s_, sent_packets)) } else { if (nextActionIndex == 5) { (LSpontaneousIos(c, ios, 0) && LReplicaNextSpontaneousMaybeMakeDecision(s, s_, c, s, s_, sent_packets)) } else { if (nextActionIndex == 6) { (LSpontaneousIos(c, ios, 0) && LReplicaNextSpontaneousMaybeExecute(s, s_, c, s, s_, sent_packets)) } else { if (nextActionIndex == 7) { (LSpontaneousIos(c, ios, 1) && LReplicaNextReadClockCheckForViewTimeout(s, s_, c, s, s_, LSpontaneousClock(c, ios), sent_packets)) } else { if (nextActionIndex == 8) { (LSpontaneousIos(c, ios, 1) && LReplicaNextReadClockCheckForQuorumOfViewSuspicions(s, s_, c, s, s_, LSpontaneousClock(c, ios), sent_packets)) } else { (((nextActionIndex == 9) && LSpontaneousIos(c, ios, 1)) && LReplicaNextReadClockMaybeSendHeartbeat(s, s_, c, s, s_, LSpontaneousClock(c, ios), sent_packets)) } } } } } } } }
}
}

/// SchedulerInit operator
pub open spec fn LSchedulerInit(c: LConstants, s: int) -> bool {
    (LReplicaInit(c, arbitrary::<int>(), c) && (arbitrary::<int>() == 0))
}

/// SchedulerNext operator
pub open spec fn LSchedulerNext(s: LState, s_: LState, c: LConstants, ios: int) -> bool {
    ((arbitrary::<int>() == ((arbitrary::<int>() + 1) % LReplicaNumActions(c))) && if (arbitrary::<int>() == 0) { LReplicaNextProcessPacket(s, s_, c, arbitrary::<Seq<int>>(), arbitrary(), ios) } else { LReplicaNoReceiveNext(s, s_, c, arbitrary::<int>(), arbitrary::<int>(), arbitrary(), ios) })
}

} // verus!
