// Auto-generated by verus-transpiler
// DO NOT EDIT MANUALLY

use std::collections::HashSet;
use vstd::prelude::*;

verus! {

#[derive(Clone)]
pub struct CRecord {
    pub rm: i64,
    pub rm_aborted: i64,
    pub rm_committed: i64,
    pub rm_prepared: i64,
    pub tm_prepared: i64,
    pub tm_state: i64,
}

impl CRecord {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CRecord {
    type V = LRecord;

    open spec fn view(&self) -> LRecord {
        LRecord {
            rm: self.rm as int,
            rm_aborted: self.rm_aborted as int,
            rm_committed: self.rm_committed as int,
            rm_prepared: self.rm_prepared as int,
            tm_prepared: self.tm_prepared as int,
            tm_state: self.tm_state as int,
        }
    }
}

#[derive(Clone)]
pub struct CState {
}

impl CState {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CState {
    type V = LState;

    open spec fn view(&self) -> LState {
        LState {
        }
    }
}

pub exec fn CState() -> (result: CRecord)ensures
    result.well_formed(),
    result@ == LState(),
{
    assume(false);
    CRecord {
        rm: 0i64,
        rm_aborted: Carbitrary(),
        rm_committed: Carbitrary(),
        rm_prepared: Carbitrary(),
        tm_prepared: Carbitrary(),
        tm_state: Carbitrary(),
    }

}

pub exec fn CConstants() -> (result: CRecord)ensures
    result.well_formed(),
    result@ == LConstants(),
{
    assume(false);
    CRecord {
        rm: Carbitrary(),
        rm_aborted: 0i64,
        rm_committed: 0i64,
        rm_prepared: 0i64,
        tm_prepared: 0i64,
        tm_state: 0i64,
    }

}

pub exec fn CTMState() -> (result: HashSet<i64>)ensures
    result@ == LTMState(),
{
    assume(false);
    { let mut __hs = HashSet::new(); __hs.insert(1755428851); __hs.insert(1819226073); __hs.insert(4391523824); __hs }

}

pub exec fn CRMState() -> (result: HashSet<i64>)ensures
    result@ == LRMState(),
{
    assume(false);
    { let mut __hs = HashSet::new(); __hs.insert(7249365736); __hs.insert(9617861224); __hs.insert(1819226073); __hs.insert(4391523824); __hs }

}

pub exec fn CTPCMessage() -> (result: HashSet<i64>)ensures
    result@ == LTPCMessage(),
{
    assume(false);
    { let mut __hs = HashSet::new(); __hs.insert(6989001116); __hs.insert(8119312364); __hs.insert(9385017532); __hs.insert(8579416217); __hs }

}

} // verus!
