// Auto-generated by verus-transpiler
// DO NOT EDIT MANUALLY

use crate::common::collections::hashsets::*;
use crate::common::collections::sets::*;
use crate::common::collections::vecs::*;
use crate::common::native::io_s::EndPoint;
use crate::generated::RSL::types_gen::*;
use crate::protocol::common::upper_bound::*;
use crate::protocol::RSL::acceptor::*;
use crate::protocol::RSL::broadcast::*;
use crate::protocol::RSL::configuration::WellFormedLConfiguration;
use crate::protocol::RSL::election::*;
use crate::protocol::RSL::executor::*;
use crate::protocol::RSL::learner::*;
use crate::protocol::RSL::proposer::*;
use crate::protocol::RSL::replica::*;
use crate::protocol::RSL::types::*;
use std::collections::HashMap;
use std::collections::HashSet;
use vstd::map::*;
use vstd::prelude::*;
use vstd::set::*;

verus! {

// =============================================================================
// Helper: clone CPacket preserving validity
// =============================================================================

#[verifier(external_body)]
fn clone_cpacket_preserving_validity(p: &CPacket) -> (res: CPacket)
    requires p.valid(),
    ensures res@ == p@, res.valid(),
{
    p.clone_up_to_view()
}

// =============================================================================
// CComputeSuccessorView — delegate to verified impl
// =============================================================================

pub exec fn CComputeSuccessorView(b: &CBallot, c: &CConstants) -> (result: CBallot)
requires
    b.valid(),
    c.valid(),
    b.seqno < 0xFFFF_FFFF_FFFF_FFFFu64,
ensures
    result.valid(),
    result@ == ComputeSuccessorView(b@, c@),
{
    // CBallot is Copy, CConstants needs clone
    CElectionState::CComputeSuccessorView(*b, c.clone_up_to_view())
}

// =============================================================================
// CBoundRequestSequence — delegate to verified impl
// =============================================================================

pub exec fn CBoundRequestSequence(s: &Vec<CRequest>, lengthBound: u64) -> (result: Vec<CRequest>)
requires
    s@.len() < 0x1_0000_0000_0000_0000,
    forall |i: int| 0 <= i < s@.len() ==> s@[i].valid(),
ensures
    result@.map(|i, r: CRequest| r@) == BoundRequestSequence(s@.map(|i, r: CRequest| r@), UpperBound::UpperBoundFinite{n: lengthBound as int}),
{
    CElectionState::CBoundRequestSequence(s, lengthBound)
}

// =============================================================================
// CRequestsMatch — delegate to verified impl
// =============================================================================

pub exec fn CRequestsMatch(r1: &CRequest, r2: &CRequest) -> (result: bool)
requires
    r1.valid(),
    r2.valid(),
ensures
    result == RequestsMatch(r1@, r2@),
{
    CElectionState::CRequestsMatch(r1, r2)
}

// =============================================================================
// CRequestSatisfiedBy — delegate to verified impl
// =============================================================================

pub exec fn CRequestSatisfiedBy(r1: &CRequest, r2: &CRequest) -> (result: bool)
requires
    r1.valid(),
    r2.valid(),
ensures
    result == RequestSatisfiedBy(r1@, r2@),
{
    CElectionState::CRequestSatisfiedBy(r1, r2)
}

// =============================================================================
// CRemoveAllSatisfiedRequestsInSequence — delegate to verified impl
// =============================================================================

pub exec fn CRemoveAllSatisfiedRequestsInSequence(s: &Vec<CRequest>, r: &CRequest) -> (result: Vec<CRequest>)
requires
    forall |i: int| 0 <= i < s@.len() ==> s@[i].valid(),
    r.valid(),
ensures
    result@.map(|i, r: CRequest| r@) == RemoveAllSatisfiedRequestsInSequence(s@.map(|i, r: CRequest| r@), r@),
{
    CElectionState::CRemoveAllSatisfiedRequestsInSequence(s, r)
}

// =============================================================================
// CElectionStateInit — delegate to verified impl
// =============================================================================

pub exec fn CElectionStateInit(c: &CReplicaConstants) -> (result: CElectionState)
requires
    c.valid(),
    (c.all.config.replica_ids.len() > 0),
ensures
    result.valid(),
    ElectionStateInit(result@, c@),
{
    CElectionState::CElectionStateInit(c.clone_up_to_view())
}

// =============================================================================
// CElectionStateProcessHeartbeat — clone-delegate to verified impl
// =============================================================================

pub exec fn CElectionStateProcessHeartbeat(es: &CElectionState, p: &CPacket, clock: &u64) -> (result: CElectionState)
requires
    es.valid(),
    p.valid(),
    p.msg is CMessageHeartbeat,
ensures
    result.valid(),
    ElectionStateProcessHeartbeat(es@, result@, p@, *clock as int),
{
    let mut state = es.clone_up_to_view();
    let pkt = clone_cpacket_preserving_validity(p);

    state.CElectionStateProcessHeartbeat(pkt, *clock);
    // ensures: state.valid(), ElectionStateProcessHeartbeat(old(state)@, state@, pkt@, clock as int)
    // Since old(state)@ == es@ and pkt@ == p@: ElectionStateProcessHeartbeat(es@, state@, p@, *clock as int)

    state
}

// =============================================================================
// CElectionStateCheckForViewTimeout — clone-delegate to verified impl
// =============================================================================

pub exec fn CElectionStateCheckForViewTimeout(es: &CElectionState, clock: &u64) -> (result: CElectionState)
requires
    es.valid(),
ensures
    result.valid(),
    ElectionStateCheckForViewTimeout(es@, result@, *clock as int),
{
    let mut state = es.clone_up_to_view();

    state.CElectionStateCheckForViewTimeout(*clock);
    // ensures: state.valid(), ElectionStateCheckForViewTimeout(old(state)@, state@, clock as int)
    // Since old(state)@ == es@: ElectionStateCheckForViewTimeout(es@, state@, *clock as int)

    state
}

// =============================================================================
// CElectionStateCheckForQuorumOfViewSuspicions — clone-delegate to verified impl
// =============================================================================

pub exec fn CElectionStateCheckForQuorumOfViewSuspicions(es: &CElectionState, clock: &u64) -> (result: CElectionState)
requires
    es.valid(),
ensures
    result.valid(),
    ElectionStateCheckForQuorumOfViewSuspicions(es@, result@, *clock as int),
{
    let mut state = es.clone_up_to_view();

    state.CElectionStateCheckForQuorumOfViewSuspicions(*clock);
    // ensures: state.valid(), ElectionStateCheckForQuorumOfViewSuspicions(old(state)@, state@, clock as int)
    // Since old(state)@ == es@: ElectionStateCheckForQuorumOfViewSuspicions(es@, state@, *clock as int)

    state
}

// =============================================================================
// CElectionStateReflectReceivedRequest — clone-delegate to verified impl
// =============================================================================

pub exec fn CElectionStateReflectReceivedRequest(es: &CElectionState, req: &CRequest) -> (result: CElectionState)
requires
    es.valid(),
    req.valid(),
ensures
    result.valid(),
    ElectionStateReflectReceivedRequest(es@, result@, req@),
{
    let mut state = es.clone_up_to_view();
    let r = req.clone_up_to_view();

    state.CElectionStateReflectReceivedRequest(r);
    // ensures: state.valid(), ElectionStateReflectReceivedRequest(old(state)@, state@, r@)
    // Since old(state)@ == es@ and r@ == req@: ElectionStateReflectReceivedRequest(es@, state@, req@)

    state
}

// =============================================================================
// CRemoveExecutedRequestBatch — delegate to verified impl
// =============================================================================

pub exec fn CRemoveExecutedRequestBatch(reqs: &Vec<CRequest>, batch: &CRequestBatch) -> (result: Vec<CRequest>)
requires
    forall |i: int| 0 <= i < reqs@.len() ==> reqs@[i].valid(),
    crequestbatch_is_valid(batch),
ensures
    result@.map(|i, r: CRequest| r@) == RemoveExecutedRequestBatch(reqs@.map(|i, r: CRequest| r@), batch@.map(|i, r: CRequest| r@)),
{
    CElectionState::CRemoveExecutedRequestBatch(reqs, batch)
}

} // verus!
