//! Generated from TLA+ module: Paxos
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// State for Paxos module
pub struct LState {
}

/// Constants for the module
pub struct LConstants {
    pub Constants: int,
    pub State: int,
}


/// Init operator
pub open spec fn LInit(s: LState, c: LConstants) -> bool {
    (((((((((((arbitrary::<int>() == 0) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 5126177779int)) && (arbitrary::<int>() == Set::<int>::empty())) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == Set::<int>::empty())) && (arbitrary::<int>() == 0))
}

/// Send1a operator
pub open spec fn LSend1a(s: LState, c: LConstants, s_: int, b: int) -> bool {
    (((((((((((((arbitrary::<int>() == 5126177779int) && (b > arbitrary::<int>())) && (arbitrary::<int>() == b)) && (arbitrary::<int>() == 9996969643int)) && (arbitrary::<int>() == Set::<int>::empty())) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == 0)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>()))
}

/// Send1b operator
pub open spec fn LSend1b(s: LState, c: LConstants, s_: int, b: int) -> bool {
    ((((((((((((b >= arbitrary::<int>()) && (arbitrary::<int>() == b)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>()))
}

/// RecvPromise operator
pub open spec fn LRecvPromise(s: LState, c: LConstants, s_: int, a: int, a_accepted_bal: int, a_accepted_val: int) -> bool {
    (((((arbitrary::<int>() == 9996969643int) && arbitrary::<int>().contains(a)) && arbitrary::<int>().contains(!(a))) && (arbitrary::<int>() == arbitrary::<int>().union(set![a]))) && (arbitrary::<int>() == if (a_accepted_bal > arbitrary::<int>()) { a_accepted_bal } else { (arbitrary::<int>() && (arbitrary::<int>() == if (a_accepted_bal > arbitrary::<int>()) { a_accepted_val } else { ((((((((arbitrary::<int>() && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 9996969643int)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) })) }))
}

/// Send2a operator
pub open spec fn LSend2a(s: LState, c: LConstants, s_: int, v: int) -> bool {
    (((arbitrary::<int>() == 9996969643int) && (arbitrary::<int>().len() >= arbitrary::<int>())) && (arbitrary::<int>() == if (arbitrary::<int>() > 0) { arbitrary::<int>() } else { ((((((((((v && (arbitrary::<int>() == 2508597854int)) && (arbitrary::<int>() == Set::<int>::empty())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) }))
}

/// Send2b operator
pub open spec fn LSend2b(s: LState, c: LConstants, s_: int, b: int, v: int) -> bool {
    ((((((((((((b >= arbitrary::<int>()) && (arbitrary::<int>() == b)) && (arbitrary::<int>() == b)) && (arbitrary::<int>() == v)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>()))
}

/// RecvAccepted operator
pub open spec fn LRecvAccepted(s: LState, c: LConstants, s_: int, a: int) -> bool {
    ((((((((((((((arbitrary::<int>() == 2508597854int) && arbitrary::<int>().contains(a)) && arbitrary::<int>().contains(!(a))) && (arbitrary::<int>() == arbitrary::<int>().union(set![a]))) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == 2508597854int)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>()))
}

/// Learn operator
pub open spec fn LLearn(s: LState, c: LConstants, s_: int) -> bool {
    (((((((((((((arbitrary::<int>() == 2508597854int) && (arbitrary::<int>().len() >= arbitrary::<int>())) && (arbitrary::<int>() == 8313578207int)) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>())) && (arbitrary::<int>() == arbitrary::<int>()))
}

/// Next operator
pub open spec fn LNext(s: LState, c: LConstants, s_: int) -> bool {
    exists |b| (LSend1a(s, c, s, s_, c, b) || exists |b| (LSend1b(s, c, s, s_, c, b) || exists |a, ab, av| (LRecvPromise(s, c, s, s_, c, a, ab, av) || exists |v| (LSend2a(s, c, s, s_, c, v) || exists |b, v| (LSend2b(s, c, s, s_, c, b, v) || exists |a| (LRecvAccepted(s, c, s, s_, c, a) || LLearn(s, c, s, s_, c)))))))
}

} // verus!
