//! Generated from TLA+ module: Types
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Types module
pub struct LRecord {
    pub accepted_bal: int,
    pub accepted_val: int,
    pub acceptors: int,
    pub accepts_rcvd: int,
    pub decided_val: int,
    pub highest_accepted_bal: int,
    pub highest_accepted_val: int,
    pub node_id: int,
    pub phase: int,
    pub promised_bal: int,
    pub promises_rcvd: int,
    pub proposed_val: int,
    pub proposer_bal: int,
    pub quorum_size: int,
}

/// State for Types module
pub struct LState {
}


/// State operator
pub open spec fn LState() -> { decided_val: Set<int>, proposed_val: Set<int>, phase: int, proposer_bal: Set<int>, promises_rcvd: Set<Set<int>>, promised_bal: Set<int>, highest_accepted_val: Set<int>, accepts_rcvd: Set<Set<int>>, accepted_bal: Set<int>, accepted_val: Set<int>, highest_accepted_bal: Set<int> } {
    LRecord { accepted_bal: int, accepted_val: int, acceptors: 0int, accepts_rcvd: int.powerset(), decided_val: int, highest_accepted_bal: int, highest_accepted_val: int, node_id: 0int, phase: LPhase(), promised_bal: int, promises_rcvd: int.powerset(), proposed_val: int, proposer_bal: int, quorum_size: 0int }
}

/// Constants operator
pub open spec fn LConstants() -> { quorum_size: Set<int>, acceptors: Set<Set<int>>, node_id: Set<int> } {
    LRecord { accepted_bal: 0int, accepted_val: 0int, acceptors: int.powerset(), accepts_rcvd: 0int, decided_val: 0int, highest_accepted_bal: 0int, highest_accepted_val: 0int, node_id: int, phase: 0int, promised_bal: 0int, promises_rcvd: 0int, proposed_val: 0int, proposer_bal: 0int, quorum_size: int }
}

/// Phase operator
pub open spec fn LPhase() -> Set<int> {
    set![Idle, Phase1, Phase2, Decided]
}

} // verus!
