//! Generated from TLA+ module: Types
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Types module
pub struct LRecord {
    pub accepted_bal: int,
    pub accepted_val: int,
    pub acceptors: int,
    pub accepts_rcvd: int,
    pub decided_val: int,
    pub highest_accepted_bal: int,
    pub highest_accepted_val: int,
    pub node_id: int,
    pub phase: int,
    pub promised_bal: int,
    pub promises_rcvd: int,
    pub proposed_val: int,
    pub proposer_bal: int,
    pub quorum_size: int,
}

/// State for Types module
pub struct LState {
}


/// State operator
pub open spec fn LState() -> LRecord {
    LRecord { accepted_bal: arbitrary(), accepted_val: arbitrary(), acceptors: 0int, accepts_rcvd: int.powerset(), decided_val: arbitrary(), highest_accepted_bal: arbitrary(), highest_accepted_val: arbitrary(), node_id: 0int, phase: LPhase(), promised_bal: arbitrary(), promises_rcvd: int.powerset(), proposed_val: arbitrary(), proposer_bal: arbitrary(), quorum_size: 0int }
}

/// Constants operator
pub open spec fn LConstants() -> LRecord {
    LRecord { accepted_bal: 0int, accepted_val: 0int, acceptors: int.powerset(), accepts_rcvd: 0int, decided_val: 0int, highest_accepted_bal: 0int, highest_accepted_val: 0int, node_id: arbitrary(), phase: 0int, promised_bal: 0int, promises_rcvd: 0int, proposed_val: 0int, proposer_bal: 0int, quorum_size: arbitrary() }
}

/// Phase operator
pub open spec fn LPhase() -> Set<int> {
    set![5126177779int, 9996969643int, 2508597854int, 8313578207int]
}

} // verus!
