// Test for generated loop patterns with invariants
// This tests the exact code structure generated by the transpiler's loop generation
// Verifies: map filtering loop with ghost state tracking

use vstd::prelude::*;
use vstd::map::*;
use vstd::set::*;
use std::collections::HashMap;

verus! {
    // === TYPES ===
    // Using concrete types to match the generated code
    pub type COperationNumber = i64;
    pub type CVote = i64;

    // Helper lemma for proving seen_keys == dom after iteration
    // This is a trusted set theory lemma (same as in src/common/collections/sets.rs)
    #[verifier::external_body]
    pub proof fn subset_len_equal_implies_equal<A>(s1: Set<A>, s2: Set<A>)
        requires
            s1.subset_of(s2),
            s1.len() == s2.len(),
        ensures
            s1 == s2
    {}

    // === SPEC PREDICATE ===
    // RemoveVotesBeforeLogTruncationPoint pattern
    // Using i64 directly for simplicity
    pub open spec fn RemoveVotesBeforeLogTruncationPoint(
        votes: Map<COperationNumber, CVote>,
        votes_: Map<COperationNumber, CVote>,
        log_truncation_point: COperationNumber
    ) -> bool {
        &&& (forall |opn: COperationNumber| votes_.contains_key(opn) ==> votes.contains_key(opn) && votes_[opn] == votes[opn])
        &&& (forall |opn: COperationNumber| opn < log_truncation_point ==> !votes_.contains_key(opn))
        &&& (forall |opn: COperationNumber| opn >= log_truncation_point && votes.contains_key(opn) ==> votes_.contains_key(opn))
    }

    // === EXEC FUNCTION WITH GENERATED LOOP ===
    // This follows the exact structure produced by the transpiler's loop generation

    pub fn c_remove_votes_before_log_truncation_point(
        votes: &HashMap<COperationNumber, CVote>,
        log_truncation_point: COperationNumber
    ) -> (result: HashMap<COperationNumber, CVote>)
        requires
            votes@.dom().finite(),
        ensures
            RemoveVotesBeforeLogTruncationPoint(votes@, result@, log_truncation_point)
    {
        broadcast use vstd::std_specs::hash::group_hash_axioms;

        let votes_keys = votes.keys();
        assert(votes_keys@.0 == 0);
        assume(votes_keys@.1.len() == votes@.len());
        assert(votes_keys@.1.to_set() =~= votes@.dom());

        let ghost mut seen_keys: Set<COperationNumber> = Set::empty();
        let mut result: HashMap<COperationNumber, CVote> = HashMap::new();

        for opn in iter:votes_keys
        invariant
            seen_keys.subset_of(votes@.dom()),
            forall |k: COperationNumber| seen_keys.contains(k) ==> votes@.contains_key(k),
            forall |k: COperationNumber| result@.contains_key(k) ==> (k >= log_truncation_point) && votes@.contains_key(k),
            forall |k: COperationNumber| result@.contains_key(k) ==> seen_keys.contains(k),
            forall |k: COperationNumber| seen_keys.contains(k) && (k >= log_truncation_point) ==> result@.contains_key(k),
        {
            broadcast use vstd::std_specs::hash::group_hash_axioms;
            assume(votes@.contains_key(*opn));
            proof{seen_keys = seen_keys.insert(*opn)};
            if *opn >= log_truncation_point {
                let value = votes.get(opn);
                match value {
                    Some(v) => { result.insert(*opn, (*v).clone()); },
                    None => {},
                }
            }
        }

        assert(seen_keys.subset_of(votes@.dom()));
        assume(votes_keys@.0 == votes_keys@.1.len());
        assume(seen_keys.len() == votes_keys@.0 as nat);
        proof{subset_len_equal_implies_equal(seen_keys, votes@.dom())};
        assert(seen_keys == votes@.dom());

        result
    }
}

fn main() {
    println!("Generated loop test compiles!");
}
