// Auto-generated by verus-transpiler
// DO NOT EDIT MANUALLY

verus! {

pub exec fn CAcceptorInit(c: &CReplicaConstants) -> (result: CAcceptor)
requires
    c.well_formed(),
ensures
    result.well_formed(),
    LAcceptorInit(result@, c@),
{
CAcceptor {
        constants: c,
        log_truncation_point: 0,
        max_bal: CMaxBal {
            seqno: 0,
            proposer_id: 0,
        },
    }
}

} // verus!
