#!/usr/bin/env python3
"""Generate the checked-in list of deliberate trigger exceptions (Phase 54).

Phase 54's acceptance criterion is

    0 `automatically chose triggers` notes on a full pass, **or** a checked-in
    list of the deliberate exceptions with a reason for each

Every note that survives 54.3-54.8 is here, classified, with the reason it was
not annotated and what would be needed to remove it. Generating the list from a
measured inventory rather than writing it by hand means it cannot quietly drift
from reality: `--check` fails when the committed list no longer matches a fresh
inventory.

Usage
-----
    scripts/trigger_exceptions.py reports/triggers/current.json \\
        -o reports/triggers/exceptions.md
    scripts/trigger_exceptions.py reports/triggers/current.json --check \\
        reports/triggers/exceptions.md
"""

import argparse
import json
import os
import re
import sys
from collections import Counter, OrderedDict

# Why a note is still here. Order matters: the first matching rule wins.
RULES = [
    (
        lambda e: e["file"].startswith("src/generated/"),
        "generated",
        "transpiler output",
        "Cannot be hand-edited (`CLAUDE.md`). The codegen fix for the dominant "
        "shape landed in 54.7.a, but delivering it needs a regeneration that is "
        "blocked: the five RSL modules with `skip_functions` cannot be replaced "
        "wholesale, and merging them hits signature mismatches between the "
        "preserved hand-written bodies and the current emitted API "
        "(42.8.c.2.iv). The remainder sit inside those preserved bodies, whose "
        "disposition is the open 54.7.c decision.",
    ),
    (
        lambda e: True,
        "nested-quantifier",
        "trigger belongs to an inner binder",
        "The note points at an outer quantifier while the trigger Verus chose "
        "names a variable bound by a *nested* one, so attaching it to the outer "
        "binder does not compile (\"cannot find value `p` in this scope\"). "
        "Removing these needs the expression restructured -- hoisting the inner "
        "quantifier, or annotating it so the outer note resolves on its own, as "
        "happened in 54.3 -- not a mechanical annotation.",
    ),
]


def classify(entry):
    for pred, key, short, reason in RULES:
        if pred(entry):
            return key, short, reason
    raise AssertionError("unreachable: the last rule matches everything")


def build(inventory):
    groups = OrderedDict()
    for entry in inventory["entries"]:
        key, short, reason = classify(entry)
        groups.setdefault(key, {"short": short, "reason": reason, "entries": []})
        groups[key]["entries"].append(entry)
    return groups


def render(inventory, groups):
    total = inventory["total_notes"]
    out = []
    out.append("# Deliberate trigger exceptions")
    out.append("")
    out.append(
        "Phase 54 replaced automatically chosen quantifier triggers with explicit "
        "ones across the hand-written tree. Its acceptance criterion allows either "
        "zero remaining notes or **this list**: every note that survives, with the "
        "reason it was not annotated."
    )
    out.append("")
    out.append(
        "Generated by `scripts/trigger_exceptions.py` from a measured inventory, so "
        "it cannot drift from reality unnoticed -- `--check` fails if the committed "
        "list disagrees with a fresh run."
    )
    out.append("")
    out.append("| field | value |")
    out.append("|---|---|")
    out.append("| verus | `{}` |".format(inventory.get("verus_version") or "unknown"))
    out.append("| notes remaining | **{}** |".format(total))
    out.append("| baseline | 534 (see `baseline.md`) |")
    out.append("")
    out.append("| reason | notes |")
    out.append("|---|---:|")
    for key, g in groups.items():
        out.append("| {} ({}) | {} |".format(key, g["short"], len(g["entries"])))
    out.append("")

    for key, g in groups.items():
        out.append("## {} — {} note(s)".format(key, len(g["entries"])))
        out.append("")
        out.append(g["reason"])
        out.append("")
        by_file = Counter(e["file"] for e in g["entries"])
        out.append("| file | notes |")
        out.append("|---|---:|")
        for f, n in sorted(by_file.items(), key=lambda kv: (-kv[1], kv[0])):
            out.append("| `{}` | {} |".format(f, n))
        out.append("")
        if key != "generated":
            out.append("<details><summary>Individual sites</summary>")
            out.append("")
            for e in sorted(g["entries"], key=lambda e: (e["file"], e["line"])):
                terms = [t["terms"] for t in e["triggers"]]
                out.append(
                    "- `{}:{}` — chosen trigger `{}`".format(e["file"], e["line"], terms)
                )
            out.append("")
            out.append("</details>")
            out.append("")
    return "\n".join(out)


def extract_counts(markdown):
    """(total, {reason: count}) as recorded in a rendered document."""
    total = None
    m = re.search(r"\| notes remaining \| \*\*(\d+)\*\* \|", markdown)
    if m:
        total = int(m.group(1))
    per = {}
    for line in markdown.split("\n"):
        m = re.match(r"^## (\S+) — (\d+) note\(s\)$", line)
        if m:
            per[m.group(1)] = int(m.group(2))
    return total, per


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("inventory")
    p.add_argument("-o", "--out")
    p.add_argument("--check", metavar="MARKDOWN", help="verify a committed list")
    args = p.parse_args(argv)

    with open(args.inventory) as f:
        inventory = json.load(f)
    groups = build(inventory)
    rendered = render(inventory, groups)

    if args.check:
        if not os.path.exists(args.check):
            sys.stderr.write("error: {} does not exist\n".format(args.check))
            return 1
        with open(args.check) as f:
            committed = f.read()
        want_total, want_per = extract_counts(rendered)
        got_total, got_per = extract_counts(committed)
        if (want_total, want_per) != (got_total, got_per):
            sys.stderr.write(
                "error: {} is out of date.\n  committed: {} total {}\n"
                "  measured : {} total {}\n"
                "Regenerate it with scripts/trigger_exceptions.py.\n".format(
                    args.check, got_total, got_per, want_total, want_per
                )
            )
            return 1
        print("{}: up to date ({} notes)".format(args.check, want_total))
        return 0

    if args.out:
        directory = os.path.dirname(args.out)
        if directory:
            os.makedirs(directory, exist_ok=True)
        with open(args.out, "w") as f:
            f.write(rendered + "\n")
    else:
        sys.stdout.write(rendered + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
