// Auto-generated by verus-transpiler
// DO NOT EDIT MANUALLY

use std::collections::HashSet;
use vstd::prelude::*;

verus! {

#[derive(Clone)]
pub struct CConstants {
    pub Constants: i64,
    pub State: i64,
    pub PBMessage: i64,
}

impl CConstants {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CConstants {
    type V = LConstants;

    open spec fn view(&self) -> LConstants {
        LConstants {
            Constants: self.Constants as int,
            State: self.State as int,
            PBMessage: self.PBMessage as int,
        }
    }
}

#[derive(Clone)]
pub struct CRecord {
    pub val: i64,
}

impl CRecord {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CRecord {
    type V = LRecord;

    open spec fn view(&self) -> LRecord {
        LRecord {
            val: self.val as int,
        }
    }
}

#[derive(Clone)]
pub struct CState {
}

impl CState {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CState {
    type V = LState;

    open spec fn view(&self) -> LState {
        LState {
        }
    }
}

pub exec fn CInit(s: &i64) -> (result: CConstants)
requires
    Carbitrary::<int>() == 6049598361,
    Carbitrary::<int>() == 0,
    Carbitrary::<int>() == 0,
    Carbitrary::<bool>() == false,
    Carbitrary::<int>() == 0,
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == 0,
    Carbitrary::<int>() == 0,
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == 0,
ensures
    result.well_formed(),
    LInit(result@, *s as int),
{
    assume(false);
    ((((((((((Carbitrary::<int>() == 6049598361) && (Carbitrary::<int>() == 0)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<bool>() == false)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == 0))

}

pub exec fn CPrimaryWrite(s: &CState, c: &CConstants, val: &i64, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<int>() == 6049598361,
    Carbitrary::<bool>() == true,
    Carbitrary::<bool>() == false,
    (Carbitrary::<int>() < Carbitrary::<int>()),
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == *val,
    Carbitrary::<bool>() == false,
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    sent_packets == Seq::<int>::empty(),
ensures
    result.well_formed(),
    LPrimaryWrite(s@, result@, c@, *val as int, sent_packets@),
{
    assume(false);
    (((((((((((((((Carbitrary::<int>() == 6049598361) && (Carbitrary::<bool>() == true)) && (Carbitrary::<bool>() == false)) && (Carbitrary::<int>() < Carbitrary::<int>())) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == *val)) && (Carbitrary::<bool>() == false)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (sent_packets == vec![]))

}

pub exec fn CPrimarySendReplicate(s: &CState, c: &CConstants, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<int>() == 6049598361,
    Carbitrary::<bool>() == true,
    Carbitrary::<bool>() == false,
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    sent_packets == Carbitrary::<Seq<int>>(),
ensures
    result.well_formed(),
    LPrimarySendReplicate(s@, result@, c@, sent_packets@),
{
    assume(false);
    ((((((((((((((Carbitrary::<int>() == 6049598361) && (Carbitrary::<bool>() == true)) && (Carbitrary::<bool>() == false)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (sent_packets == Carbitrary::<Seq<int>>()))

}

pub exec fn CBackupReceiveReplicate(s: &CState, c: &CConstants, val: &i64, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<int>() == 6049598361,
    Carbitrary::<int>() == (Carbitrary::<int>() + 1),
    Carbitrary::<int>() == *val,
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    sent_packets == Seq::<int>::empty(),
ensures
    result.well_formed(),
    LBackupReceiveReplicate(s@, result@, c@, *val as int, sent_packets@),
{
    assume(false);
    ((((((((((((Carbitrary::<int>() == 6049598361) && (Carbitrary::<int>() == (Carbitrary::<int>() + 1))) && (Carbitrary::<int>() == *val)) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (sent_packets == vec![]))

}

pub exec fn CBackupSendAck(s: &CState, c: &CConstants, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<int>() == 6049598361,
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    sent_packets == SeqLit([Literal(Int(7544150754))]),
ensures
    result.well_formed(),
    LBackupSendAck(s@, result@, c@, sent_packets@),
{
    assume(false);
    (((((((((((((Carbitrary::<int>() == 6049598361) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (sent_packets == vec![7544150754]))

}

pub exec fn CPrimaryReceiveAck(s: &CState, c: &CConstants, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<int>() == 6049598361,
    Carbitrary::<bool>() == true,
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    sent_packets == Seq::<int>::empty(),
ensures
    result.well_formed(),
    LPrimaryReceiveAck(s@, result@, c@, sent_packets@),
{
    assume(false);
    (((((((((((((Carbitrary::<int>() == 6049598361) && (Carbitrary::<bool>() == true)) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (sent_packets == vec![]))

}

pub exec fn CPrimaryCommit(s: &CState, c: &CConstants, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<int>() == 6049598361,
    Carbitrary::<bool>() == true,
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == (Carbitrary::<int>() + 1),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<bool>() == false,
    Carbitrary::<int>() == 0,
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    sent_packets == Seq::<int>::empty(),
ensures
    result.well_formed(),
    LPrimaryCommit(s@, result@, c@, sent_packets@),
{
    assume(false);
    ((((((((((((((Carbitrary::<int>() == 6049598361) && (Carbitrary::<bool>() == true)) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == (Carbitrary::<int>() + 1))) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<bool>() == false)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (sent_packets == vec![]))

}

pub exec fn CPrimaryFail(s: &CState, c: &CConstants, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<int>() == 6049598361,
    Carbitrary::<int>() == 1048442360,
    Carbitrary::<bool>() == false,
    Carbitrary::<int>() == 0,
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<bool>() == false,
    Carbitrary::<int>() == Carbitrary::<int>(),
    sent_packets == Seq::<int>::empty(),
ensures
    result.well_formed(),
    LPrimaryFail(s@, result@, c@, sent_packets@),
{
    assume(false);
    ((((((((((((Carbitrary::<int>() == 6049598361) && (Carbitrary::<int>() == 1048442360)) && (Carbitrary::<bool>() == false)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<bool>() == false)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (sent_packets == vec![]))

}

pub exec fn CBackupPromote(s: &CState, c: &CConstants, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<int>() == 1048442360,
    Carbitrary::<int>() == 6049598361,
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<bool>() == false,
    Carbitrary::<int>() == 0,
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == (Carbitrary::<int>() + 1),
    sent_packets == Seq::<int>::empty(),
ensures
    result.well_formed(),
    LBackupPromote(s@, result@, c@, sent_packets@),
{
    assume(false);
    ((((((((((((Carbitrary::<int>() == 1048442360) && (Carbitrary::<int>() == 6049598361)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<bool>() == false)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == (Carbitrary::<int>() + 1))) && (sent_packets == vec![]))

}

// TRANSLATE-TODO: not functionalizable: Exists quantifier with 2 variables (val, sent_packets) not supported (only single-variable exists can be converted to executable code)
#[verifier(external_body)]
pub exec fn CNext(s: &CState, c: &CConstants) -> (result: CState)
ensures
    result.well_formed(),
    LNext(s@, result@, c@),
{
    unimplemented!()
}

} // verus!
