// Auto-generated by verus-transpiler
// DO NOT EDIT MANUALLY

use std::collections::HashSet;
use vstd::prelude::*;

verus! {

#[derive(Clone)]
pub struct CConstants {
    pub VPMessage: i64,
    pub State: i64,
    pub Constants: i64,
}

impl CConstants {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CConstants {
    type V = LConstants;

    open spec fn view(&self) -> LConstants {
        LConstants {
            VPMessage: self.VPMessage as int,
            State: self.State as int,
            Constants: self.Constants as int,
        }
    }
}

#[derive(Clone)]
pub struct CRecord {
    pub bal: i64,
    pub v_bal: i64,
    pub val: i64,
}

impl CRecord {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CRecord {
    type V = LRecord;

    open spec fn view(&self) -> LRecord {
        LRecord {
            bal: self.bal as int,
            v_bal: self.v_bal as int,
            val: self.val as int,
        }
    }
}

#[derive(Clone)]
pub struct CState {
}

impl CState {
    pub open spec fn well_formed(&self) -> bool {
        true
    }
}

impl View for CState {
    type V = LState;

    open spec fn view(&self) -> LState {
        LState {
        }
    }
}

pub exec fn CInit(s: &i64) -> (result: CConstants)
requires
    Carbitrary::<int>() == 0,
    Carbitrary::<int>() == 0,
    Carbitrary::<int>() == 0,
    Carbitrary::<int>() == 0,
    Carbitrary::<bool>() == false,
    Carbitrary::<bool>() == true,
    Set::<int>::empty() == Set::<int>::empty(),
    Set::<int>::empty() == Set::<int>::empty(),
    Carbitrary::<bool>() == false,
    Carbitrary::<int>() == 0,
    Carbitrary::<int>() == 0,
    Carbitrary::<bool>() == false,
    (Carbitrary::<int>() >= 1),
    (Carbitrary::<int>() >= Carbitrary::<int>()),
ensures
    result.well_formed(),
    LInit(result@, *s as int),
{
    assume(false);
    ((((((((((((((Carbitrary::<int>() == 0) && (Carbitrary::<int>() == 0)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<bool>() == false)) && (Carbitrary::<bool>() == true)) && (HashSet::new() == HashSet::new())) && (HashSet::new() == HashSet::new())) && (Carbitrary::<bool>() == false)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<bool>() == false)) && (Carbitrary::<int>() >= 1)) && (Carbitrary::<int>() >= Carbitrary::<int>()))

}

pub exec fn CPrepare(s: &CState, c: &CConstants, b: &i64, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<bool>() == true,
    (*b > Carbitrary::<int>()),
    Carbitrary::<int>() == *b,
    sent_packets == Carbitrary::<Seq<int>>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
ensures
    result.well_formed(),
    LPrepare(s@, result@, c@, *b as int, sent_packets@),
{
    assume(false);
    (((((((((((((((Carbitrary::<bool>() == true) && (*b > Carbitrary::<int>())) && (Carbitrary::<int>() == *b)) && (sent_packets == Carbitrary::<Seq<int>>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>()))

}

pub exec fn CSendPromise(s: &CState, c: &CConstants, prepare_bal: &i64, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<bool>() == true,
    (*prepare_bal > Carbitrary::<int>()),
    Carbitrary::<int>() == *prepare_bal,
    sent_packets == Carbitrary::<Seq<int>>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
ensures
    result.well_formed(),
    LSendPromise(s@, result@, c@, *prepare_bal as int, sent_packets@),
{
    assume(false);
    (((((((((((((((Carbitrary::<bool>() == true) && (*prepare_bal > Carbitrary::<int>())) && (Carbitrary::<int>() == *prepare_bal)) && (sent_packets == Carbitrary::<Seq<int>>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>()))

}

pub exec fn CReceivePromise(s: &CState, c: &CConstants, sender: &i64, promise_bal: &i64, promise_v_bal: &i64, promise_val: bool, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<bool>() == true,
    *promise_bal == Carbitrary::<int>(),
    !Set::<int>::empty()@.contains(*sender as int),
    Set::<int>::empty() == Set::<int>::empty().union(set![sender]),
    Carbitrary::<int>() == Carbitrary::<int>(),
ensures
    result.well_formed(),
    LReceivePromise(s@, result@, c@, *sender as int, *promise_bal as int, *promise_v_bal as int, promise_val, sent_packets@),
{
    assume(false);
    (((((Carbitrary::<bool>() == true) && (*promise_bal == Carbitrary::<int>())) && !contains(&HashSet::new(), sender)) && (HashSet::new() ==     let mut __hs = HashSet::new().clone();
    __hs.insert(*sender);
    __hs
)) && (Carbitrary::<int>() == Carbitrary::<int>()))

}

pub exec fn CAccept(s: &CState, c: &CConstants, b: &i64, v: &i64, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<bool>() == true,
    *b == Carbitrary::<int>(),
    (*b > Carbitrary::<int>()),
    Carbitrary::<int>() == *b,
    Carbitrary::<int>() == *v,
    Carbitrary::<bool>() == true,
    sent_packets == Carbitrary::<Seq<int>>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
ensures
    result.well_formed(),
    LAccept(s@, result@, c@, *b as int, *v as int, sent_packets@),
{
    assume(false);
    ((((((((((((((((Carbitrary::<bool>() == true) && (*b == Carbitrary::<int>())) && (*b > Carbitrary::<int>())) && (Carbitrary::<int>() == *b)) && (Carbitrary::<int>() == *v)) && (Carbitrary::<bool>() == true)) && (sent_packets == Carbitrary::<Seq<int>>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>()))

}

pub exec fn CReceiveAccepted(s: &CState, c: &CConstants, sender: &i64, accept_bal: &i64, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<bool>() == true,
    *accept_bal == Carbitrary::<int>(),
    !Set::<int>::empty()@.contains(*sender as int),
    Set::<int>::empty() == Set::<int>::empty().union(set![sender]),
    sent_packets == Seq::<int>::empty(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
ensures
    result.well_formed(),
    LReceiveAccepted(s@, result@, c@, *sender as int, *accept_bal as int, sent_packets@),
{
    assume(false);
    ((((((((((((((((Carbitrary::<bool>() == true) && (*accept_bal == Carbitrary::<int>())) && !contains(&HashSet::new(), sender)) && (HashSet::new() ==     let mut __hs = HashSet::new().clone();
    __hs.insert(*sender);
    __hs
)) && (sent_packets == vec![])) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>()))

}

pub exec fn CCommit(s: &CState, c: &CConstants, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<bool>() == true,
    Carbitrary::<bool>() == false,
    (Carbitrary::<Seq<int>>().len() as int >= Carbitrary::<int>()),
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == Carbitrary::<int>(),
    sent_packets == Seq::<int>::empty(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
ensures
    result.well_formed(),
    LCommit(s@, result@, c@, sent_packets@),
{
    assume(false);
    ((((((((((((((((Carbitrary::<bool>() == true) && (Carbitrary::<bool>() == false)) && ((Carbitrary::<Seq<int>>().len() as i64) >= Carbitrary::<int>())) && (Carbitrary::<bool>() == true)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (sent_packets == vec![])) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>()))

}

pub exec fn CReconfigure(s: &CState, c: &CConstants, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<bool>() == true,
    Carbitrary::<int>() == (Carbitrary::<int>() + 1),
    Carbitrary::<int>() == 0,
    Carbitrary::<int>() == 0,
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<bool>() == false,
    Carbitrary::<bool>() == true,
    Set::<int>::empty() == Set::<int>::empty(),
    Set::<int>::empty() == Set::<int>::empty(),
    sent_packets == Seq::<int>::empty(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
ensures
    result.well_formed(),
    LReconfigure(s@, result@, c@, sent_packets@),
{
    assume(false);
    ((((((((((((((Carbitrary::<bool>() == true) && (Carbitrary::<int>() == (Carbitrary::<int>() + 1))) && (Carbitrary::<int>() == 0)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<bool>() == false)) && (Carbitrary::<bool>() == true)) && (HashSet::new() == HashSet::new())) && (HashSet::new() == HashSet::new())) && (sent_packets == vec![])) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>()))

}

pub exec fn CWitnessSync(s: &CState, c: &CConstants, witness_val: bool, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<bool>() == true,
    Carbitrary::<bool>() == true,
    Carbitrary::<bool>() == witness_val,
    Carbitrary::<bool>() == If { cond: Not(Call { func: Path { segments: ["arbitrary::<bool>"] }, args: [] }), then_branch: Ident("witness_val"), else_branch: Some(Binary(Binary(Binary(Binary(Binary(Binary(Binary(Binary(Binary(Binary(Call { func: Path { segments: ["arbitrary"] }, args: [] }, And, Eq(Ident("sent_packets"), Call { func: Path { segments: ["Seq::<int>", "empty"] }, args: [] })), And, Eq(Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] }, Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] })), And, Eq(Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] }, Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] })), And, Eq(Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] }, Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] })), And, Eq(Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] }, Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] })), And, Eq(Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] }, Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] })), And, Eq(Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] }, Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] })), And, Eq(Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] }, Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] })), And, Eq(Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] }, Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] })), And, Eq(Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] }, Call { func: Path { segments: ["arbitrary::<int>"] }, args: [] }))) },
ensures
    result.well_formed(),
    LWitnessSync(s@, result@, c@, witness_val, sent_packets@),
{
    assume(false);
    ((((Carbitrary::<bool>() == true) && (Carbitrary::<bool>() == true)) && (Carbitrary::<bool>() == witness_val)) && (Carbitrary::<bool>() == if !Carbitrary::<bool>() {
        witness_val
    } else {
        ((((((((((Carbitrary() && (sent_packets == vec![])) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>()))
    }))

}

pub exec fn CSync(s: &CState, c: &CConstants, new_config: &i64, val: &i64, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<bool>() == false,
    (*new_config > Carbitrary::<int>()),
    Carbitrary::<int>() == *new_config,
    Carbitrary::<int>() == 0,
    Carbitrary::<int>() == 0,
    Carbitrary::<int>() == *val,
    Carbitrary::<bool>() == false,
    Carbitrary::<bool>() == true,
    Set::<int>::empty() == Set::<int>::empty(),
    Set::<int>::empty() == Set::<int>::empty(),
    Carbitrary::<bool>() == false,
    Carbitrary::<int>() == 0,
    Carbitrary::<int>() == 0,
    Carbitrary::<bool>() == false,
    sent_packets == Seq::<int>::empty(),
ensures
    result.well_formed(),
    LSync(s@, result@, c@, *new_config as int, *val as int, sent_packets@),
{
    assume(false);
    (((((((((((((((Carbitrary::<bool>() == false) && (*new_config > Carbitrary::<int>())) && (Carbitrary::<int>() == *new_config)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<int>() == *val)) && (Carbitrary::<bool>() == false)) && (Carbitrary::<bool>() == true)) && (HashSet::new() == HashSet::new())) && (HashSet::new() == HashSet::new())) && (Carbitrary::<bool>() == false)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<int>() == 0)) && (Carbitrary::<bool>() == false)) && (sent_packets == vec![]))

}

pub exec fn CDeactivate(s: &CState, c: &CConstants, sent_packets: &Vec<i64>) -> (result: CState)
requires
    s.well_formed(),
    c.well_formed(),
    Carbitrary::<bool>() == true,
    Carbitrary::<bool>() == false,
    sent_packets == Seq::<int>::empty(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
    Carbitrary::<int>() == Carbitrary::<int>(),
ensures
    result.well_formed(),
    LDeactivate(s@, result@, c@, sent_packets@),
{
    assume(false);
    ((((((((((((((Carbitrary::<bool>() == true) && (Carbitrary::<bool>() == false)) && (sent_packets == vec![])) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>())) && (Carbitrary::<int>() == Carbitrary::<int>()))

}

// TRANSLATE-TODO: not functionalizable: Exists quantifier with 2 variables (b, sent_packets) not supported (only single-variable exists can be converted to executable code)
#[verifier(external_body)]
pub exec fn CNext(s: &CState, c: &CConstants) -> (result: CState)
ensures
    result.well_formed(),
    LNext(s@, result@, c@),
{
    unimplemented!()
}

} // verus!
