//! Golden: the **whole** Jetpack, three modules, projected to one Verus spec.
//!
//! What this case shows that `tier3/t3_01_jetpack` does not:
//!
//! - it is the **fast path** as well as recovery — `ClientSendPreaccept`,
//!   `HandlePreaccept{Request,Response}`, `Resubmit`, `HandleFinishRecovery`
//!   and the client-side quorum counting, none of which the slice had;
//! - it is a genuine **multi-module composition**: two library modules with no
//!   `Init`/`Next` of their own, INSTANCEd by a third, exactly as upstream has
//!   it. The `LB`/`LJ` name prefixes are those INSTANCE qualifiers;
//! - `IsFastQuorum` is the closed form derived in TODO.md 55.3.a, which is what
//!   made the fast path projectable at all.
//!
//! Two shapes here appear in no other golden, and both are worth reading:
//!
//! - **`LHandleMessage` disjoins per variant.** `LBUpdateTerm` handles all four
//!   Raft message types, and `Aeq` is claimed by three actions. One `match` arm
//!   per variant, `||` between the handlers — because a second arm for a
//!   variant is unreachable and would silently drop a handler.
//! - **`LBAdvanceCommitIndex`'s quantifier is re-indexed from 0.** The source
//!   binds `\E k \in 1 .. Len(log[i])`; emitting that literally gives
//!   `s.log[k - 1]`, and Verus will not infer a trigger from a subscript with
//!   arithmetic in it. Quantifying one lower and writing `k + 1` elsewhere is
//!   the same set of witnesses in the only form Verus accepts.
//!
//! Verified with Verus 0.2026.08.02.b677dd5: `0 verified, 0 errors` — a
//! spec-only file has no proof obligations, so that *is* the typecheck.

//! Single-process Verus spec projected from TLA+ module `jetpack_raft_clean`.
//!
//! Generated by `verus-transpile clean-tla`. Do not edit by hand: the
//! clean-subset spec it came from is the source of truth.

use vstd::prelude::*;

verus! {
    pub enum LOstate {
        Follower,
        Candidate,
        ToBeLeader,
        Leader,
        NotMember,
    }

    pub enum LBEntryCommand {
        Append,
        InitCluster,
        AddServer,
        RemoveServer,
    }

    pub enum LPendingReconfigOp {
        Add,
        Remove,
        None,
    }

    pub enum LJstate {
        Ready,
        Recovery,
        AfterBeginRecovery,
        AfterPrepare,
        AfterAccept,
        AfterResubmit,
    }

    pub enum LAepMresult {
        Ok,
        StaleTerm,
        EntryMismatch,
    }

    pub struct LBEntry {
        pub command: LBEntryCommand,
        pub term: int,
        pub value: int,
    }

    pub struct LBConfig {
        pub id: int,
        pub members: Set<int>,
        pub committed: bool,
    }

    pub struct LPendingReconfig {
        pub op: LPendingReconfigOp,
        pub target: int,
    }

    pub struct LJCommand {
        pub cmd_id: int,
        pub key: int,
    }

    /// Wire messages. Routing lives on the packet, not in the payload.
    pub enum LMessage {
        Rvq { mterm: int, mlast_log_term: int, mlast_log_index: int },
        Rvp { mterm: int, mvote_granted: bool },
        Aeq { mterm: int, mprev_log_index: int, mprev_log_term: int, mentries: Seq<LBEntry>, mcommit_index: int },
        Aep { mterm: int, mresult: LAepMresult, mmatch_index: int },
        Paq { mepoch: int, mcmd: LJCommand },
        Pap { mcmd: LJCommand, msuccess: bool, mjepoch: int, mview_epoch: int, mview_members: Set<int>, mview_proposers: Set<int> },
        Brq { mjepoch: int, mview_epoch: int, mview_members: Set<int>, mview_proposers: Set<int> },
        Brp { maccepted_ballot: int, maccepted_value: Set<LJCommand> },
        Pq { mballot: int, moepoch: int },
        Pp { maccepted_ballot: int, maccepted_value: Set<LJCommand>, mballot: int },
        Aq { mballot: int, mvalue: Set<LJCommand> },
        Ap { mballot: int },
        Fin { mjepoch: int },
    }

    /// A message addressed to a peer.
    pub struct LPacket {
        pub dst: int,
        pub msg: LMessage,
    }

    /// This node's state.
    pub struct LState {
        pub current_term: int,
        pub ostate: LOstate,
        pub voted_for: int,
        pub log: Seq<LBEntry>,
        pub commit_index: int,
        pub votes_granted: Set<int>,
        pub next_index: Map<int, int>,
        pub match_index: Map<int, int>,
        pub config: LBConfig,
        pub pending_reconfig: LPendingReconfig,
        pub election_ctr: int,
        pub restart_ctr: int,
        pub jstate: LJstate,
        pub jepoch: int,
        pub oepoch: int,
        pub view_epoch: int,
        pub view_members: Set<int>,
        pub view_proposers: Set<int>,
        pub max_seen_ballot: int,
        pub accepted_ballot: int,
        pub accepted_value: Set<LJCommand>,
        pub cmd_pool: Map<int, LJCommand>,
        pub recovery_set: Set<int>,
        pub prep_rcvd: Set<int>,
        pub accept_rcvd: Set<int>,
        pub chosen_value: Set<LJCommand>,
        pub highest_seen_ballot: int,
        pub highest_seen_value: Set<LJCommand>,
        pub client_pending: LJCommand,
        pub client_successes: Set<int>,
        pub client_heard_from: Set<int>,
        pub client_epoch: int,
        pub client_members: Set<int>,
        pub client_proposers: Set<int>,
    }

    /// Protocol constants, including this node's own identity.
    pub struct LConstants {
        pub server: Set<int>,
        pub client: Set<int>,
        pub commands: Set<int>,
        pub key: Set<int>,
        pub max_term: int,
        pub max_log_len: int,
        pub max_elections: int,
        pub max_restarts: int,
        pub node_id: int,
    }

    pub open spec fn LBLastTerm(c: LConstants, xlog: Seq<LBEntry>) -> int {
        if (xlog.len() as int) == 0 { 0 } else { xlog[(xlog.len() as int) - 1].term }
    }

    pub open spec fn LBIsQuorumOf(c: LConstants, s_arg: Set<int>, members: Set<int>) -> bool {
        (s_arg.len() as int) * 2 > (members.len() as int)
    }

    pub open spec fn LJIsQuorum(c: LConstants, s_arg: Set<int>, members: Set<int>) -> bool {
        (s_arg.len() as int) * 2 > (members.len() as int)
    }

    pub open spec fn LJIsFastQuorum(c: LConstants, s_arg: Set<int>, members: Set<int>, proposers: Set<int>) -> bool {
        proposers.subset_of(s_arg) && (if (proposers.len() as int) * 2 > (members.len() as int) { (s_arg.len() as int) * 2 > (members.len() as int) } else { s_arg == members })
    }

    pub open spec fn LJHasConflict(c: LConstants, pool: Map<int, LJCommand>, cmd: LJCommand) -> bool {
        pool.dom().contains(cmd.key) && pool[cmd.key] != cmd
    }

    pub open spec fn LInit(s: LState, c: LConstants) -> bool {
        &&& s.current_term == 1
        &&& s.ostate == if c.server.contains(c.node_id) { LOstate::Follower } else { LOstate::NotMember }
        &&& s.voted_for == 0
        &&& s.log == if c.server.contains(c.node_id) { seq![LBEntry { command: LBEntryCommand::InitCluster, term: 0, value: choose|v: int| c.commands.contains(v) && true }] } else { Seq::empty() }
        &&& s.commit_index == if c.server.contains(c.node_id) { 1int } else { 0int }
        &&& s.votes_granted == Set::<int>::empty()
        &&& s.next_index == Map::new(c.server, |j: int| 1int)
        &&& s.match_index == Map::new(c.server, |j: int| 0int)
        &&& s.config == LBConfig { id: 0, members: c.server, committed: true }
        &&& s.pending_reconfig == LPendingReconfig { op: LPendingReconfigOp::None, target: 0 }
        &&& s.election_ctr == 0
        &&& s.restart_ctr == 0
        &&& s.jstate is Ready
        &&& s.jepoch == 0
        &&& s.oepoch == 0
        &&& s.view_epoch == 0
        &&& s.view_members == c.server
        &&& s.view_proposers == c.server
        &&& s.max_seen_ballot == 0
        &&& s.accepted_ballot == 0
        &&& s.accepted_value == Set::<LJCommand>::empty()
        &&& s.cmd_pool == Map::new(c.key, |k: int| LJCommand { cmd_id: 0, key: 0 })
        &&& s.recovery_set == Set::<int>::empty()
        &&& s.prep_rcvd == Set::<int>::empty()
        &&& s.accept_rcvd == Set::<int>::empty()
        &&& s.chosen_value == Set::<LJCommand>::empty()
        &&& s.highest_seen_ballot == 0
        &&& s.highest_seen_value == Set::<LJCommand>::empty()
        &&& s.client_pending == LJCommand { cmd_id: 0, key: 0 }
        &&& s.client_successes == Set::<int>::empty()
        &&& s.client_heard_from == Set::<int>::empty()
        &&& s.client_epoch == 0
        &&& s.client_members == c.server
        &&& s.client_proposers == c.server
    }

    pub open spec fn LPromoteToLeader(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.server.contains(c.node_id)
        &&& s.ostate is ToBeLeader
        &&& s.jstate is Ready
        &&& s_.ostate is Leader
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.current_term == s.current_term
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LBRestart(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& s.restart_ctr < c.max_restarts
        &&& s_.ostate == if s.config.members.contains(c.node_id) { LOstate::Follower } else { LOstate::NotMember }
        &&& s_.votes_granted == Set::<int>::empty()
        &&& s_.next_index == Map::new(c.server, |j: int| 1int)
        &&& s_.match_index == Map::new(c.server, |j: int| 0int)
        &&& s_.commit_index == 0
        &&& s_.pending_reconfig == LPendingReconfig { op: LPendingReconfigOp::None, target: 0 }
        &&& s_.restart_ctr == s.restart_ctr + 1
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.current_term == s.current_term
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.config == s.config
        &&& s_.election_ctr == s.election_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LBUpdateTerm(
        s: LState,
        s_: LState,
        c: LConstants,
        mterm: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& mterm > s.current_term
        &&& s_.current_term == mterm
        &&& s_.ostate is Follower
        &&& s_.voted_for == 0
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LBRequestVote(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& s.election_ctr < c.max_elections
        &&& s.current_term < c.max_term
        &&& s.ostate is Follower || s.ostate is Candidate
        &&& s.config.members.contains(c.node_id)
        &&& s_.ostate is Candidate
        &&& s_.current_term == s.current_term + 1
        &&& s_.voted_for == c.node_id
        &&& s_.votes_granted == set![c.node_id]
        &&& s_.election_ctr == s.election_ctr + 1
        &&& sent_packets == s.config.members.map(|j: int| LPacket { dst: j, msg: LMessage::Rvq { mterm: s.current_term + 1, mlast_log_term: LBLastTerm(c, s.log), mlast_log_index: (s.log.len() as int) } })
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LBHandleRequestVoteRequest(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        mterm: int,
        mlast_log_term: int,
        mlast_log_index: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& mterm <= s.current_term
        &&& s_.voted_for == if mterm == s.current_term && (mlast_log_term > LBLastTerm(c, s.log) || mlast_log_term == LBLastTerm(c, s.log) && mlast_log_index >= (s.log.len() as int)) && set![0, src].contains(s.voted_for) { src } else { s.voted_for }
        &&& sent_packets == set![LPacket { dst: src, msg: LMessage::Rvp { mterm: s.current_term, mvote_granted: mterm == s.current_term && (mlast_log_term > LBLastTerm(c, s.log) || mlast_log_term == LBLastTerm(c, s.log) && mlast_log_index >= (s.log.len() as int)) && set![0, src].contains(s.voted_for) } }]
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LBHandleRequestVoteResponse(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        mterm: int,
        mvote_granted: bool,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& mterm == s.current_term
        &&& s.ostate is Candidate
        &&& s_.votes_granted == if mvote_granted { s.votes_granted.union(set![src]) } else { s.votes_granted }
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LBBecomeToBeLeader(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& s.ostate is Candidate
        &&& LBIsQuorumOf(c, s.votes_granted, s.config.members)
        &&& s_.ostate is ToBeLeader
        &&& s_.next_index == Map::new(c.server, |j: int| (s.log.len() as int) + 1)
        &&& s_.match_index == Map::new(c.server, |j: int| 0int)
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.current_term == s.current_term
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LBClientRequest(
        s: LState,
        s_: LState,
        c: LConstants,
        v: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& s.ostate is Leader
        &&& (s.log.len() as int) < c.max_log_len
        &&& s_.log == s.log.push(LBEntry { command: LBEntryCommand::Append, term: s.current_term, value: v })
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LBAppendEntries(
        s: LState,
        s_: LState,
        c: LConstants,
        j: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.node_id != j
        &&& s.ostate is Leader
        &&& s.config.members.contains(j)
        &&& s.next_index[j] >= 1
        &&& sent_packets == set![LPacket { dst: j, msg: LMessage::Aeq { mterm: s.current_term, mprev_log_index: s.next_index[j] - 1, mprev_log_term: if s.next_index[j] - 1 > 0 { s.log[s.next_index[j] - 1 - 1].term } else { 0 }, mentries: s.log.subrange(s.next_index[j] - 1, if (s.log.len() as int) < s.next_index[j] { (s.log.len() as int) } else { s.next_index[j] }), mcommit_index: if s.commit_index < s.next_index[j] { s.commit_index } else { s.next_index[j] } } }]
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LBRejectAppendEntriesRequest(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        mterm: int,
        mprev_log_index: int,
        mprev_log_term: int,
        mentries: Seq<LBEntry>,
        mcommit_index: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& mterm <= s.current_term
        &&& mterm < s.current_term || mterm == s.current_term && s.ostate is Follower && !(if mentries != Seq::empty() { mprev_log_index > 0 && mprev_log_index <= (s.log.len() as int) && mprev_log_term == s.log[mprev_log_index - 1].term } else { mprev_log_index == (s.log.len() as int) && (mprev_log_index == 0 || mprev_log_index > 0 && mprev_log_term == s.log[mprev_log_index - 1].term) })
        &&& sent_packets == set![LPacket { dst: src, msg: LMessage::Aep { mterm: s.current_term, mresult: if mterm < s.current_term { LAepMresult::StaleTerm } else { LAepMresult::EntryMismatch }, mmatch_index: 0 } }]
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LBAcceptAppendEntriesRequest(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        mterm: int,
        mprev_log_index: int,
        mprev_log_term: int,
        mentries: Seq<LBEntry>,
        mcommit_index: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& mterm == s.current_term
        &&& s.ostate is Follower || s.ostate is Candidate
        &&& if mentries != Seq::empty() { mprev_log_index > 0 && mprev_log_index <= (s.log.len() as int) && mprev_log_term == s.log[mprev_log_index - 1].term } else { mprev_log_index == (s.log.len() as int) && (mprev_log_index == 0 || mprev_log_index > 0 && mprev_log_term == s.log[mprev_log_index - 1].term) }
        &&& (s.log.len() as int) < c.max_log_len
        &&& s_.log == if mentries == Seq::empty() { s.log } else { s.log.subrange(1 - 1, mprev_log_index).push(mentries[0]) }
        &&& s_.commit_index == mcommit_index
        &&& s_.ostate == if s.config.members.contains(c.node_id) { LOstate::Follower } else { LOstate::NotMember }
        &&& sent_packets == set![LPacket { dst: src, msg: LMessage::Aep { mterm: s.current_term, mresult: LAepMresult::Ok, mmatch_index: mprev_log_index + (mentries.len() as int) } }]
        &&& s_.current_term == s.current_term
        &&& s_.voted_for == s.voted_for
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LBHandleAppendEntriesResponse(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        mterm: int,
        mresult: LAepMresult,
        mmatch_index: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& mterm == s.current_term
        &&& s.ostate is Leader
        &&& s_.next_index == if mresult is Ok { s.next_index.insert(src, mmatch_index + 1) } else { if mresult is EntryMismatch { s.next_index.insert(src, if s.next_index[src] > 1 { s.next_index[src] - 1 } else { 1 }) } else { s.next_index } }
        &&& s_.match_index == if mresult is Ok { s.match_index.insert(src, mmatch_index) } else { s.match_index }
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LBAdvanceCommitIndex(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& s.ostate is Leader
        &&& exists|k: int| 0 <= k && k <= (s.log.len() as int) - 1 && k + 1 > s.commit_index && LBIsQuorumOf(c, c.server.filter(|j: int| s.match_index[j] >= k + 1).union(set![c.node_id]), s.config.members) && s.log[k].term == s.current_term && s_.commit_index == k + 1
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LBRequestReconfig(
        s: LState,
        s_: LState,
        c: LConstants,
        op: LPendingReconfigOp,
        target: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& s.ostate is Leader
        &&& s.pending_reconfig == LPendingReconfig { op: LPendingReconfigOp::None, target: 0 }
        &&& s.config.committed
        &&& op is Add && !s.config.members.contains(target) || op is Remove && s.config.members.contains(target)
        &&& s_.pending_reconfig == LPendingReconfig { op: op, target: target }
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LJClientSendPreaccept(
        s: LState,
        s_: LState,
        c: LConstants,
        cmd: LJCommand,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.client.contains(c.node_id)
        &&& s.client_pending == LJCommand { cmd_id: 0, key: 0 }
        &&& s_.client_pending == cmd
        &&& s_.client_successes == Set::<int>::empty()
        &&& s_.client_heard_from == Set::<int>::empty()
        &&& sent_packets == s.client_members.map(|d: int| LPacket { dst: d, msg: LMessage::Paq { mepoch: s.client_epoch, mcmd: cmd } })
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LJHandlePreacceptRequest(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        mepoch: int,
        mcmd: LJCommand,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.server.contains(c.node_id)
        &&& s_.cmd_pool == if mepoch == s.jepoch && s.jstate is Ready && !(LJHasConflict(c, s.cmd_pool, mcmd)) { s.cmd_pool.insert(mcmd.key, mcmd) } else { s.cmd_pool }
        &&& sent_packets == set![LPacket { dst: src, msg: LMessage::Pap { msuccess: mepoch == s.jepoch && s.jstate is Ready && !(LJHasConflict(c, s.cmd_pool, mcmd)), mjepoch: s.jepoch, mview_epoch: s.view_epoch, mview_members: s.view_members, mview_proposers: s.view_proposers, mcmd: mcmd } }]
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LJHandlePreacceptResponse(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        mcmd: LJCommand,
        msuccess: bool,
        mjepoch: int,
        mview_epoch: int,
        mview_members: Set<int>,
        mview_proposers: Set<int>,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.client.contains(c.node_id)
        &&& s.client_pending != LJCommand { cmd_id: 0, key: 0 }
        &&& s_.client_successes == if LJIsFastQuorum(c, if msuccess { s.client_successes.union(set![src]) } else { s.client_successes }, s.client_members, s.client_proposers) || !(LJIsFastQuorum(c, (if msuccess { s.client_successes.union(set![src]) } else { s.client_successes }).union(s.client_members.difference(s.client_heard_from.union(set![src]))), s.client_members, s.client_proposers)) { Set::empty() } else { if msuccess { s.client_successes.union(set![src]) } else { s.client_successes } }
        &&& s_.client_heard_from == if LJIsFastQuorum(c, if msuccess { s.client_successes.union(set![src]) } else { s.client_successes }, s.client_members, s.client_proposers) || !(LJIsFastQuorum(c, (if msuccess { s.client_successes.union(set![src]) } else { s.client_successes }).union(s.client_members.difference(s.client_heard_from.union(set![src]))), s.client_members, s.client_proposers)) { Set::empty() } else { s.client_heard_from.union(set![src]) }
        &&& s_.client_pending == if LJIsFastQuorum(c, if msuccess { s.client_successes.union(set![src]) } else { s.client_successes }, s.client_members, s.client_proposers) || !(LJIsFastQuorum(c, (if msuccess { s.client_successes.union(set![src]) } else { s.client_successes }).union(s.client_members.difference(s.client_heard_from.union(set![src]))), s.client_members, s.client_proposers)) { LJCommand { cmd_id: 0, key: 0 } } else { s.client_pending }
        &&& s_.client_epoch == if !(msuccess) && mview_epoch > s.client_epoch { mview_epoch } else { s.client_epoch }
        &&& s_.client_members == if !(msuccess) && mview_epoch > s.client_epoch { mview_members } else { s.client_members }
        &&& s_.client_proposers == if !(msuccess) && mview_epoch > s.client_epoch { mview_proposers } else { s.client_proposers }
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
    }

    pub open spec fn LJSendBeginRecovery(
        s: LState,
        s_: LState,
        c: LConstants,
        b: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.server.contains(c.node_id)
        &&& s.jstate is Ready
        &&& b > s.jepoch
        &&& s_.jepoch == b
        &&& s_.jstate is Recovery
        &&& s_.recovery_set == Set::<int>::empty()
        &&& s_.highest_seen_ballot == 0
        &&& s_.highest_seen_value == Set::<LJCommand>::empty()
        &&& sent_packets == s.view_members.map(|d: int| LPacket { dst: d, msg: LMessage::Brq { mjepoch: b, mview_epoch: s.view_epoch, mview_members: s.view_members, mview_proposers: s.view_proposers } })
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LJHandleBeginRecoveryRequest(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        mjepoch: int,
        mview_epoch: int,
        mview_members: Set<int>,
        mview_proposers: Set<int>,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.server.contains(c.node_id)
        &&& s_.jstate is Recovery
        &&& s_.view_epoch == mview_epoch
        &&& s_.view_members == mview_members
        &&& s_.view_proposers == mview_proposers
        &&& s_.oepoch == mview_epoch
        &&& sent_packets == set![LPacket { dst: src, msg: LMessage::Brp { maccepted_ballot: s.accepted_ballot, maccepted_value: s.accepted_value } }]
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jepoch == s.jepoch
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LJHandleBeginRecoveryResponse(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        maccepted_ballot: int,
        maccepted_value: Set<LJCommand>,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.server.contains(c.node_id)
        &&& s.jstate is Recovery
        &&& s_.recovery_set == s.recovery_set.union(set![src])
        &&& s_.highest_seen_ballot == if maccepted_ballot > s.highest_seen_ballot { maccepted_ballot } else { s.highest_seen_ballot }
        &&& s_.highest_seen_value == if maccepted_ballot > s.highest_seen_ballot { maccepted_value } else { s.highest_seen_value }
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LJCompleteBeginRecovery(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.server.contains(c.node_id)
        &&& s.jstate is Recovery
        &&& LJIsQuorum(c, s.recovery_set, s.view_members)
        &&& s_.chosen_value == s.highest_seen_value
        &&& s_.jstate is AfterBeginRecovery
        &&& s_.prep_rcvd == Set::<int>::empty()
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LJSendPrepare(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.server.contains(c.node_id)
        &&& s.jstate is AfterBeginRecovery
        &&& sent_packets == s.view_members.map(|d: int| LPacket { dst: d, msg: LMessage::Pq { mballot: s.jepoch, moepoch: s.oepoch } })
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LJHandlePrepareRequest(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        mballot: int,
        moepoch: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.server.contains(c.node_id)
        &&& moepoch >= s.oepoch
        &&& mballot >= s.max_seen_ballot
        &&& s_.max_seen_ballot == mballot
        &&& s_.oepoch == moepoch
        &&& sent_packets == set![LPacket { dst: src, msg: LMessage::Pp { mballot: mballot, maccepted_ballot: s.accepted_ballot, maccepted_value: s.accepted_value } }]
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LJHandlePrepareResponse(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        maccepted_ballot: int,
        maccepted_value: Set<LJCommand>,
        mballot: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.server.contains(c.node_id)
        &&& mballot == s.jepoch
        &&& s_.prep_rcvd == s.prep_rcvd.union(set![src])
        &&& s_.highest_seen_ballot == if maccepted_ballot > s.highest_seen_ballot { maccepted_ballot } else { s.highest_seen_ballot }
        &&& s_.highest_seen_value == if maccepted_ballot > s.highest_seen_ballot { maccepted_value } else { s.highest_seen_value }
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LJCompletePrepare(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.server.contains(c.node_id)
        &&& s.jstate is AfterBeginRecovery
        &&& LJIsQuorum(c, s.prep_rcvd, s.view_members)
        &&& s_.chosen_value == if s.highest_seen_ballot > 0 { s.highest_seen_value } else { s.chosen_value }
        &&& s_.jstate is AfterPrepare
        &&& s_.accept_rcvd == Set::<int>::empty()
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LJSendAccept(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.server.contains(c.node_id)
        &&& s.jstate is AfterPrepare
        &&& sent_packets == s.view_members.map(|d: int| LPacket { dst: d, msg: LMessage::Aq { mballot: s.jepoch, mvalue: s.chosen_value } })
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LJHandleAcceptRequest(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        mballot: int,
        mvalue: Set<LJCommand>,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.server.contains(c.node_id)
        &&& mballot >= s.max_seen_ballot
        &&& s_.max_seen_ballot == mballot
        &&& s_.accepted_ballot == mballot
        &&& s_.accepted_value == mvalue
        &&& sent_packets == set![LPacket { dst: src, msg: LMessage::Ap { mballot: mballot } }]
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LJHandleAcceptResponse(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        mballot: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.server.contains(c.node_id)
        &&& mballot == s.jepoch
        &&& s_.accept_rcvd == s.accept_rcvd.union(set![src])
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jstate == s.jstate
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LJCompleteAccept(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.server.contains(c.node_id)
        &&& s.jstate is AfterPrepare
        &&& LJIsQuorum(c, s.accept_rcvd, s.view_members)
        &&& s_.jstate is AfterAccept
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LJResubmit(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.server.contains(c.node_id)
        &&& s.jstate is AfterAccept
        &&& s_.jstate is AfterResubmit
        &&& sent_packets == s.view_proposers.map(|d: int| s.chosen_value.map(|cmd: LJCommand| LPacket { dst: d, msg: LMessage::Paq { mepoch: s.jepoch, mcmd: cmd } })).flatten()
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LJFinishRecovery(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.server.contains(c.node_id)
        &&& s.jstate is AfterResubmit
        &&& s_.jstate is Ready
        &&& s_.recovery_set == Set::<int>::empty()
        &&& s_.prep_rcvd == Set::<int>::empty()
        &&& s_.accept_rcvd == Set::<int>::empty()
        &&& sent_packets == s.view_members.map(|d: int| LPacket { dst: d, msg: LMessage::Fin { mjepoch: s.jepoch } })
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    pub open spec fn LJHandleFinishRecovery(
        s: LState,
        s_: LState,
        c: LConstants,
        mjepoch: int,
        sent_packets: Set<LPacket>,
    ) -> bool {
        &&& c.server.contains(c.node_id)
        &&& s_.jstate == if s.jstate is Recovery { LJstate::Ready } else { s.jstate }
        &&& sent_packets == Set::<LPacket>::empty()
        &&& s_.current_term == s.current_term
        &&& s_.ostate == s.ostate
        &&& s_.voted_for == s.voted_for
        &&& s_.log == s.log
        &&& s_.commit_index == s.commit_index
        &&& s_.votes_granted == s.votes_granted
        &&& s_.next_index == s.next_index
        &&& s_.match_index == s.match_index
        &&& s_.config == s.config
        &&& s_.pending_reconfig == s.pending_reconfig
        &&& s_.election_ctr == s.election_ctr
        &&& s_.restart_ctr == s.restart_ctr
        &&& s_.jepoch == s.jepoch
        &&& s_.oepoch == s.oepoch
        &&& s_.view_epoch == s.view_epoch
        &&& s_.view_members == s.view_members
        &&& s_.view_proposers == s.view_proposers
        &&& s_.max_seen_ballot == s.max_seen_ballot
        &&& s_.accepted_ballot == s.accepted_ballot
        &&& s_.accepted_value == s.accepted_value
        &&& s_.cmd_pool == s.cmd_pool
        &&& s_.recovery_set == s.recovery_set
        &&& s_.prep_rcvd == s.prep_rcvd
        &&& s_.accept_rcvd == s.accept_rcvd
        &&& s_.chosen_value == s.chosen_value
        &&& s_.highest_seen_ballot == s.highest_seen_ballot
        &&& s_.highest_seen_value == s.highest_seen_value
        &&& s_.client_pending == s.client_pending
        &&& s_.client_successes == s.client_successes
        &&& s_.client_heard_from == s.client_heard_from
        &&& s_.client_epoch == s.client_epoch
        &&& s_.client_members == s.client_members
        &&& s_.client_proposers == s.client_proposers
    }

    /// Dispatch on the received message. Delivery and the tag are the
    /// framework's; each handler states only its own conditions.
    pub open spec fn LHandleMessage(
        s: LState,
        s_: LState,
        c: LConstants,
        src: int,
        msg: LMessage,
        sent_packets: Set<LPacket>,
    ) -> bool {
        match msg {
            LMessage::Rvq { mterm, mlast_log_term, mlast_log_index } =>
                LBUpdateTerm(s, s_, c, mterm, sent_packets)
                || LBHandleRequestVoteRequest(s, s_, c, src, mterm, mlast_log_term, mlast_log_index, sent_packets),
            LMessage::Rvp { mterm, mvote_granted } =>
                LBUpdateTerm(s, s_, c, mterm, sent_packets)
                || LBHandleRequestVoteResponse(s, s_, c, src, mterm, mvote_granted, sent_packets),
            LMessage::Aeq { mterm, mprev_log_index, mprev_log_term, mentries, mcommit_index } =>
                LBUpdateTerm(s, s_, c, mterm, sent_packets)
                || LBRejectAppendEntriesRequest(s, s_, c, src, mterm, mprev_log_index, mprev_log_term, mentries, mcommit_index, sent_packets)
                || LBAcceptAppendEntriesRequest(s, s_, c, src, mterm, mprev_log_index, mprev_log_term, mentries, mcommit_index, sent_packets),
            LMessage::Aep { mterm, mresult, mmatch_index } =>
                LBUpdateTerm(s, s_, c, mterm, sent_packets)
                || LBHandleAppendEntriesResponse(s, s_, c, src, mterm, mresult, mmatch_index, sent_packets),
            LMessage::Paq { mepoch, mcmd } =>
                LJHandlePreacceptRequest(s, s_, c, src, mepoch, mcmd, sent_packets),
            LMessage::Pap { mcmd, msuccess, mjepoch, mview_epoch, mview_members, mview_proposers } =>
                LJHandlePreacceptResponse(s, s_, c, src, mcmd, msuccess, mjepoch, mview_epoch, mview_members, mview_proposers, sent_packets),
            LMessage::Brq { mjepoch, mview_epoch, mview_members, mview_proposers } =>
                LJHandleBeginRecoveryRequest(s, s_, c, src, mjepoch, mview_epoch, mview_members, mview_proposers, sent_packets),
            LMessage::Brp { maccepted_ballot, maccepted_value } =>
                LJHandleBeginRecoveryResponse(s, s_, c, src, maccepted_ballot, maccepted_value, sent_packets),
            LMessage::Pq { mballot, moepoch } =>
                LJHandlePrepareRequest(s, s_, c, src, mballot, moepoch, sent_packets),
            LMessage::Pp { maccepted_ballot, maccepted_value, mballot } =>
                LJHandlePrepareResponse(s, s_, c, src, maccepted_ballot, maccepted_value, mballot, sent_packets),
            LMessage::Aq { mballot, mvalue } =>
                LJHandleAcceptRequest(s, s_, c, src, mballot, mvalue, sent_packets),
            LMessage::Ap { mballot } =>
                LJHandleAcceptResponse(s, s_, c, src, mballot, sent_packets),
            LMessage::Fin { mjepoch } =>
                LJHandleFinishRecovery(s, s_, c, mjepoch, sent_packets),
        }
    }

    pub open spec fn LNext(
        s: LState,
        s_: LState,
        c: LConstants,
        sent_packets: Set<LPacket>,
    ) -> bool {
        ||| LPromoteToLeader(s, s_, c, sent_packets)
        ||| LBRestart(s, s_, c, sent_packets)
        ||| LBRequestVote(s, s_, c, sent_packets)
        ||| LBBecomeToBeLeader(s, s_, c, sent_packets)
        ||| (exists|v: int|
                c.commands.contains(v) && LBClientRequest(s, s_, c, v, sent_packets))
        ||| (exists|j: int|
                c.server.contains(j) && LBAppendEntries(s, s_, c, j, sent_packets))
        ||| LBAdvanceCommitIndex(s, s_, c, sent_packets)
        ||| (exists|op: LPendingReconfigOp, target: int|
                op is Add || op is Remove && c.server.contains(target) && LBRequestReconfig(s, s_, c, op, target, sent_packets))
        ||| (exists|cmd: LJCommand|
                LJClientSendPreaccept(s, s_, c, cmd, sent_packets))
        ||| (exists|b: int|
                LJSendBeginRecovery(s, s_, c, b, sent_packets))
        ||| LJCompleteBeginRecovery(s, s_, c, sent_packets)
        ||| LJSendPrepare(s, s_, c, sent_packets)
        ||| LJCompletePrepare(s, s_, c, sent_packets)
        ||| LJSendAccept(s, s_, c, sent_packets)
        ||| LJCompleteAccept(s, s_, c, sent_packets)
        ||| LJResubmit(s, s_, c, sent_packets)
        ||| LJFinishRecovery(s, s_, c, sent_packets)
        ||| (exists|src: int, msg: LMessage|
                LHandleMessage(s, s_, c, src, msg, sent_packets))
    }
}
