//! Generated from TLA+ module: Paxos
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;

verus! {

/// State for Paxos module
pub struct LState {
    pub maxBal: Set<int>,
    pub maxVBal: Set<int>,
    pub maxVal: Set<int>,
}


/// Acceptors operator
pub open spec fn LAcceptors() -> Set<int> {
    set![1, 2, 3]
}

/// Values operator
pub open spec fn LValues() -> Set<int> {
    set![1, 2, 3]
}

/// Init operator
pub open spec fn LInit(s: LState) -> bool {
    (((s.maxBal == Set::<int>::empty()) && (s.maxVBal == Set::<int>::empty())) && (s.maxVal == Set::<int>::empty()))
}

/// Send1a operator
pub open spec fn LSend1a(s: LState, s_: LState, b: int) -> bool {
    (((LAcceptors().contains(b) && (s_.maxBal == s.maxBal)) && (s_.maxVBal == s.maxVBal)) && (s_.maxVal == s.maxVal))
}

/// Send1b operator
pub open spec fn LSend1b(s: LState, s_: LState, a: int, b: int) -> bool {
    ((((LAcceptors().contains(a) && LAcceptors().contains(b)) && (s_.maxBal == s.maxBal.union(set![b]))) && (s_.maxVBal == s.maxVBal)) && (s_.maxVal == s.maxVal))
}

/// Send2a operator
pub open spec fn LSend2a(s: LState, s_: LState, b: int, v: int) -> bool {
    (((((LAcceptors().contains(b) && LValues().contains(v)) && ((s.maxVal == Set::<int>::empty()) || s.maxVal.contains(v))) && (s_.maxBal == s.maxBal)) && (s_.maxVBal == s.maxVBal.union(set![b]))) && (s_.maxVal == s.maxVal))
}

/// Send2b operator
pub open spec fn LSend2b(s: LState, s_: LState, a: int, b: int, v: int) -> bool {
    ((((((LAcceptors().contains(a) && LAcceptors().contains(b)) && LValues().contains(v)) && ((s.maxVal == Set::<int>::empty()) || s.maxVal.contains(v))) && (s_.maxBal == s.maxBal)) && (s_.maxVBal == s.maxVBal.union(set![b]))) && (s_.maxVal == s.maxVal.union(set![v])))
}

/// Next operator
pub open spec fn LNext(s: LState, s_: LState) -> bool {
    (((((((((((((((((((((((((((((((((((((((((((((((LSend1a(s, s_, 1) || LSend1a(s, s_, 2)) || LSend1a(s, s_, 3)) || LSend1b(s, s_, 1, 1)) || LSend1b(s, s_, 1, 2)) || LSend1b(s, s_, 1, 3)) || LSend1b(s, s_, 2, 1)) || LSend1b(s, s_, 2, 2)) || LSend1b(s, s_, 2, 3)) || LSend1b(s, s_, 3, 1)) || LSend1b(s, s_, 3, 2)) || LSend1b(s, s_, 3, 3)) || LSend2a(s, s_, 1, 1)) || LSend2a(s, s_, 1, 2)) || LSend2a(s, s_, 1, 3)) || LSend2a(s, s_, 2, 1)) || LSend2a(s, s_, 2, 2)) || LSend2a(s, s_, 2, 3)) || LSend2a(s, s_, 3, 1)) || LSend2a(s, s_, 3, 2)) || LSend2a(s, s_, 3, 3)) || LSend2b(s, s_, 1, 1, 1)) || LSend2b(s, s_, 1, 1, 2)) || LSend2b(s, s_, 1, 1, 3)) || LSend2b(s, s_, 1, 2, 1)) || LSend2b(s, s_, 1, 2, 2)) || LSend2b(s, s_, 1, 2, 3)) || LSend2b(s, s_, 1, 3, 1)) || LSend2b(s, s_, 1, 3, 2)) || LSend2b(s, s_, 1, 3, 3)) || LSend2b(s, s_, 2, 1, 1)) || LSend2b(s, s_, 2, 1, 2)) || LSend2b(s, s_, 2, 1, 3)) || LSend2b(s, s_, 2, 2, 1)) || LSend2b(s, s_, 2, 2, 2)) || LSend2b(s, s_, 2, 2, 3)) || LSend2b(s, s_, 2, 3, 1)) || LSend2b(s, s_, 2, 3, 2)) || LSend2b(s, s_, 2, 3, 3)) || LSend2b(s, s_, 3, 1, 1)) || LSend2b(s, s_, 3, 1, 2)) || LSend2b(s, s_, 3, 1, 3)) || LSend2b(s, s_, 3, 2, 1)) || LSend2b(s, s_, 3, 2, 2)) || LSend2b(s, s_, 3, 2, 3)) || LSend2b(s, s_, 3, 3, 1)) || LSend2b(s, s_, 3, 3, 2)) || LSend2b(s, s_, 3, 3, 3))
}

/// ChosenValueAgreement operator
pub open spec fn LChosenValueAgreement(s: LState) -> bool {
    forall |v1: int, v2: int| #![trigger (v1 + 0)] #![trigger (v2 + 0)] (s.maxVal.contains(v1) && s.maxVal.contains(v2)) ==> (v1 == v2)
}

/// TypeOK operator
pub open spec fn LTypeOK(s: LState) -> bool {
    ((s.maxBal.subset_of(LAcceptors()) && s.maxVBal.subset_of(LAcceptors())) && s.maxVal.subset_of(LValues()))
}

} // verus!
