//! Generated from TLA+ module: Types
//!
//! This file was auto-generated by verus-transpiler.

use vstd::prelude::*;
use vstd::seq::*;
use vstd::set::*;

verus! {

/// Record type for Types module
pub struct LRecord {
    pub accepts_rcvd: int,
    pub committed: int,
    pub committed_val: int,
    pub config_num: int,
    pub has_voted: int,
    pub has_witness: int,
    pub is_active: int,
    pub max_bal: int,
    pub max_v_bal: int,
    pub max_val: int,
    pub node_id: int,
    pub num_nodes: int,
    pub promises_rcvd: int,
    pub quorum_size: int,
    pub witness_val: int,
}

/// State for Types module
pub struct LState {
}


/// Constants operator
pub open spec fn LConstants() -> { node_id: Set<int>, quorum_size: Set<int>, num_nodes: Set<int> } {
    LRecord { accepts_rcvd: 0int, committed: 0int, committed_val: 0int, config_num: 0int, has_voted: 0int, has_witness: 0int, is_active: 0int, max_bal: 0int, max_v_bal: 0int, max_val: 0int, node_id: int, num_nodes: int, promises_rcvd: 0int, quorum_size: int, witness_val: 0int }
}

/// State operator
pub open spec fn LState() -> { witness_val: Set<int>, config_num: Set<int>, committed: Set<bool>, has_witness: Set<bool>, committed_val: Set<int>, max_val: Set<int>, max_v_bal: Set<int>, promises_rcvd: Set<Set<int>>, has_voted: Set<bool>, max_bal: Set<int>, is_active: Set<bool>, accepts_rcvd: Set<Set<int>> } {
    LRecord { accepts_rcvd: int.powerset(), committed: bool, committed_val: int, config_num: int, has_voted: bool, has_witness: bool, is_active: bool, max_bal: int, max_v_bal: int, max_val: int, node_id: 0int, num_nodes: 0int, promises_rcvd: int.powerset(), quorum_size: 0int, witness_val: int }
}

/// VPMessage operator
pub open spec fn LVPMessage() -> Set<int> {
    set![Prepare, Promise, Accept]
}

} // verus!
